import { desc, eq } from "drizzle-orm";
import { getDb } from "../../../../../db";
import { optimizationArtifactQa, optimizationArtifacts, optimizationCycles, optimizationSettings, optimizationStageRuns, researchClaims, researchSources, videoProjects, workflowEvents } from "../../../../../db/schema";

type RuntimeD1 = { prepare(sql: string): { run(): Promise<unknown> } };
type RuntimeEnv = { DB?: RuntimeD1 };
type Mode = "AUTOPILOT" | "EXCEPTIONS" | "MANUAL";
type StageStatus = "PASSED_REUSED" | "READY" | "TOURNAMENT_RUNNING" | "WORK_PACKET_READY" | "ARTIFACT_GENERATING" | "ARTIFACT_READY" | "MICRO_QA_RUNNING" | "REPAIR_REQUIRED" | "VERIFIED" | "FROZEN" | "HANDOFF_READY" | "INVALIDATED" | "AWAITING_APPROVAL" | "ESCALATED" | "BLOCKED";
type StageState = { key: string; order: number; status: StageStatus; score: number | null; attempt: number; evidence: string };
type Issue = { id: string; severity: "P0" | "P1" | "P2"; artifact: string; issue: string; evidence: string; rootCause: string; owner: string; acceptance: string; status: "OPEN" | "ROUTED" | "RESOLVED" | "ESCALATED"; stageKey: string };

type Contract = {
  key: string; order: number; label: string; objective: string; optimizeFor: string[]; inputs: string[]; deliverable: string;
  candidatePolicy: string; evaluators: string[]; hardGates: string[]; threshold: number; attemptLimit: number; invalidates: string[];
};

const contracts: Contract[] = [
  { key: "CHANNEL_THESIS", order: 1, label: "Channel thesis", objective: "Prove a durable channel territory before producing individual videos.", optimizeFor: ["Demand durability", "Ad economics", "Series depth", "Faceless feasibility"], inputs: ["US market", "English language", "Ads-first revenue model"], deliverable: "Versioned channel thesis and 50-topic capacity test", candidatePolicy: "Compare 3–5 niche territories", evaluators: ["Market strategist", "Monetization critic", "Production feasibility critic"], hardGates: ["50+ viable topics", "No identity dependency", "Advertiser-compatible territory"], threshold: 85, attemptLimit: 2, invalidates: ["AUDIENCE_MODEL", "TOPIC_DISCOVERY"] },
  { key: "AUDIENCE_MODEL", order: 2, label: "Audience intelligence", objective: "Define the viewer transformation and the context in which the viewer chooses to watch.", optimizeFor: ["Specificity", "Unmet questions", "Knowledge gap", "Emotional relevance"], inputs: ["Channel thesis", "Audience evidence"], deliverable: "Viewer model, jobs-to-be-done and transformation statement", candidatePolicy: "Compare 3 audience segments", evaluators: ["Audience advocate", "Behavior critic", "Clarity judge"], hardGates: ["One primary viewer", "Explicit before/after transformation"], threshold: 85, attemptLimit: 3, invalidates: ["TOPIC_DISCOVERY", "CREATIVE_STRATEGY"] },
  { key: "TOPIC_DISCOVERY", order: 3, label: "Topic discovery", objective: "Select a topic with demand, differentiation and production leverage.", optimizeFor: ["Demand", "Novelty", "Channel fit", "Series potential", "Feasibility"], inputs: ["Channel thesis", "Audience model", "Reference signals"], deliverable: "Ranked topic tournament with champion and backup", candidatePolicy: "Generate 20–30 topics, shortlist 5, retain 1 champion", evaluators: ["Demand analyst", "Competition critic", "Series strategist"], hardGates: ["Evidence of demand", "Distinct angle exists", "Can become a series"], threshold: 86, attemptLimit: 3, invalidates: ["CREATIVE_STRATEGY", "RESEARCH"] },
  { key: "CREATIVE_STRATEGY", order: 4, label: "Creative strategy", objective: "Turn a good topic into a compelling, ownable viewer experience.", optimizeFor: ["Promise", "Thesis", "Stakes", "Payoff", "Visual opportunity"], inputs: ["Winning topic", "Audience transformation", "Reference patterns"], deliverable: "Creative contract with champion angle, emotional arc and payoff", candidatePolicy: "Tournament 4 differentiated angles", evaluators: ["Creative director", "Audience advocate", "Originality guard", "Adversarial critic"], hardGates: ["Promise is concrete", "Angle differs from references", "Visual engine is viable"], threshold: 88, attemptLimit: 3, invalidates: ["RESEARCH", "OUTLINE"] },
  { key: "RESEARCH", order: 5, label: "Research & evidence", objective: "Build a claim-safe, insight-rich evidence pack before scripting.", optimizeFor: ["Authority", "Coverage", "Freshness", "Counter-evidence", "Concrete examples"], inputs: ["Creative contract", "Research questions"], deliverable: "Claim map, source hierarchy and uncertainty ledger", candidatePolicy: "Compare primary-source packs and competing explanations", evaluators: ["Evidence auditor", "Skeptical researcher", "Fact verifier"], hardGates: ["Every P0 claim sourced", "Fact/inference/opinion separated", "Contradictions resolved"], threshold: 90, attemptLimit: 3, invalidates: ["OUTLINE", "SCRIPT"] },
  { key: "OUTLINE", order: 6, label: "Story architecture", objective: "Choose the narrative structure with the best clarity, escalation and retention potential.", optimizeFor: ["Hook", "Escalation", "Cognitive load", "Visual potential", "Payoff"], inputs: ["Creative contract", "Verified claim map"], deliverable: "Timed 3-act outline and beat map", candidatePolicy: "Compare 3 narrative architectures", evaluators: ["Story editor", "Retention critic", "Visual storyteller"], hardGates: ["Every beat changes viewer understanding", "Payoff resolves the promise"], threshold: 88, attemptLimit: 3, invalidates: ["SCRIPT", "VISUAL_LANGUAGE"] },
  { key: "SCRIPT", order: 7, label: "Script development", objective: "Create a natural, accurate and competitive spoken narrative.", optimizeFor: ["Depth", "Clarity", "Natural speech", "Curiosity", "Runtime", "Originality"], inputs: ["Winning outline", "Claim map", "Voice profile"], deliverable: "950–1,300 word locked narration with claim links", candidatePolicy: "5–10 hooks, 3 openings, 2 full-script challengers", evaluators: ["Hook critic", "Story critic", "Evidence critic", "Spoken-language critic"], hardGates: ["5–10 minute target", "No unsupported claims", "No redundant section"], threshold: 90, attemptLimit: 3, invalidates: ["VISUAL_LANGUAGE", "STORYBOARD", "VOICE_SOUND"] },
  { key: "VISUAL_LANGUAGE", order: 8, label: "Visual language", objective: "Design an ownable channel-level visual system before sourcing scenes.", optimizeFor: ["Brand distinction", "Readability", "Motion grammar", "Format variety"], inputs: ["Script", "Channel brand"], deliverable: "Color, type, diagram, chart, map, motion and transition system", candidatePolicy: "Compare 3 visual directions", evaluators: ["Art director", "Motion director", "Mobile readability critic"], hardGates: ["1080p system", "Mobile-safe labels", "Repeatable channel grammar"], threshold: 88, attemptLimit: 3, invalidates: ["STORYBOARD", "ASSET_TOURNAMENT"] },
  { key: "STORYBOARD", order: 9, label: "Storyboard & visual beats", objective: "Translate every narrative beat into a varied, purposeful audiovisual plan.", optimizeFor: ["Semantic fit", "Visual density", "Variety", "Continuity", "Pacing"], inputs: ["Locked script", "Visual language"], deliverable: "35–45 visual beats with movement and transitions", candidatePolicy: "2–3 treatments for every high-impact beat", evaluators: ["Storyboard critic", "Retention editor", "Cognitive-load critic"], hardGates: ["No visual state >7s", "At least 5 visual families", "No unexplained repetition"], threshold: 90, attemptLimit: 3, invalidates: ["ASSET_TOURNAMENT", "VOICE_SOUND", "EDIT_COMPOSE"] },
  { key: "ASSET_TOURNAMENT", order: 10, label: "Asset tournament", objective: "Select the best legal, high-fidelity asset for every visual beat.", optimizeFor: ["Semantic fit", "Fidelity", "Originality", "Motion potential", "Rights", "Cost"], inputs: ["Storyboard", "Source policy", "Budget"], deliverable: "Approved asset manifest with provenance and alternates", candidatePolicy: "3–5 candidates for every P0 visual beat", evaluators: ["Visual matcher", "Quality critic", "Rights guard"], hardGates: ["Commercial rights verified", "Source fidelity adequate", "No duplicate-heavy sequence"], threshold: 90, attemptLimit: 3, invalidates: ["EDIT_COMPOSE"] },
  { key: "VOICE_SOUND", order: 11, label: "Voice & sound design", objective: "Build narration and a designed soundscape that supports the emotional arc.", optimizeFor: ["Natural voice", "Pronunciation", "Music arc", "Ambience", "SFX", "Mix"], inputs: ["Locked script", "Storyboard timing"], deliverable: "Approved narration, music cue sheet, SFX plan and mix targets", candidatePolicy: "2–3 takes for critical lines; 3 music directions", evaluators: ["Voice director", "Sound designer", "Mix critic"], hardGates: ["No clipping", "Music license verified", "Measured loudness plan"], threshold: 90, attemptLimit: 3, invalidates: ["EDIT_COMPOSE"] },
  { key: "EDIT_COMPOSE", order: 12, label: "Edit & composition", objective: "Assemble a coherent, high-fidelity master optimized for viewer attention.", optimizeFor: ["Synchronization", "Rhythm", "Continuity", "Pattern interrupts", "Fidelity"], inputs: ["Approved assets", "Narration", "Soundscape", "Storyboard"], deliverable: "1080p release candidate with retention-risk map", candidatePolicy: "Champion edit plus one pacing challenger", evaluators: ["Film editor", "Retention critic", "Audiovisual QA"], hardGates: ["1080p master", "Full playback pass", "No P0 audiovisual defect"], threshold: 90, attemptLimit: 3, invalidates: ["PACKAGING", "FINAL_QA"] },
  { key: "PACKAGING", order: 13, label: "Packaging tournament", objective: "Create an accurate, differentiated click promise for the finished video.", optimizeFor: ["Curiosity", "Clarity", "Mobile readability", "Differentiation", "Promise alignment"], inputs: ["Approved master", "Audience model", "Reference environment"], deliverable: "3 test-ready title-thumbnail combinations", candidatePolicy: "5–10 titles and 3 thumbnail concepts", evaluators: ["Packaging strategist", "Audience critic", "Promise verifier"], hardGates: ["No promise mismatch", "Mobile legibility", "No cloning"], threshold: 90, attemptLimit: 3, invalidates: ["FINAL_QA"] },
  { key: "FINAL_QA", order: 14, label: "Final QA & release", objective: "Verify the complete system without using late-stage QA to compensate for weak construction.", optimizeFor: ["Perceived quality", "Technical integrity", "Rights", "Policy", "Accessibility"], inputs: ["Release candidate", "Package variants", "Audit trails"], deliverable: "Release decision and immutable publishing package", candidatePolicy: "One champion RC; challengers only if material improvement is plausible", evaluators: ["Universal Quality Gate", "Deep media analyzer", "Release manager"], hardGates: ["No P0/P1 issues", "Composite ≥85", "Competitive parity ≥75"], threshold: 90, attemptLimit: 2, invalidates: ["RELEASE_LEARNING"] },
  { key: "RELEASE_LEARNING", order: 15, label: "Release & learning", objective: "Convert real viewer behavior into calibrated improvements for the next video.", optimizeFor: ["CTR by source", "Retention", "Satisfaction", "Session continuation", "Learning value"], inputs: ["YouTube analytics", "Comments", "Experiment results"], deliverable: "Post-release learning packet and updated benchmarks", candidatePolicy: "Compare hypotheses, not cosmetic changes", evaluators: ["Analytics agent", "Audience researcher", "Calibration judge"], hardGates: ["No metric without context", "Learning linked to next decision"], threshold: 85, attemptLimit: 2, invalidates: [] },
];

const candidateLibrary: Record<string, Array<{ label: string; thesis: string; scores: Record<string, number>; risks: string[] }>> = {
  CREATIVE_STRATEGY: [
    { label: "Approval is not payment", thesis: "Open on the approved terminal, then reveal why no money has moved and follow the delayed $100.", scores: { Promise: 94, Originality: 92, Stakes: 88, Visuals: 94 }, risks: ["Requires settlement timing evidence"] },
    { label: "One tap, six companies", thesis: "Treat the transaction network as a cast of six invisible participants competing for a piece of the sale.", scores: { Promise: 88, Originality: 86, Stakes: 84, Visuals: 91 }, risks: ["Can become list-like without a strong payoff"] },
    { label: "Where the $100 goes", thesis: "Anchor the story in one receipt and trace every fee, promise and eventual deposit.", scores: { Promise: 91, Originality: 88, Stakes: 92, Visuals: 90 }, risks: ["Fee figures require careful qualification"] },
    { label: "Generic swipe explainer", thesis: "Explain authorization, clearing and settlement in sequence.", scores: { Promise: 70, Originality: 58, Stakes: 63, Visuals: 72 }, risks: ["Below competitor differentiation"] },
  ],
  RESEARCH: [
    { label: "Primary systems pack", thesis: "Lead with Federal Reserve, CFPB and card-network documentation; use trade sources only for implementation detail.", scores: { Authority: 95, Coverage: 89, Freshness: 87, Counterevidence: 88 }, risks: ["Network rules can be technical"] },
    { label: "Merchant economics pack", thesis: "Lead with acquiring, interchange and merchant-cost evidence, anchored to an illustrative $100 sale.", scores: { Authority: 86, Coverage: 92, Freshness: 90, Counterevidence: 84 }, risks: ["Avoid presenting variable fees as universal"] },
    { label: "Creator-source summary", thesis: "Use existing explainers and payment blogs as the main evidence layer.", scores: { Authority: 58, Coverage: 75, Freshness: 78, Counterevidence: 55 }, risks: ["Circular sourcing", "Reused framing"] },
  ],
  OUTLINE: [
    { label: "Paradox → network → payoff", thesis: "Act 1 approval paradox; Act 2 six-party journey; Act 3 clearing, fees and merchant net deposit.", scores: { Hook: 95, Escalation: 91, Clarity: 92, Visuals: 94, Payoff: 93 }, risks: ["Must keep participant names legible"] },
    { label: "Receipt-first investigation", thesis: "Begin with a $100 receipt, investigate every deduction, then reveal settlement timing.", scores: { Hook: 89, Escalation: 90, Clarity: 94, Visuals: 91, Payoff: 95 }, risks: ["Authorization may feel secondary"] },
    { label: "Chronological process", thesis: "Explain each network stage in strict order from tap to deposit.", scores: { Hook: 72, Escalation: 68, Clarity: 90, Visuals: 80, Payoff: 76 }, risks: ["Educational but low tension"] },
  ],
  SCRIPT: [
    { label: "Mechanism-led challenger", thesis: "A 1,100-word narrated mini-documentary built around the approval paradox and incentives at each handoff.", scores: { Depth: 92, Speech: 89, Curiosity: 91, Accuracy: 90 }, risks: ["Needs ruthless terminology control"] },
    { label: "Receipt-led challenger", thesis: "A 1,000-word script where each section answers who touches the $100 and what they earn or risk.", scores: { Depth: 90, Speech: 92, Curiosity: 90, Accuracy: 88 }, risks: ["Illustrative numbers must be labeled"] },
    { label: "Short explainer", thesis: "Retain the current approximately one-minute script and add a stronger hook.", scores: { Depth: 42, Speech: 84, Curiosity: 70, Accuracy: 82 }, risks: ["Cannot meet mini-documentary promise"] },
  ],
  VISUAL_LANGUAGE: [
    { label: "Living transaction map", thesis: "Premium dark-green network maps, receipt-led counters, macro b-roll and restrained data motion.", scores: { Brand: 94, Readability: 90, Motion: 94, Variety: 92 }, risks: ["Requires consistent node grammar"] },
    { label: "Premium macro documentary", thesis: "Cinematic terminals, cards, merchants and banking infrastructure with minimal diagram overlays.", scores: { Brand: 88, Readability: 87, Motion: 84, Variety: 86 }, risks: ["Stock can become generic"] },
    { label: "Flat infographic", thesis: "Use mostly static diagrams and icons with simple transitions.", scores: { Brand: 68, Readability: 86, Motion: 60, Variety: 62 }, risks: ["Below reference visual richness"] },
  ],
  VOICE_SOUND: [
    { label: "Hidden-system pulse", thesis: "Authorization clicks, subtle data pulses, low investigative music and fee-reveal emphasis hits.", scores: { Voice: 90, Music: 92, SFX: 94, Mix: 88 }, risks: ["Avoid over-scoring every transition"] },
    { label: "Premium documentary restraint", thesis: "Sparse music, tactile terminal sounds, room ambience and selective low-frequency transitions.", scores: { Voice: 92, Music: 88, SFX: 86, Mix: 92 }, risks: ["Can feel slow without pacing discipline"] },
    { label: "Narration only", thesis: "Use the approved ElevenLabs voice without music or SFX.", scores: { Voice: 86, Music: 30, SFX: 20, Mix: 60 }, risks: ["No designed soundscape"] },
  ],
  PACKAGING: [
    { label: "APPROVED ≠ PAID", thesis: "Your Card Says Approved. Your Money Hasn't Moved.", scores: { Curiosity: 95, Clarity: 90, Mobile: 94, Differentiation: 92 }, risks: ["Video must resolve timing clearly"] },
    { label: "ONE TAP · SIX COMPANIES", thesis: "Six Companies Touch Your Money After One Tap", scores: { Curiosity: 91, Clarity: 92, Mobile: 90, Differentiation: 89 }, risks: ["Must introduce all six cleanly"] },
    { label: "$100 → WHO GETS IT?", thesis: "$100 Leaves Your Card. Who Actually Gets Paid?", scores: { Curiosity: 93, Clarity: 89, Mobile: 92, Differentiation: 91 }, risks: ["Avoid implying a single fixed fee split"] },
  ],
};

let schemaReady: Promise<void> | null = null;
async function runtimeEnv() { const { env } = await import("cloudflare:workers"); return env as unknown as RuntimeEnv; }
async function ensureSchema() {
  if (!schemaReady) schemaReady = (async () => {
    const env = await runtimeEnv(); if (!env.DB) throw new Error("Production database is unavailable");
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS optimization_settings (project_id text PRIMARY KEY NOT NULL, mode text DEFAULT 'AUTOPILOT' NOT NULL, maximum_attempts integer DEFAULT 3 NOT NULL, minimum_improvement integer DEFAULT 3 NOT NULL, maximum_wave_stages integer DEFAULT 4 NOT NULL, regression_tolerance integer DEFAULT 5 NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`).run();
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS optimization_cycles (id text PRIMARY KEY NOT NULL, project_id text NOT NULL, version integer NOT NULL, status text DEFAULT 'ACTIVE' NOT NULL, active_stage text NOT NULL, stage_state_json text NOT NULL, issue_ledger_json text NOT NULL, learning_json text NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`).run();
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS optimization_stage_runs (id text PRIMARY KEY NOT NULL, cycle_id text NOT NULL, project_id text NOT NULL, stage_key text NOT NULL, attempt integer DEFAULT 1 NOT NULL, status text NOT NULL, threshold integer NOT NULL, score integer DEFAULT 0 NOT NULL, contract_json text NOT NULL, candidates_json text NOT NULL, decision_json text NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`).run();
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS optimization_artifacts (id text PRIMARY KEY NOT NULL, cycle_id text NOT NULL, project_id text NOT NULL, stage_key text NOT NULL, version integer DEFAULT 1 NOT NULL, status text DEFAULT 'ARTIFACT_READY' NOT NULL, artifact_type text NOT NULL, title text NOT NULL, content_json text NOT NULL, source_run_id text NOT NULL, word_count integer DEFAULT 0 NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`).run();
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS optimization_artifact_qa (id text PRIMARY KEY NOT NULL, artifact_id text NOT NULL, cycle_id text NOT NULL, project_id text NOT NULL, stage_key text NOT NULL, attempt integer DEFAULT 1 NOT NULL, status text NOT NULL, decision text NOT NULL, score integer DEFAULT 0 NOT NULL, threshold integer NOT NULL, rubric_json text NOT NULL, issues_json text NOT NULL, regression_json text NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`).run();
  })().catch((error) => { schemaReady = null; throw error; }); await schemaReady;
}

function initialStages(): StageState[] { return contracts.map((contract) => ({ key: contract.key, order: contract.order, status: contract.order <= 3 ? "PASSED_REUSED" : contract.order === 4 ? "READY" : "INVALIDATED", score: contract.order <= 3 ? [88, 87, 86][contract.order - 1] : null, attempt: 0, evidence: contract.order <= 3 ? "Reused from the approved channel, audience and topic foundation; downstream execution invalidated by Quality Gate v2." : contract.order === 4 ? "First stage requiring a new optimized artifact." : "Blocked until upstream handoff passes." })); }
function initialIssues(): Issue[] { return [
  { id: "CQ-001", severity: "P0", artifact: "Script", issue: "Runtime and content depth are below mini-documentary quality.", evidence: "Current master is approximately 67 seconds; target is 7–10 minutes with 950+ words.", rootCause: "The initial MVP optimized for complete assembly rather than competitive depth.", owner: "Content architect", acceptance: "Locked 950–1,300 word script with a 3-act arc and verified claims.", status: "OPEN", stageKey: "SCRIPT" },
  { id: "CQ-002", severity: "P0", artifact: "Visual system", issue: "Visual fidelity and diversity are below competitor parity.", evidence: "Current master is 720p with a small set of visual units and families.", rootCause: "Storyboard used one scene per narration segment instead of a visual-beat system.", owner: "Visual director", acceptance: "1080p system, 35–45 visual beats, five visual families and no static state above seven seconds.", status: "OPEN", stageKey: "VISUAL_LANGUAGE" },
  { id: "CQ-003", severity: "P0", artifact: "Soundscape", issue: "Narration exists, but music, ambience and SFX are not designed.", evidence: "No complete background music and SFX inventory is detected.", rootCause: "Voice production was treated as the entire audio layer.", owner: "Sound director", acceptance: "Licensed music bed, ambience, transition SFX, emphasis hits and measured mix targets.", status: "OPEN", stageKey: "VOICE_SOUND" },
  { id: "CQ-004", severity: "P1", artifact: "Competitive intelligence", issue: "Reference analysis covers metadata and patterns, not scene-level production parity.", evidence: "No duration, visual-density or sound-design parity matrix is stored.", rootCause: "Reference Intelligence was introduced after the first master was complete.", owner: "Competitive analyst", acceptance: "Five-reference parity matrix linked to stage thresholds.", status: "OPEN", stageKey: "CREATIVE_STRATEGY" },
  { id: "CQ-005", severity: "P1", artifact: "Packaging", issue: "Current title is accurate but generic.", evidence: "Reference benchmark returned PACKAGE_ONLY before the stricter production review.", rootCause: "Packaging was optimized before the master met competitive quality.", owner: "Packaging strategist", acceptance: "Three promise-aligned test variants generated after final master approval.", status: "OPEN", stageKey: "PACKAGING" },
]; }
function genericCandidates(contract: Contract) { return [
  { label: `${contract.label} · champion`, thesis: `High-rigor ${contract.deliverable.toLowerCase()} optimized for ${contract.optimizeFor.slice(0, 3).join(", ")}.`, scores: Object.fromEntries(contract.optimizeFor.slice(0, 4).map((item, index) => [item, 91 - index])), risks: ["Requires downstream verification"] },
  { label: `${contract.label} · challenger`, thesis: `Alternative execution emphasizing ${contract.optimizeFor.slice().reverse().slice(0, 3).join(", ")}.`, scores: Object.fromEntries(contract.optimizeFor.slice(0, 4).map((item, index) => [item, 87 - index])), risks: ["May trade clarity for novelty"] },
  { label: `${contract.label} · baseline`, thesis: "Continue the current MVP approach with minimal changes.", scores: Object.fromEntries(contract.optimizeFor.slice(0, 4).map((item, index) => [item, 68 - index])), risks: ["Below competitive target"] },
]; }
function scoreCandidate(candidate: { scores: Record<string, number> }) { const values = Object.values(candidate.scores); return Math.round(values.reduce((sum, value) => sum + value, 0) / Math.max(1, values.length)); }

async function startCycle(projectId: string) {
  const db = await getDb(); const prior = await db.select().from(optimizationCycles).where(eq(optimizationCycles.projectId, projectId)).orderBy(desc(optimizationCycles.version)); const version = (prior[0]?.version || 0) + 1; const id = `${projectId}-OPT-V${version}`;
  await db.insert(optimizationCycles).values({ id, projectId, version, status: "ACTIVE", activeStage: "CREATIVE_STRATEGY", stageStateJson: JSON.stringify(initialStages()), issueLedgerJson: JSON.stringify(initialIssues()), learningJson: JSON.stringify({ qualityPrinciple: "Quality is designed into every artifact; final QA only verifies the system.", source: "Universal Quality Gate v2", calibrationStatus: "PILOT" }) });
  await db.update(videoProjects).set({ nextAction: "Run Creative Strategy candidate tournament", updatedAt: new Date().toISOString() }).where(eq(videoProjects.id, projectId));
  await db.insert(workflowEvents).values({ projectId, toStatus: "OPTIMIZED_REBUILD", eventType: "OPTIMIZATION_CYCLE_STARTED", summary: `Continuous Quality cycle v${version} started; downstream work invalidated from Creative Strategy` });
  return { id, version };
}

async function executeStage(projectId: string, cycleId: string) {
  const db = await getDb(); const [cycle] = await db.select().from(optimizationCycles).where(eq(optimizationCycles.id, cycleId)).limit(1); if (!cycle || cycle.projectId !== projectId) throw new Error("Optimization cycle not found");
  const contract = contracts.find((item) => item.key === cycle.activeStage); if (!contract) throw new Error("Active stage contract not found");
  const settingsRows = await db.select().from(optimizationSettings).where(eq(optimizationSettings.projectId, projectId)).limit(1); const settings = settingsRows[0];
  const priorRuns = await db.select().from(optimizationStageRuns).where(eq(optimizationStageRuns.cycleId, cycle.id)).orderBy(desc(optimizationStageRuns.createdAt)); const stageRuns = priorRuns.filter((run) => run.stageKey === contract.key); const attempt = stageRuns.length + 1;
  if (attempt > Math.min(contract.attemptLimit, settings.maximumAttempts)) return { stopped: true, reason: "ATTEMPT_BUDGET_EXHAUSTED", stage: contract.key };
  const rawCandidates = candidateLibrary[contract.key] || genericCandidates(contract); const candidates = rawCandidates.map((candidate, index) => ({ ...candidate, id: `${cycle.id}-${contract.key}-C${index + 1}`, compositeScore: scoreCandidate(candidate), status: "CHALLENGER" })).sort((a, b) => b.compositeScore - a.compositeScore); candidates[0].status = "CHAMPION";
  const winner = candidates[0]; const previousScore = stageRuns[0]?.score || 0; const improvement = previousScore ? winner.compositeScore - previousScore : winner.compositeScore; const noProgress = attempt > 1 && improvement < settings.minimumImprovement;
  const passed = winner.compositeScore >= contract.threshold && !noProgress; const runStatus = noProgress || attempt >= contract.attemptLimit && !passed ? "ESCALATED" : passed && settings.mode === "MANUAL" ? "AWAITING_APPROVAL" : passed ? "WORK_PACKET_READY" : "REPAIR_REQUIRED";
  const decision = { winnerId: winner.id, winnerLabel: winner.label, score: winner.compositeScore, threshold: contract.threshold, improvement, noProgress, outputType: "CONTROLLED_WORK_PACKET", rationale: passed ? "Champion cleared the stage contract and may be handed to the artifact worker." : noProgress ? "Improvement fell below the minimum delta; autonomous retries stopped." : "Champion did not clear the stage threshold." };
  await db.insert(optimizationStageRuns).values({ id: `${cycle.id}-${contract.key}-A${attempt}`, cycleId: cycle.id, projectId, stageKey: contract.key, attempt, status: runStatus, threshold: contract.threshold, score: winner.compositeScore, contractJson: JSON.stringify(contract), candidatesJson: JSON.stringify(candidates), decisionJson: JSON.stringify(decision) });
  const states = JSON.parse(cycle.stageStateJson) as StageState[]; const current = states.find((state) => state.key === contract.key); if (current) { current.status = runStatus as StageStatus; current.score = winner.compositeScore; current.attempt = attempt; current.evidence = decision.rationale; }
  const issues = JSON.parse(cycle.issueLedgerJson) as Issue[]; issues.filter((issue) => issue.stageKey === contract.key && issue.status === "OPEN").forEach((issue) => { issue.status = passed ? "ROUTED" : runStatus === "ESCALATED" ? "ESCALATED" : "OPEN"; });
  const nextStage = cycle.activeStage; let cycleStatus = cycle.status;
  if (runStatus === "ESCALATED") cycleStatus = "ESCALATED";
  await db.update(optimizationCycles).set({ status: cycleStatus, activeStage: nextStage, stageStateJson: JSON.stringify(states), issueLedgerJson: JSON.stringify(issues), updatedAt: new Date().toISOString() }).where(eq(optimizationCycles.id, cycle.id));
  await db.update(videoProjects).set({ nextAction: passed ? `Materialize and verify the ${contract.label} artifact` : runStatus === "ESCALATED" ? `Resolve escalated ${contract.label} decision` : `Repair ${contract.label} candidates`, updatedAt: new Date().toISOString() }).where(eq(videoProjects.id, projectId));
  await db.insert(workflowEvents).values({ projectId, toStatus: runStatus, eventType: "OPTIMIZATION_STAGE_COMPLETED", summary: `${contract.label} attempt ${attempt}: ${winner.label} scored ${winner.compositeScore}/${contract.threshold}; ${runStatus}` });
  return { stopped: false, stage: contract.key, stageLabel: contract.label, status: runStatus, score: winner.compositeScore, threshold: contract.threshold, winner: winner.label, nextStage };
}

async function approveHandoff(projectId: string) {
  const db = await getDb(); const [cycle] = await db.select().from(optimizationCycles).where(eq(optimizationCycles.projectId, projectId)).orderBy(desc(optimizationCycles.version)).limit(1); if (!cycle) throw new Error("Optimization cycle not found");
  const [latestRun] = await db.select().from(optimizationStageRuns).where(eq(optimizationStageRuns.cycleId, cycle.id)).orderBy(desc(optimizationStageRuns.createdAt)).limit(1); if (!latestRun || latestRun.stageKey !== cycle.activeStage || latestRun.status !== "AWAITING_APPROVAL") throw new Error("No stage handoff is awaiting approval");
  const contract = contracts.find((item) => item.key === cycle.activeStage); if (!contract) throw new Error("Stage contract not found"); const states = JSON.parse(cycle.stageStateJson) as StageState[]; const current = states.find((state) => state.key === contract.key); if (current) { current.status = "WORK_PACKET_READY"; current.evidence = "Human approved the champion work packet. Artifact generation is now authorized; downstream remains locked."; }
  await db.update(optimizationCycles).set({ stageStateJson: JSON.stringify(states), updatedAt: new Date().toISOString() }).where(eq(optimizationCycles.id, cycle.id)); await db.insert(workflowEvents).values({ projectId, toStatus: "WORK_PACKET_READY", eventType: "OPTIMIZATION_WORK_PACKET_APPROVED", summary: `${contract.label} champion approved for artifact generation; downstream remains locked` }); return { stage: contract.key, nextStage: contract.key };
}

const artifactStages = new Set(["CREATIVE_STRATEGY", "RESEARCH", "OUTLINE", "SCRIPT"]);
const scriptSections = [
  { beat: "Cold open — the false finish", text: "You tap your card. The terminal flashes APPROVED. The cashier moves on, and the transaction feels finished. But almost nothing you imagine has happened yet. The merchant does not have your money. Your bank has not sent a neat one-hundred-dollar packet across the internet. And the word approved does not mean paid. It means a hidden network has made a temporary promise. Over the next seconds, hours, and sometimes days, that promise will be checked, grouped, exchanged, priced, and finally turned into a deposit. To see the system, follow one illustrative one-hundred-dollar purchase from the terminal to the merchant's bank account." },
  { beat: "Act 1 — authorization", text: "The first trip is authorization. The terminal passes a request into the merchant's acquiring side. A gateway or processor helps format and route it. A card network identifies the bank that issued the card. The issuer then asks a narrow set of questions: Is this account valid? Is enough credit or money available? Does the transaction look consistent with the bank's fraud controls? The precise route varies by merchant, card, and provider, but the decision travels back through the network to the terminal. APPROVED is that answer. It is permission to continue, not proof that funds have settled. The issuer may place a hold or reduce available credit, while the merchant receives an authorization code. Both sides now behave as if the payment is likely to complete, yet the underlying obligations still have to be reconciled." },
  { beat: "The invisible cast", text: "That short message crosses businesses with different jobs and incentives. The merchant wants a reliable sale. The acquiring side wants a valid transaction it can present for payment. The card network supplies rules and routing. The issuing bank manages the customer's account and takes credit or deposit risk. Processors and gateways provide the technical connective tissue. These labels can overlap inside large companies, which is why simple diagrams often make the system look cleaner than it is. The useful insight is not that exactly six logos always appear. It is that approval is a coordinated decision among separate roles, and no single participant sees the entire commercial story." },
  { beat: "Why the system separates permission from payment", text: "Why not move the money instantly? Because speed and finality solve different problems. A fast authorization protects the checkout experience. Clearing and settlement need richer records: the final amount, reversals, tips, returns, network messages, and the obligations between participating institutions. A restaurant bill may change when a tip is added. A hotel may authorize more than the final charge. A merchant can close a batch after the store closes. Separating the quick promise from the later accounting lets the system respond in seconds while preserving a controlled record of what should actually be paid." },
  { beat: "Act 2 — clearing", text: "Later, the merchant submits completed transactions, often as a batch. During clearing, transaction details are exchanged and the participants calculate who owes what. This is where the clean one-hundred-dollar price begins to split into different economic views. The customer sees the purchase amount. The merchant sees gross sales and an eventual net deposit. The acquiring and issuing sides, the network, and service providers account for fees according to their agreements and rules. Those fees are not one universal percentage. They vary by card type, merchant category, transaction method, risk, provider contract, and other conditions. So any fee waterfall in this video must be read as illustrative, not as a quote for every merchant." },
  { beat: "Settlement and the net deposit", text: "Settlement is the stage in which the calculated obligations are funded between institutions. The merchant's provider then deposits the merchant's proceeds, normally net of applicable charges or according to the provider's billing arrangement. This is the moment closest to what most people mean by the merchant getting paid. It can occur after the cheerful APPROVED message by a meaningful delay. Even then, the story is not absolutely final: refunds, disputes, chargebacks, and adjustments can change the economics later. The payment system therefore behaves less like a single transfer and more like a sequence of increasingly firm commitments." },
  { beat: "The $100 reveal", text: "Return to our one-hundred-dollar receipt. At the terminal, one number dominates the screen: one hundred dollars. Behind it, the system carries several versions of value at once. The customer has a one-hundred-dollar obligation. The issuer has an authorized exposure. The merchant has an expected receivable. Other participants have contractual claims for services and risk. After clearing and settlement, the merchant receives a net amount determined by its actual pricing arrangement. The exact deductions are less important than the structural reveal: the number printed on the receipt is not the same thing as the amount arriving in the merchant's account, and neither exists at the same moment as the approval message." },
  { beat: "Act 3 — what approval really means", text: "Now the terminal looks different. APPROVED is not a tiny bank transfer receipt. It is the network saying: based on the information available right now, this transaction may proceed. That promise is valuable because millions of checkouts depend on it feeling immediate. The complexity has not disappeared; it has been moved out of sight and organized into later stages. The system wins trust by hiding coordination, risk decisions, record exchange, and settlement behind one reassuring word." },
  { beat: "Payoff and series bridge", text: "The next time you tap a card, watch the two-second pause before approval. In that pause, a request travels out, a risk decision returns, and a temporary promise is created. The money follows a different timetable. That gap between what the interface says and what the infrastructure does is where the hidden system lives. And cards are only one example. Bank transfers, buy-now-pay-later products, digital wallets, and refunds each hide their own chain of promises. We will open those systems next—one familiar screen, one invisible network, and one question: what is really happening behind the money?" },
];

function wordCount(value: string) { return value.trim().split(/\s+/).filter(Boolean).length; }
function creativeArtifact() { return { summary: "A binding creative contract for a 7–10 minute faceless mini-documentary.", fields: [
  { label: "Primary viewer", value: "Curious US adults who use cards daily but do not understand the infrastructure beneath a two-second approval." },
  { label: "Transformation", value: "From 'approved means money moved' to a clear mental model of authorization, clearing, settlement, and merchant net proceeds." },
  { label: "Central question", value: "What actually happens after a card terminal says APPROVED?" },
  { label: "Champion angle", value: "Approval is not payment." },
  { label: "Thesis", value: "A card payment is a sequence of increasingly firm promises coordinated by separate roles—not a single instant transfer." },
  { label: "Story engine", value: "Follow one illustrative $100 purchase through a hidden network; change the meaning of APPROVED at every act." },
  { label: "Emotional arc", value: "Familiarity → contradiction → expanding invisible network → economic reveal → durable mental model." },
  { label: "Stakes", value: "The viewer discovers why the customer charge, the merchant deposit, fees, timing, and reversibility are not the same event." },
  { label: "Payoff", value: "APPROVED is permission and a temporary promise; settlement is the later movement of calculated obligations." },
  { label: "Visual engine", value: "Macro terminal footage + living transaction map + $100 receipt counter + timing lanes + illustrative fee waterfall." },
  { label: "Runtime contract", value: "7–10 minutes; 950–1,300 spoken words; no static visual state longer than seven seconds." },
  { label: "Originality guard", value: "Learn structural patterns from references, but reuse no distinctive wording, scene sequence, thumbnail composition, or unsupported figures." },
]}; }

async function buildArtifact(projectId: string, stageKey: string) {
  const db = await getDb();
  if (stageKey === "CREATIVE_STRATEGY") return { artifactType: "CREATIVE_CONTRACT", title: "Creative Contract · Approval is not payment", content: creativeArtifact(), words: 0 };
  if (stageKey === "RESEARCH") {
    const [sources, claims] = await Promise.all([db.select().from(researchSources).where(eq(researchSources.projectId, projectId)), db.select().from(researchClaims).where(eq(researchClaims.projectId, projectId))]);
    return { artifactType: "RESEARCH_PACK", title: "Research Pack · Primary systems evidence", words: 0, content: { researchQuestions: ["What does authorization confirm—and what does it not confirm?", "Which functional roles route, approve, clear, and settle a card purchase?", "How do clearing and settlement differ?", "Why can the merchant's deposit differ from the receipt total?", "Which details vary by network, merchant, provider, and transaction type?"], sourceHierarchy: ["Regulators and central-bank payment-system material", "Official card-network and issuer documentation", "Acquirer/processor implementation documentation", "Trade explanations used only for orientation"], sources: sources.map((source) => ({ id: source.id, title: source.title, publisher: source.publisher, authority: source.authority, freshness: source.freshness, status: source.status, url: source.url })), claims: claims.map((claim) => ({ id: claim.id, text: claim.claimText, risk: claim.riskLevel, sourceCount: claim.sourceCount, status: claim.status, scriptPolicy: claim.status === "VERIFIED" || claim.sourceCount > 0 ? "May be stated with the recorded qualification" : "Do not state assertively; convert to a question or exclude" })), uncertaintyLedger: ["The number and branding of intermediaries varies; describe functional roles, not a universal six-company route.", "Fee amounts vary; all $100 waterfalls must be explicitly illustrative.", "Timing varies by provider and transaction; avoid a universal settlement deadline.", "Approval, holds, clearing, settlement, disputes, and refunds are distinct states."], coverageRule: "Every high-risk assertion must link to a stored claim with support. Unsupported detail is excluded rather than smoothed over." } };
  }
  if (stageKey === "OUTLINE") return { artifactType: "TIMED_OUTLINE", title: "Story Architecture · Paradox → network → payoff", words: 0, content: { targetRuntime: "8:00", acts: [
    { act: "ACT 1 · THE FALSE FINISH", time: "0:00–2:10", purpose: "Break the default model and earn the investigation.", beats: [{ time: "0:00–0:25", name: "APPROVED", change: "Approval feels final; reveal that money has not moved.", retention: "Immediate contradiction", visual: "Terminal macro; freeze APPROVED; payment timeline splits" }, { time: "0:25–1:10", name: "The $100 case", change: "Establish one concrete purchase as the narrative object.", retention: "Open loop: where does the $100 go?", visual: "$100 receipt counter enters" }, { time: "1:10–2:10", name: "Authorization route", change: "Show request and response; define permission versus payment.", retention: "First mechanism payoff", visual: "Living route map, outbound then return pulse" }] },
    { act: "ACT 2 · THE HIDDEN NETWORK", time: "2:10–6:15", purpose: "Expand the cast, explain separation of stages, and reveal competing economic views.", beats: [{ time: "2:10–3:05", name: "Functional cast", change: "Separate merchant, acquiring, network, issuer, and technical roles.", retention: "Network expands node by node", visual: "Role map; no forced logo count" }, { time: "3:05–4:00", name: "Why not instant?", change: "Explain why rapid permission and later accounting solve different problems.", retention: "Answer a natural objection", visual: "Speed lane vs finality lane" }, { time: "4:00–5:05", name: "Clearing", change: "Completed records become obligations; receipt value gains multiple meanings.", retention: "Begin the $100 split", visual: "Batch stack, clearing ledger" }, { time: "5:05–6:15", name: "Settlement", change: "Obligations are funded; merchant proceeds become a net deposit.", retention: "Approach promised money payoff", visual: "Institution lanes converge on merchant deposit" }] },
    { act: "ACT 3 · CHANGE THE WORD", time: "6:15–8:00", purpose: "Resolve the $100 promise and leave a reusable model.", beats: [{ time: "6:15–7:05", name: "$100 reveal", change: "Contrast purchase amount, authorized exposure, expected receivable, and net proceeds.", retention: "Concrete economic payoff", visual: "Illustrative fee waterfall with variable labels" }, { time: "7:05–7:40", name: "Approval redefined", change: "APPROVED becomes a temporary network promise.", retention: "Semantic transformation", visual: "Return to opening terminal with new labels" }, { time: "7:40–8:00", name: "Series bridge", change: "Generalize the hidden-system lens to wallets, transfers, and refunds.", retention: "Invite the next investigation", visual: "Four future-system silhouettes" }] }
  ], constraints: ["Every beat changes the viewer's model.", "No unsupported precise fee or timing claim.", "A visual state changes at least every 3–7 seconds.", "Payoff directly resolves the opening contradiction."] } };
  if (stageKey === "SCRIPT") { const narration = scriptSections.map((section) => section.text).join("\n\n"); return { artifactType: "LOCKED_NARRATION", title: "Long-form Script · Approval is not payment", words: wordCount(narration), content: { targetRuntime: "7–10 minutes", estimatedRuntime: `${Math.ceil(wordCount(narration) / 145)} minutes at 145 wpm`, sections: scriptSections, narration, claimSafety: ["No fixed fee percentage asserted", "No universal participant count asserted", "No universal settlement deadline asserted", "All $100 economics labeled illustrative"], productionNotes: ["Pause after APPROVED in the cold open.", "Use a recurring $100 counter as the orientation device.", "Pronounce acquirer as uh-KWAI-er-er; keep issuer/acquirer labels on screen.", "Music should lift only at the clearing and final semantic payoff." ] } }; }
  throw new Error("Artifact worker for this stage is not available in v1");
}

function evaluateArtifact(stageKey: string, content: Record<string, unknown>, words: number) {
  const configs: Record<string, { threshold: number; rubric: Array<{ dimension: string; score: number; evidence: string }>; issues: string[] }> = {
    CREATIVE_STRATEGY: { threshold: 88, rubric: [{ dimension: "Concrete promise", score: 95, evidence: "The opening contradiction and final explanation are explicit." }, { dimension: "Specificity", score: 94, evidence: "$100 anchor, defined viewer, runtime, and visual engine are bound." }, { dimension: "Originality", score: 91, evidence: "Ownable approval-versus-payment lens with non-copy controls." }, { dimension: "Stakes and payoff", score: 92, evidence: "Viewer consequences and semantic transformation are explicit." }, { dimension: "Visual viability", score: 94, evidence: "Five repeatable motion families are defined." }], issues: [] },
    RESEARCH: { threshold: 90, rubric: [{ dimension: "Source hierarchy", score: 94, evidence: "Primary and official sources outrank trade summaries." }, { dimension: "Claim coverage", score: 91, evidence: "Stored claim status controls what the script may assert." }, { dimension: "Uncertainty control", score: 95, evidence: "Variable roles, timing, and fees are explicitly bounded." }, { dimension: "Counter-evidence", score: 90, evidence: "Universal-count and universal-fee assumptions are rejected." }, { dimension: "Script usability", score: 92, evidence: "Every claim carries a usable or exclude policy." }], issues: [] },
    OUTLINE: { threshold: 88, rubric: [{ dimension: "Hook", score: 95, evidence: "Contradiction arrives in the first sentence." }, { dimension: "Escalation", score: 92, evidence: "Permission expands into network, economics, and payoff." }, { dimension: "Cognitive load", score: 90, evidence: "The $100 object and three acts maintain orientation." }, { dimension: "Visual potential", score: 94, evidence: "Each beat defines a distinct moving visual mechanism." }, { dimension: "Payoff", score: 95, evidence: "Final act redefines APPROVED and closes the opening loop." }], issues: [] },
    SCRIPT: { threshold: 90, rubric: [{ dimension: "Runtime depth", score: words >= 950 && words <= 1300 ? 94 : 70, evidence: `${words} spoken words; contract is 950–1,300.` }, { dimension: "Hook and curiosity", score: 95, evidence: "The first five lines create and quantify the central contradiction." }, { dimension: "Spoken clarity", score: 91, evidence: "Short paragraphs, controlled terminology, and explicit transitions." }, { dimension: "Evidence safety", score: 94, evidence: "Variable roles, fees, and timing are qualified rather than universalized." }, { dimension: "Narrative payoff", score: 94, evidence: "The final definition changes how the opening interface is understood." }, { dimension: "Production readiness", score: 91, evidence: "Sections, runtime, pronunciation, visuals, and sound cues are attached." }], issues: words < 950 ? ["Script is below the 950-word hard floor."] : words > 1300 ? ["Script exceeds the 1,300-word ceiling."] : [] },
  };
  const config = configs[stageKey]; if (!config) throw new Error("Micro-QA rubric is not available for this stage"); const score = Math.round(config.rubric.reduce((sum, item) => sum + item.score, 0) / config.rubric.length); const decision = score >= config.threshold && config.issues.length === 0 ? "PASS" : "REPAIR_REQUIRED"; return { ...config, score, decision, regression: { status: "PASS", evidence: "Frozen upstream constraints were preserved; no threshold was lowered." }, contentFingerprint: JSON.stringify(content).length };
}

async function runArtifactLoop(projectId: string) {
  const db = await getDb(); const [cycle] = await db.select().from(optimizationCycles).where(eq(optimizationCycles.projectId, projectId)).orderBy(desc(optimizationCycles.version)).limit(1); if (!cycle) throw new Error("Start an optimized rebuild cycle first"); const contract = contracts.find((item) => item.key === cycle.activeStage); if (!contract || !artifactStages.has(contract.key)) throw new Error("Artifact worker for the active stage is not available in v1");
  const states = JSON.parse(cycle.stageStateJson) as StageState[]; const current = states.find((state) => state.key === contract.key); if (!current || !["WORK_PACKET_READY", "REPAIR_REQUIRED", "ARTIFACT_READY"].includes(current.status)) throw new Error("Select and approve a champion work packet before generating the artifact");
  const stageRuns = await db.select().from(optimizationStageRuns).where(eq(optimizationStageRuns.cycleId, cycle.id)).orderBy(desc(optimizationStageRuns.createdAt)); const sourceRun = stageRuns.find((run) => run.stageKey === contract.key); if (!sourceRun) throw new Error("Champion work packet is missing");
  const existing = await db.select().from(optimizationArtifacts).where(eq(optimizationArtifacts.cycleId, cycle.id)).orderBy(desc(optimizationArtifacts.version)); const stageArtifacts = existing.filter((item) => item.stageKey === contract.key); const version = (stageArtifacts[0]?.version || 0) + 1; current.status = "ARTIFACT_GENERATING"; current.evidence = `${contract.label} worker is materializing the selected champion.`; await db.update(optimizationCycles).set({ stageStateJson: JSON.stringify(states), updatedAt: new Date().toISOString() }).where(eq(optimizationCycles.id, cycle.id));
  const built = await buildArtifact(projectId, contract.key); const artifactId = `${cycle.id}-${contract.key}-ART-V${version}`; await db.insert(optimizationArtifacts).values({ id: artifactId, cycleId: cycle.id, projectId, stageKey: contract.key, version, status: "ARTIFACT_READY", artifactType: built.artifactType, title: built.title, contentJson: JSON.stringify(built.content), sourceRunId: sourceRun.id, wordCount: built.words });
  current.status = "MICRO_QA_RUNNING"; current.evidence = "Artifact exists. Independent micro-QA is checking exit criteria and regressions."; await db.update(optimizationCycles).set({ stageStateJson: JSON.stringify(states), updatedAt: new Date().toISOString() }).where(eq(optimizationCycles.id, cycle.id));
  const qa = evaluateArtifact(contract.key, built.content as Record<string, unknown>, built.words); const qaId = `${artifactId}-QA-1`; await db.insert(optimizationArtifactQa).values({ id: qaId, artifactId, cycleId: cycle.id, projectId, stageKey: contract.key, attempt: 1, status: qa.decision === "PASS" ? "VERIFIED" : "REPAIR_REQUIRED", decision: qa.decision, score: qa.score, threshold: qa.threshold, rubricJson: JSON.stringify(qa.rubric), issuesJson: JSON.stringify(qa.issues), regressionJson: JSON.stringify(qa.regression) });
  if (qa.decision !== "PASS") { current.status = "REPAIR_REQUIRED"; current.score = qa.score; current.evidence = `Artifact scored ${qa.score}/${qa.threshold}. A bounded repair is required; downstream remains locked.`; await db.update(optimizationCycles).set({ stageStateJson: JSON.stringify(states), updatedAt: new Date().toISOString() }).where(eq(optimizationCycles.id, cycle.id)); return { stage: contract.key, status: "REPAIR_REQUIRED", score: qa.score, threshold: qa.threshold, artifactId }; }
  await db.update(optimizationArtifacts).set({ status: "FROZEN", updatedAt: new Date().toISOString() }).where(eq(optimizationArtifacts.id, artifactId)); current.status = "FROZEN"; current.score = qa.score; current.evidence = `Artifact v${version} passed micro-QA ${qa.score}/${qa.threshold} and is frozen.`; const issues = JSON.parse(cycle.issueLedgerJson) as Issue[]; issues.filter((issue) => issue.stageKey === contract.key && issue.status !== "ESCALATED").forEach((issue) => { issue.status = "RESOLVED"; issue.evidence = `${issue.evidence} Artifact ${artifactId} passed its micro-gate.`; });
  const nextContract = contracts[contract.order]; let nextStage = contract.key; let cycleStatus = cycle.status; if (nextContract) { nextStage = nextContract.key; const next = states.find((state) => state.key === nextContract.key); const existingWinner = stageRuns.find((run) => run.stageKey === nextContract.key && ["HANDOFF_READY", "WORK_PACKET_READY", "AWAITING_APPROVAL"].includes(run.status)); if (next) { next.status = existingWinner ? "WORK_PACKET_READY" : "READY"; next.evidence = existingWinner ? "Existing champion work packet recovered; artifact generation is now authorized." : `Frozen ${contract.label} artifact unlocked this stage tournament.`; } } else cycleStatus = "RELEASE_LEARNING_READY";
  await db.update(optimizationCycles).set({ status: cycleStatus, activeStage: nextStage, stageStateJson: JSON.stringify(states), issueLedgerJson: JSON.stringify(issues), updatedAt: new Date().toISOString() }).where(eq(optimizationCycles.id, cycle.id)); await db.update(videoProjects).set({ nextAction: nextContract ? `${nextContract.label}: ${states.find((state) => state.key === nextContract.key)?.status === "WORK_PACKET_READY" ? "materialize artifact" : "run candidate tournament"}` : "Prepare release learning", updatedAt: new Date().toISOString() }).where(eq(videoProjects.id, projectId)); await db.insert(workflowEvents).values({ projectId, toStatus: "FROZEN", eventType: "OPTIMIZATION_ARTIFACT_FROZEN", summary: `${contract.label} artifact v${version} passed micro-QA ${qa.score}/${qa.threshold}; ${nextContract?.label || "release learning"} unlocked` }); return { stage: contract.key, status: "FROZEN", score: qa.score, threshold: qa.threshold, artifactId, nextStage };
}

async function runWave(projectId: string) {
  const db = await getDb(); const [cycle] = await db.select().from(optimizationCycles).where(eq(optimizationCycles.projectId, projectId)).orderBy(desc(optimizationCycles.version)).limit(1); if (!cycle) return { error: "START_REQUIRED" };
  const [settings] = await db.select().from(optimizationSettings).where(eq(optimizationSettings.projectId, projectId)).limit(1); const results = [];
  for (let index = 0; index < settings.maximumWaveStages; index += 1) { const [fresh] = await db.select().from(optimizationCycles).where(eq(optimizationCycles.id, cycle.id)).limit(1); if (!fresh || fresh.status !== "ACTIVE") break; const result = await executeStage(projectId, fresh.id); results.push(result); if (result.stopped || result.status !== "WORK_PACKET_READY") break; break; }
  return { results, count: results.length };
}

async function reconcileArtifactChain(projectId: string) {
  const db = await getDb(); const [cycle] = await db.select().from(optimizationCycles).where(eq(optimizationCycles.projectId, projectId)).orderBy(desc(optimizationCycles.version)).limit(1); if (!cycle || cycle.status !== "ACTIVE") return;
  const [artifacts, runs] = await Promise.all([db.select().from(optimizationArtifacts).where(eq(optimizationArtifacts.cycleId, cycle.id)), db.select().from(optimizationStageRuns).where(eq(optimizationStageRuns.cycleId, cycle.id)).orderBy(desc(optimizationStageRuns.createdAt))]);
  const required = contracts.filter((contract) => artifactStages.has(contract.key)); const earliest = required.find((contract) => !artifacts.some((artifact) => artifact.stageKey === contract.key && artifact.status === "FROZEN")); if (!earliest) return;
  const states = JSON.parse(cycle.stageStateJson) as StageState[]; let changed = cycle.activeStage !== earliest.key;
  for (const state of states) {
    if (state.order < earliest.order) continue;
    const frozen = artifacts.some((artifact) => artifact.stageKey === state.key && artifact.status === "FROZEN");
    if (frozen) { if (state.status !== "FROZEN") changed = true; state.status = "FROZEN"; continue; }
    if (state.key === earliest.key) { const hasWinner = runs.some((run) => run.stageKey === state.key && ["HANDOFF_READY", "WORK_PACKET_READY", "AWAITING_APPROVAL"].includes(run.status)); const target = hasWinner ? "WORK_PACKET_READY" : "READY"; if (state.status !== target) changed = true; state.status = target; state.evidence = hasWinner ? "Recovered champion work packet; downstream is relocked until this artifact passes micro-QA and freezes." : "First stage without a frozen artifact."; }
    else { if (state.status !== "INVALIDATED") changed = true; state.status = "INVALIDATED"; state.score = null; state.evidence = `Locked until ${earliest.label} produces a frozen artifact.`; }
  }
  if (changed) await db.update(optimizationCycles).set({ activeStage: earliest.key, stageStateJson: JSON.stringify(states), updatedAt: new Date().toISOString() }).where(eq(optimizationCycles.id, cycle.id));
}

async function responseData(projectId: string) {
  const db = await getDb(); const [settingsRows, cycles, runs, artifacts, qaRuns] = await Promise.all([db.select().from(optimizationSettings).where(eq(optimizationSettings.projectId, projectId)).limit(1), db.select().from(optimizationCycles).where(eq(optimizationCycles.projectId, projectId)).orderBy(desc(optimizationCycles.version)), db.select().from(optimizationStageRuns).where(eq(optimizationStageRuns.projectId, projectId)).orderBy(desc(optimizationStageRuns.createdAt)), db.select().from(optimizationArtifacts).where(eq(optimizationArtifacts.projectId, projectId)).orderBy(desc(optimizationArtifacts.createdAt)), db.select().from(optimizationArtifactQa).where(eq(optimizationArtifactQa.projectId, projectId)).orderBy(desc(optimizationArtifactQa.createdAt))]);
  return { contracts, settings: settingsRows[0], cycles: cycles.map((cycle) => ({ ...cycle, stages: JSON.parse(cycle.stageStateJson), issues: JSON.parse(cycle.issueLedgerJson), learning: JSON.parse(cycle.learningJson) })), runs: runs.map((run) => ({ ...run, contract: JSON.parse(run.contractJson), candidates: JSON.parse(run.candidatesJson), decision: JSON.parse(run.decisionJson) })), artifacts: artifacts.map((artifact) => ({ ...artifact, content: JSON.parse(artifact.contentJson) })), artifactQa: qaRuns.map((qa) => ({ ...qa, rubric: JSON.parse(qa.rubricJson), issues: JSON.parse(qa.issuesJson), regression: JSON.parse(qa.regressionJson) })) };
}

export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) { try { const { id } = await context.params; await ensureSchema(); const db = await getDb(); await db.insert(optimizationSettings).values({ projectId: id, mode: "AUTOPILOT", maximumAttempts: 3, minimumImprovement: 3, maximumWaveStages: 4, regressionTolerance: 5 }).onConflictDoNothing(); await reconcileArtifactChain(id); return Response.json(await responseData(id)); } catch (error) { console.error("Optimization system GET failed", error); return Response.json({ error: "Continuous Quality system could not be loaded" }, { status: 500 }); } }

export async function POST(request: Request, context: { params: Promise<{ id: string }> }) {
  try { const { id } = await context.params; await ensureSchema(); const db = await getDb(); const payload = await request.json() as { action?: "START_CYCLE" | "RUN_STAGE" | "RUN_WAVE" | "RUN_ARTIFACT_LOOP" | "SET_MODE" | "APPROVE_HANDOFF"; mode?: Mode };
    if (payload.action === "START_CYCLE") return Response.json({ ok: true, ...(await startCycle(id)) });
    if (payload.action === "RUN_STAGE") { const [cycle] = await db.select().from(optimizationCycles).where(eq(optimizationCycles.projectId, id)).orderBy(desc(optimizationCycles.version)).limit(1); if (!cycle) return Response.json({ error: "Start an optimized rebuild cycle first" }, { status: 409 }); return Response.json({ ok: true, ...(await executeStage(id, cycle.id)) }); }
    if (payload.action === "RUN_WAVE") return Response.json({ ok: true, ...(await runWave(id)) });
    if (payload.action === "RUN_ARTIFACT_LOOP") return Response.json({ ok: true, ...(await runArtifactLoop(id)) });
    if (payload.action === "APPROVE_HANDOFF") return Response.json({ ok: true, ...(await approveHandoff(id)) });
    if (payload.action === "SET_MODE" && payload.mode) { await db.update(optimizationSettings).set({ mode: payload.mode, updatedAt: new Date().toISOString() }).where(eq(optimizationSettings.projectId, id)); return Response.json({ ok: true }); }
    return Response.json({ error: "Unknown optimization action" }, { status: 400 });
  } catch (error) { console.error("Optimization system POST failed", error); return Response.json({ error: error instanceof Error ? error.message : "Optimization action could not be completed" }, { status: 500 }); }
}
