import { desc, eq } from "drizzle-orm";
import { getDb } from "../../../../../db";
import { optimizationCycles, optimizationSettings, optimizationStageRuns, videoProjects, workflowEvents } from "../../../../../db/schema";

type RuntimeD1 = { prepare(sql: string): { run(): Promise<unknown> } };
type RuntimeEnv = { DB?: RuntimeD1 };
type Mode = "AUTOPILOT" | "EXCEPTIONS" | "MANUAL";
type StageStatus = "PASSED_REUSED" | "READY" | "ACTIVE" | "INVALIDATED" | "HANDOFF_READY" | "AWAITING_APPROVAL" | "REPAIR_REQUIRED" | "ESCALATED" | "BLOCKED";
type StageState = { key: string; order: number; status: StageStatus; score: number | null; attempt: number; evidence: string };
type Issue = { id: string; severity: "P0" | "P1" | "P2"; artifact: string; issue: string; evidence: string; rootCause: string; owner: string; acceptance: string; status: "OPEN" | "ROUTED" | "RESOLVED" | "ESCALATED"; stageKey: string };

type Contract = {
  key: string; order: number; label: string; objective: string; optimizeFor: string[]; inputs: string[]; deliverable: string;
  candidatePolicy: string; evaluators: string[]; hardGates: string[]; threshold: number; attemptLimit: number; invalidates: string[];
};

const contracts: Contract[] = [
  { key: "CHANNEL_THESIS", order: 1, label: "Channel thesis", objective: "Prove a durable channel territory before producing individual videos.", optimizeFor: ["Demand durability", "Ad economics", "Series depth", "Faceless feasibility"], inputs: ["US market", "English language", "Ads-first revenue model"], deliverable: "Versioned channel thesis and 50-topic capacity test", candidatePolicy: "Compare 3–5 niche territories", evaluators: ["Market strategist", "Monetization critic", "Production feasibility critic"], hardGates: ["50+ viable topics", "No identity dependency", "Advertiser-compatible territory"], threshold: 85, attemptLimit: 2, invalidates: ["AUDIENCE_MODEL", "TOPIC_DISCOVERY"] },
  { key: "AUDIENCE_MODEL", order: 2, label: "Audience intelligence", objective: "Define the viewer transformation and the context in which the viewer chooses to watch.", optimizeFor: ["Specificity", "Unmet questions", "Knowledge gap", "Emotional relevance"], inputs: ["Channel thesis", "Audience evidence"], deliverable: "Viewer model, jobs-to-be-done and transformation statement", candidatePolicy: "Compare 3 audience segments", evaluators: ["Audience advocate", "Behavior critic", "Clarity judge"], hardGates: ["One primary viewer", "Explicit before/after transformation"], threshold: 85, attemptLimit: 3, invalidates: ["TOPIC_DISCOVERY", "CREATIVE_STRATEGY"] },
  { key: "TOPIC_DISCOVERY", order: 3, label: "Topic discovery", objective: "Select a topic with demand, differentiation and production leverage.", optimizeFor: ["Demand", "Novelty", "Channel fit", "Series potential", "Feasibility"], inputs: ["Channel thesis", "Audience model", "Reference signals"], deliverable: "Ranked topic tournament with champion and backup", candidatePolicy: "Generate 20–30 topics, shortlist 5, retain 1 champion", evaluators: ["Demand analyst", "Competition critic", "Series strategist"], hardGates: ["Evidence of demand", "Distinct angle exists", "Can become a series"], threshold: 86, attemptLimit: 3, invalidates: ["CREATIVE_STRATEGY", "RESEARCH"] },
  { key: "CREATIVE_STRATEGY", order: 4, label: "Creative strategy", objective: "Turn a good topic into a compelling, ownable viewer experience.", optimizeFor: ["Promise", "Thesis", "Stakes", "Payoff", "Visual opportunity"], inputs: ["Winning topic", "Audience transformation", "Reference patterns"], deliverable: "Creative contract with champion angle, emotional arc and payoff", candidatePolicy: "Tournament 4 differentiated angles", evaluators: ["Creative director", "Audience advocate", "Originality guard", "Adversarial critic"], hardGates: ["Promise is concrete", "Angle differs from references", "Visual engine is viable"], threshold: 88, attemptLimit: 3, invalidates: ["RESEARCH", "OUTLINE"] },
  { key: "RESEARCH", order: 5, label: "Research & evidence", objective: "Build a claim-safe, insight-rich evidence pack before scripting.", optimizeFor: ["Authority", "Coverage", "Freshness", "Counter-evidence", "Concrete examples"], inputs: ["Creative contract", "Research questions"], deliverable: "Claim map, source hierarchy and uncertainty ledger", candidatePolicy: "Compare primary-source packs and competing explanations", evaluators: ["Evidence auditor", "Skeptical researcher", "Fact verifier"], hardGates: ["Every P0 claim sourced", "Fact/inference/opinion separated", "Contradictions resolved"], threshold: 90, attemptLimit: 3, invalidates: ["OUTLINE", "SCRIPT"] },
  { key: "OUTLINE", order: 6, label: "Story architecture", objective: "Choose the narrative structure with the best clarity, escalation and retention potential.", optimizeFor: ["Hook", "Escalation", "Cognitive load", "Visual potential", "Payoff"], inputs: ["Creative contract", "Verified claim map"], deliverable: "Timed 3-act outline and beat map", candidatePolicy: "Compare 3 narrative architectures", evaluators: ["Story editor", "Retention critic", "Visual storyteller"], hardGates: ["Every beat changes viewer understanding", "Payoff resolves the promise"], threshold: 88, attemptLimit: 3, invalidates: ["SCRIPT", "VISUAL_LANGUAGE"] },
  { key: "SCRIPT", order: 7, label: "Script development", objective: "Create a natural, accurate and competitive spoken narrative.", optimizeFor: ["Depth", "Clarity", "Natural speech", "Curiosity", "Runtime", "Originality"], inputs: ["Winning outline", "Claim map", "Voice profile"], deliverable: "950–1,300 word locked narration with claim links", candidatePolicy: "5–10 hooks, 3 openings, 2 full-script challengers", evaluators: ["Hook critic", "Story critic", "Evidence critic", "Spoken-language critic"], hardGates: ["5–10 minute target", "No unsupported claims", "No redundant section"], threshold: 90, attemptLimit: 3, invalidates: ["VISUAL_LANGUAGE", "STORYBOARD", "VOICE_SOUND"] },
  { key: "VISUAL_LANGUAGE", order: 8, label: "Visual language", objective: "Design an ownable channel-level visual system before sourcing scenes.", optimizeFor: ["Brand distinction", "Readability", "Motion grammar", "Format variety"], inputs: ["Script", "Channel brand"], deliverable: "Color, type, diagram, chart, map, motion and transition system", candidatePolicy: "Compare 3 visual directions", evaluators: ["Art director", "Motion director", "Mobile readability critic"], hardGates: ["1080p system", "Mobile-safe labels", "Repeatable channel grammar"], threshold: 88, attemptLimit: 3, invalidates: ["STORYBOARD", "ASSET_TOURNAMENT"] },
  { key: "STORYBOARD", order: 9, label: "Storyboard & visual beats", objective: "Translate every narrative beat into a varied, purposeful audiovisual plan.", optimizeFor: ["Semantic fit", "Visual density", "Variety", "Continuity", "Pacing"], inputs: ["Locked script", "Visual language"], deliverable: "35–45 visual beats with movement and transitions", candidatePolicy: "2–3 treatments for every high-impact beat", evaluators: ["Storyboard critic", "Retention editor", "Cognitive-load critic"], hardGates: ["No visual state >7s", "At least 5 visual families", "No unexplained repetition"], threshold: 90, attemptLimit: 3, invalidates: ["ASSET_TOURNAMENT", "VOICE_SOUND", "EDIT_COMPOSE"] },
  { key: "ASSET_TOURNAMENT", order: 10, label: "Asset tournament", objective: "Select the best legal, high-fidelity asset for every visual beat.", optimizeFor: ["Semantic fit", "Fidelity", "Originality", "Motion potential", "Rights", "Cost"], inputs: ["Storyboard", "Source policy", "Budget"], deliverable: "Approved asset manifest with provenance and alternates", candidatePolicy: "3–5 candidates for every P0 visual beat", evaluators: ["Visual matcher", "Quality critic", "Rights guard"], hardGates: ["Commercial rights verified", "Source fidelity adequate", "No duplicate-heavy sequence"], threshold: 90, attemptLimit: 3, invalidates: ["EDIT_COMPOSE"] },
  { key: "VOICE_SOUND", order: 11, label: "Voice & sound design", objective: "Build narration and a designed soundscape that supports the emotional arc.", optimizeFor: ["Natural voice", "Pronunciation", "Music arc", "Ambience", "SFX", "Mix"], inputs: ["Locked script", "Storyboard timing"], deliverable: "Approved narration, music cue sheet, SFX plan and mix targets", candidatePolicy: "2–3 takes for critical lines; 3 music directions", evaluators: ["Voice director", "Sound designer", "Mix critic"], hardGates: ["No clipping", "Music license verified", "Measured loudness plan"], threshold: 90, attemptLimit: 3, invalidates: ["EDIT_COMPOSE"] },
  { key: "EDIT_COMPOSE", order: 12, label: "Edit & composition", objective: "Assemble a coherent, high-fidelity master optimized for viewer attention.", optimizeFor: ["Synchronization", "Rhythm", "Continuity", "Pattern interrupts", "Fidelity"], inputs: ["Approved assets", "Narration", "Soundscape", "Storyboard"], deliverable: "1080p release candidate with retention-risk map", candidatePolicy: "Champion edit plus one pacing challenger", evaluators: ["Film editor", "Retention critic", "Audiovisual QA"], hardGates: ["1080p master", "Full playback pass", "No P0 audiovisual defect"], threshold: 90, attemptLimit: 3, invalidates: ["PACKAGING", "FINAL_QA"] },
  { key: "PACKAGING", order: 13, label: "Packaging tournament", objective: "Create an accurate, differentiated click promise for the finished video.", optimizeFor: ["Curiosity", "Clarity", "Mobile readability", "Differentiation", "Promise alignment"], inputs: ["Approved master", "Audience model", "Reference environment"], deliverable: "3 test-ready title-thumbnail combinations", candidatePolicy: "5–10 titles and 3 thumbnail concepts", evaluators: ["Packaging strategist", "Audience critic", "Promise verifier"], hardGates: ["No promise mismatch", "Mobile legibility", "No cloning"], threshold: 90, attemptLimit: 3, invalidates: ["FINAL_QA"] },
  { key: "FINAL_QA", order: 14, label: "Final QA & release", objective: "Verify the complete system without using late-stage QA to compensate for weak construction.", optimizeFor: ["Perceived quality", "Technical integrity", "Rights", "Policy", "Accessibility"], inputs: ["Release candidate", "Package variants", "Audit trails"], deliverable: "Release decision and immutable publishing package", candidatePolicy: "One champion RC; challengers only if material improvement is plausible", evaluators: ["Universal Quality Gate", "Deep media analyzer", "Release manager"], hardGates: ["No P0/P1 issues", "Composite ≥85", "Competitive parity ≥75"], threshold: 90, attemptLimit: 2, invalidates: ["RELEASE_LEARNING"] },
  { key: "RELEASE_LEARNING", order: 15, label: "Release & learning", objective: "Convert real viewer behavior into calibrated improvements for the next video.", optimizeFor: ["CTR by source", "Retention", "Satisfaction", "Session continuation", "Learning value"], inputs: ["YouTube analytics", "Comments", "Experiment results"], deliverable: "Post-release learning packet and updated benchmarks", candidatePolicy: "Compare hypotheses, not cosmetic changes", evaluators: ["Analytics agent", "Audience researcher", "Calibration judge"], hardGates: ["No metric without context", "Learning linked to next decision"], threshold: 85, attemptLimit: 2, invalidates: [] },
];

const candidateLibrary: Record<string, Array<{ label: string; thesis: string; scores: Record<string, number>; risks: string[] }>> = {
  CREATIVE_STRATEGY: [
    { label: "Approval is not payment", thesis: "Open on the approved terminal, then reveal why no money has moved and follow the delayed $100.", scores: { Promise: 94, Originality: 92, Stakes: 88, Visuals: 94 }, risks: ["Requires settlement timing evidence"] },
    { label: "One tap, six companies", thesis: "Treat the transaction network as a cast of six invisible participants competing for a piece of the sale.", scores: { Promise: 88, Originality: 86, Stakes: 84, Visuals: 91 }, risks: ["Can become list-like without a strong payoff"] },
    { label: "Where the $100 goes", thesis: "Anchor the story in one receipt and trace every fee, promise and eventual deposit.", scores: { Promise: 91, Originality: 88, Stakes: 92, Visuals: 90 }, risks: ["Fee figures require careful qualification"] },
    { label: "Generic swipe explainer", thesis: "Explain authorization, clearing and settlement in sequence.", scores: { Promise: 70, Originality: 58, Stakes: 63, Visuals: 72 }, risks: ["Below competitor differentiation"] },
  ],
  RESEARCH: [
    { label: "Primary systems pack", thesis: "Lead with Federal Reserve, CFPB and card-network documentation; use trade sources only for implementation detail.", scores: { Authority: 95, Coverage: 89, Freshness: 87, Counterevidence: 88 }, risks: ["Network rules can be technical"] },
    { label: "Merchant economics pack", thesis: "Lead with acquiring, interchange and merchant-cost evidence, anchored to an illustrative $100 sale.", scores: { Authority: 86, Coverage: 92, Freshness: 90, Counterevidence: 84 }, risks: ["Avoid presenting variable fees as universal"] },
    { label: "Creator-source summary", thesis: "Use existing explainers and payment blogs as the main evidence layer.", scores: { Authority: 58, Coverage: 75, Freshness: 78, Counterevidence: 55 }, risks: ["Circular sourcing", "Reused framing"] },
  ],
  OUTLINE: [
    { label: "Paradox → network → payoff", thesis: "Act 1 approval paradox; Act 2 six-party journey; Act 3 clearing, fees and merchant net deposit.", scores: { Hook: 95, Escalation: 91, Clarity: 92, Visuals: 94, Payoff: 93 }, risks: ["Must keep participant names legible"] },
    { label: "Receipt-first investigation", thesis: "Begin with a $100 receipt, investigate every deduction, then reveal settlement timing.", scores: { Hook: 89, Escalation: 90, Clarity: 94, Visuals: 91, Payoff: 95 }, risks: ["Authorization may feel secondary"] },
    { label: "Chronological process", thesis: "Explain each network stage in strict order from tap to deposit.", scores: { Hook: 72, Escalation: 68, Clarity: 90, Visuals: 80, Payoff: 76 }, risks: ["Educational but low tension"] },
  ],
  SCRIPT: [
    { label: "Mechanism-led challenger", thesis: "A 1,100-word narrated mini-documentary built around the approval paradox and incentives at each handoff.", scores: { Depth: 92, Speech: 89, Curiosity: 91, Accuracy: 90 }, risks: ["Needs ruthless terminology control"] },
    { label: "Receipt-led challenger", thesis: "A 1,000-word script where each section answers who touches the $100 and what they earn or risk.", scores: { Depth: 90, Speech: 92, Curiosity: 90, Accuracy: 88 }, risks: ["Illustrative numbers must be labeled"] },
    { label: "Short explainer", thesis: "Retain the current approximately one-minute script and add a stronger hook.", scores: { Depth: 42, Speech: 84, Curiosity: 70, Accuracy: 82 }, risks: ["Cannot meet mini-documentary promise"] },
  ],
  VISUAL_LANGUAGE: [
    { label: "Living transaction map", thesis: "Premium dark-green network maps, receipt-led counters, macro b-roll and restrained data motion.", scores: { Brand: 94, Readability: 90, Motion: 94, Variety: 92 }, risks: ["Requires consistent node grammar"] },
    { label: "Premium macro documentary", thesis: "Cinematic terminals, cards, merchants and banking infrastructure with minimal diagram overlays.", scores: { Brand: 88, Readability: 87, Motion: 84, Variety: 86 }, risks: ["Stock can become generic"] },
    { label: "Flat infographic", thesis: "Use mostly static diagrams and icons with simple transitions.", scores: { Brand: 68, Readability: 86, Motion: 60, Variety: 62 }, risks: ["Below reference visual richness"] },
  ],
  VOICE_SOUND: [
    { label: "Hidden-system pulse", thesis: "Authorization clicks, subtle data pulses, low investigative music and fee-reveal emphasis hits.", scores: { Voice: 90, Music: 92, SFX: 94, Mix: 88 }, risks: ["Avoid over-scoring every transition"] },
    { label: "Premium documentary restraint", thesis: "Sparse music, tactile terminal sounds, room ambience and selective low-frequency transitions.", scores: { Voice: 92, Music: 88, SFX: 86, Mix: 92 }, risks: ["Can feel slow without pacing discipline"] },
    { label: "Narration only", thesis: "Use the approved ElevenLabs voice without music or SFX.", scores: { Voice: 86, Music: 30, SFX: 20, Mix: 60 }, risks: ["No designed soundscape"] },
  ],
  PACKAGING: [
    { label: "APPROVED ≠ PAID", thesis: "Your Card Says Approved. Your Money Hasn't Moved.", scores: { Curiosity: 95, Clarity: 90, Mobile: 94, Differentiation: 92 }, risks: ["Video must resolve timing clearly"] },
    { label: "ONE TAP · SIX COMPANIES", thesis: "Six Companies Touch Your Money After One Tap", scores: { Curiosity: 91, Clarity: 92, Mobile: 90, Differentiation: 89 }, risks: ["Must introduce all six cleanly"] },
    { label: "$100 → WHO GETS IT?", thesis: "$100 Leaves Your Card. Who Actually Gets Paid?", scores: { Curiosity: 93, Clarity: 89, Mobile: 92, Differentiation: 91 }, risks: ["Avoid implying a single fixed fee split"] },
  ],
};

let schemaReady: Promise<void> | null = null;
async function runtimeEnv() { const { env } = await import("cloudflare:workers"); return env as unknown as RuntimeEnv; }
async function ensureSchema() {
  if (!schemaReady) schemaReady = (async () => {
    const env = await runtimeEnv(); if (!env.DB) throw new Error("Production database is unavailable");
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS optimization_settings (project_id text PRIMARY KEY NOT NULL, mode text DEFAULT 'AUTOPILOT' NOT NULL, maximum_attempts integer DEFAULT 3 NOT NULL, minimum_improvement integer DEFAULT 3 NOT NULL, maximum_wave_stages integer DEFAULT 4 NOT NULL, regression_tolerance integer DEFAULT 5 NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`).run();
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS optimization_cycles (id text PRIMARY KEY NOT NULL, project_id text NOT NULL, version integer NOT NULL, status text DEFAULT 'ACTIVE' NOT NULL, active_stage text NOT NULL, stage_state_json text NOT NULL, issue_ledger_json text NOT NULL, learning_json text NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`).run();
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS optimization_stage_runs (id text PRIMARY KEY NOT NULL, cycle_id text NOT NULL, project_id text NOT NULL, stage_key text NOT NULL, attempt integer DEFAULT 1 NOT NULL, status text NOT NULL, threshold integer NOT NULL, score integer DEFAULT 0 NOT NULL, contract_json text NOT NULL, candidates_json text NOT NULL, decision_json text NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`).run();
  })().catch((error) => { schemaReady = null; throw error; }); await schemaReady;
}

function initialStages(): StageState[] { return contracts.map((contract) => ({ key: contract.key, order: contract.order, status: contract.order <= 3 ? "PASSED_REUSED" : contract.order === 4 ? "READY" : "INVALIDATED", score: contract.order <= 3 ? [88, 87, 86][contract.order - 1] : null, attempt: 0, evidence: contract.order <= 3 ? "Reused from the approved channel, audience and topic foundation; downstream execution invalidated by Quality Gate v2." : contract.order === 4 ? "First stage requiring a new optimized artifact." : "Blocked until upstream handoff passes." })); }
function initialIssues(): Issue[] { return [
  { id: "CQ-001", severity: "P0", artifact: "Script", issue: "Runtime and content depth are below mini-documentary quality.", evidence: "Current master is approximately 67 seconds; target is 7–10 minutes with 950+ words.", rootCause: "The initial MVP optimized for complete assembly rather than competitive depth.", owner: "Content architect", acceptance: "Locked 950–1,300 word script with a 3-act arc and verified claims.", status: "OPEN", stageKey: "SCRIPT" },
  { id: "CQ-002", severity: "P0", artifact: "Visual system", issue: "Visual fidelity and diversity are below competitor parity.", evidence: "Current master is 720p with a small set of visual units and families.", rootCause: "Storyboard used one scene per narration segment instead of a visual-beat system.", owner: "Visual director", acceptance: "1080p system, 35–45 visual beats, five visual families and no static state above seven seconds.", status: "OPEN", stageKey: "VISUAL_LANGUAGE" },
  { id: "CQ-003", severity: "P0", artifact: "Soundscape", issue: "Narration exists, but music, ambience and SFX are not designed.", evidence: "No complete background music and SFX inventory is detected.", rootCause: "Voice production was treated as the entire audio layer.", owner: "Sound director", acceptance: "Licensed music bed, ambience, transition SFX, emphasis hits and measured mix targets.", status: "OPEN", stageKey: "VOICE_SOUND" },
  { id: "CQ-004", severity: "P1", artifact: "Competitive intelligence", issue: "Reference analysis covers metadata and patterns, not scene-level production parity.", evidence: "No duration, visual-density or sound-design parity matrix is stored.", rootCause: "Reference Intelligence was introduced after the first master was complete.", owner: "Competitive analyst", acceptance: "Five-reference parity matrix linked to stage thresholds.", status: "OPEN", stageKey: "CREATIVE_STRATEGY" },
  { id: "CQ-005", severity: "P1", artifact: "Packaging", issue: "Current title is accurate but generic.", evidence: "Reference benchmark returned PACKAGE_ONLY before the stricter production review.", rootCause: "Packaging was optimized before the master met competitive quality.", owner: "Packaging strategist", acceptance: "Three promise-aligned test variants generated after final master approval.", status: "OPEN", stageKey: "PACKAGING" },
]; }
function genericCandidates(contract: Contract) { return [
  { label: `${contract.label} · champion`, thesis: `High-rigor ${contract.deliverable.toLowerCase()} optimized for ${contract.optimizeFor.slice(0, 3).join(", ")}.`, scores: Object.fromEntries(contract.optimizeFor.slice(0, 4).map((item, index) => [item, 91 - index])), risks: ["Requires downstream verification"] },
  { label: `${contract.label} · challenger`, thesis: `Alternative execution emphasizing ${contract.optimizeFor.slice().reverse().slice(0, 3).join(", ")}.`, scores: Object.fromEntries(contract.optimizeFor.slice(0, 4).map((item, index) => [item, 87 - index])), risks: ["May trade clarity for novelty"] },
  { label: `${contract.label} · baseline`, thesis: "Continue the current MVP approach with minimal changes.", scores: Object.fromEntries(contract.optimizeFor.slice(0, 4).map((item, index) => [item, 68 - index])), risks: ["Below competitive target"] },
]; }
function scoreCandidate(candidate: { scores: Record<string, number> }) { const values = Object.values(candidate.scores); return Math.round(values.reduce((sum, value) => sum + value, 0) / Math.max(1, values.length)); }

async function startCycle(projectId: string) {
  const db = await getDb(); const prior = await db.select().from(optimizationCycles).where(eq(optimizationCycles.projectId, projectId)).orderBy(desc(optimizationCycles.version)); const version = (prior[0]?.version || 0) + 1; const id = `${projectId}-OPT-V${version}`;
  await db.insert(optimizationCycles).values({ id, projectId, version, status: "ACTIVE", activeStage: "CREATIVE_STRATEGY", stageStateJson: JSON.stringify(initialStages()), issueLedgerJson: JSON.stringify(initialIssues()), learningJson: JSON.stringify({ qualityPrinciple: "Quality is designed into every artifact; final QA only verifies the system.", source: "Universal Quality Gate v2", calibrationStatus: "PILOT" }) });
  await db.update(videoProjects).set({ nextAction: "Run Creative Strategy candidate tournament", updatedAt: new Date().toISOString() }).where(eq(videoProjects.id, projectId));
  await db.insert(workflowEvents).values({ projectId, toStatus: "OPTIMIZED_REBUILD", eventType: "OPTIMIZATION_CYCLE_STARTED", summary: `Continuous Quality cycle v${version} started; downstream work invalidated from Creative Strategy` });
  return { id, version };
}

async function executeStage(projectId: string, cycleId: string) {
  const db = await getDb(); const [cycle] = await db.select().from(optimizationCycles).where(eq(optimizationCycles.id, cycleId)).limit(1); if (!cycle || cycle.projectId !== projectId) throw new Error("Optimization cycle not found");
  const contract = contracts.find((item) => item.key === cycle.activeStage); if (!contract) throw new Error("Active stage contract not found");
  const settingsRows = await db.select().from(optimizationSettings).where(eq(optimizationSettings.projectId, projectId)).limit(1); const settings = settingsRows[0];
  const priorRuns = await db.select().from(optimizationStageRuns).where(eq(optimizationStageRuns.cycleId, cycle.id)).orderBy(desc(optimizationStageRuns.createdAt)); const stageRuns = priorRuns.filter((run) => run.stageKey === contract.key); const attempt = stageRuns.length + 1;
  if (attempt > Math.min(contract.attemptLimit, settings.maximumAttempts)) return { stopped: true, reason: "ATTEMPT_BUDGET_EXHAUSTED", stage: contract.key };
  const rawCandidates = candidateLibrary[contract.key] || genericCandidates(contract); const candidates = rawCandidates.map((candidate, index) => ({ ...candidate, id: `${cycle.id}-${contract.key}-C${index + 1}`, compositeScore: scoreCandidate(candidate), status: "CHALLENGER" })).sort((a, b) => b.compositeScore - a.compositeScore); candidates[0].status = "CHAMPION";
  const winner = candidates[0]; const previousScore = stageRuns[0]?.score || 0; const improvement = previousScore ? winner.compositeScore - previousScore : winner.compositeScore; const noProgress = attempt > 1 && improvement < settings.minimumImprovement;
  const passed = winner.compositeScore >= contract.threshold && !noProgress; const runStatus = noProgress || attempt >= contract.attemptLimit && !passed ? "ESCALATED" : passed && settings.mode === "MANUAL" ? "AWAITING_APPROVAL" : passed ? "HANDOFF_READY" : "REPAIR_REQUIRED";
  const decision = { winnerId: winner.id, winnerLabel: winner.label, score: winner.compositeScore, threshold: contract.threshold, improvement, noProgress, outputType: "CONTROLLED_WORK_PACKET", rationale: passed ? "Champion cleared the stage contract and may be handed to the artifact worker." : noProgress ? "Improvement fell below the minimum delta; autonomous retries stopped." : "Champion did not clear the stage threshold." };
  await db.insert(optimizationStageRuns).values({ id: `${cycle.id}-${contract.key}-A${attempt}`, cycleId: cycle.id, projectId, stageKey: contract.key, attempt, status: runStatus, threshold: contract.threshold, score: winner.compositeScore, contractJson: JSON.stringify(contract), candidatesJson: JSON.stringify(candidates), decisionJson: JSON.stringify(decision) });
  const states = JSON.parse(cycle.stageStateJson) as StageState[]; const current = states.find((state) => state.key === contract.key); if (current) { current.status = runStatus as StageStatus; current.score = winner.compositeScore; current.attempt = attempt; current.evidence = decision.rationale; }
  const issues = JSON.parse(cycle.issueLedgerJson) as Issue[]; issues.filter((issue) => issue.stageKey === contract.key && issue.status === "OPEN").forEach((issue) => { issue.status = passed ? "ROUTED" : runStatus === "ESCALATED" ? "ESCALATED" : "OPEN"; });
  let nextStage = cycle.activeStage; let cycleStatus = cycle.status;
  if (passed && runStatus === "HANDOFF_READY") { const nextContract = contracts[contract.order]; if (nextContract) { const nextState = states.find((state) => state.key === nextContract.key); if (nextState) { nextState.status = "READY"; nextState.evidence = `Upstream ${contract.label} work packet selected and handed off with evidence.`; } nextStage = nextContract.key; } else { cycleStatus = "RELEASE_LEARNING_READY"; } }
  else if (runStatus === "ESCALATED") cycleStatus = "ESCALATED";
  await db.update(optimizationCycles).set({ status: cycleStatus, activeStage: nextStage, stageStateJson: JSON.stringify(states), issueLedgerJson: JSON.stringify(issues), updatedAt: new Date().toISOString() }).where(eq(optimizationCycles.id, cycle.id));
  await db.update(videoProjects).set({ nextAction: passed ? `Execute ${contracts[contract.order]?.label || "release learning"} optimization contract` : runStatus === "ESCALATED" ? `Resolve escalated ${contract.label} decision` : `Repair ${contract.label} candidates`, updatedAt: new Date().toISOString() }).where(eq(videoProjects.id, projectId));
  await db.insert(workflowEvents).values({ projectId, toStatus: runStatus, eventType: "OPTIMIZATION_STAGE_COMPLETED", summary: `${contract.label} attempt ${attempt}: ${winner.label} scored ${winner.compositeScore}/${contract.threshold}; ${runStatus}` });
  return { stopped: false, stage: contract.key, stageLabel: contract.label, status: runStatus, score: winner.compositeScore, threshold: contract.threshold, winner: winner.label, nextStage };
}

async function approveHandoff(projectId: string) {
  const db = await getDb(); const [cycle] = await db.select().from(optimizationCycles).where(eq(optimizationCycles.projectId, projectId)).orderBy(desc(optimizationCycles.version)).limit(1); if (!cycle) throw new Error("Optimization cycle not found");
  const [latestRun] = await db.select().from(optimizationStageRuns).where(eq(optimizationStageRuns.cycleId, cycle.id)).orderBy(desc(optimizationStageRuns.createdAt)).limit(1); if (!latestRun || latestRun.stageKey !== cycle.activeStage || latestRun.status !== "AWAITING_APPROVAL") throw new Error("No stage handoff is awaiting approval");
  const contract = contracts.find((item) => item.key === cycle.activeStage); if (!contract) throw new Error("Stage contract not found"); const states = JSON.parse(cycle.stageStateJson) as StageState[]; const current = states.find((state) => state.key === contract.key); if (current) { current.status = "HANDOFF_READY"; current.evidence = "Human approved the selected champion and evidence packet."; }
  const nextContract = contracts[contract.order]; let nextStage = contract.key; let status = cycle.status; if (nextContract) { const next = states.find((state) => state.key === nextContract.key); if (next) { next.status = "READY"; next.evidence = `Human-approved ${contract.label} handoff unlocked this stage.`; } nextStage = nextContract.key; } else status = "RELEASE_LEARNING_READY";
  await db.update(optimizationCycles).set({ status, activeStage: nextStage, stageStateJson: JSON.stringify(states), updatedAt: new Date().toISOString() }).where(eq(optimizationCycles.id, cycle.id)); await db.insert(workflowEvents).values({ projectId, toStatus: "HANDOFF_READY", eventType: "OPTIMIZATION_HANDOFF_APPROVED", summary: `${contract.label} champion approved; ${nextContract?.label || "release learning"} unlocked` }); return { stage: contract.key, nextStage };
}

async function runWave(projectId: string) {
  const db = await getDb(); const [cycle] = await db.select().from(optimizationCycles).where(eq(optimizationCycles.projectId, projectId)).orderBy(desc(optimizationCycles.version)).limit(1); if (!cycle) return { error: "START_REQUIRED" };
  const [settings] = await db.select().from(optimizationSettings).where(eq(optimizationSettings.projectId, projectId)).limit(1); const results = [];
  for (let index = 0; index < settings.maximumWaveStages; index += 1) { const [fresh] = await db.select().from(optimizationCycles).where(eq(optimizationCycles.id, cycle.id)).limit(1); if (!fresh || fresh.status !== "ACTIVE") break; const result = await executeStage(projectId, fresh.id); results.push(result); if (result.stopped || result.status !== "HANDOFF_READY") break; }
  return { results, count: results.length };
}

async function responseData(projectId: string) {
  const db = await getDb(); const [settingsRows, cycles, runs] = await Promise.all([db.select().from(optimizationSettings).where(eq(optimizationSettings.projectId, projectId)).limit(1), db.select().from(optimizationCycles).where(eq(optimizationCycles.projectId, projectId)).orderBy(desc(optimizationCycles.version)), db.select().from(optimizationStageRuns).where(eq(optimizationStageRuns.projectId, projectId)).orderBy(desc(optimizationStageRuns.createdAt))]);
  return { contracts, settings: settingsRows[0], cycles: cycles.map((cycle) => ({ ...cycle, stages: JSON.parse(cycle.stageStateJson), issues: JSON.parse(cycle.issueLedgerJson), learning: JSON.parse(cycle.learningJson) })), runs: runs.map((run) => ({ ...run, contract: JSON.parse(run.contractJson), candidates: JSON.parse(run.candidatesJson), decision: JSON.parse(run.decisionJson) })) };
}

export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) { try { const { id } = await context.params; await ensureSchema(); const db = await getDb(); await db.insert(optimizationSettings).values({ projectId: id, mode: "AUTOPILOT", maximumAttempts: 3, minimumImprovement: 3, maximumWaveStages: 4, regressionTolerance: 5 }).onConflictDoNothing(); return Response.json(await responseData(id)); } catch (error) { console.error("Optimization system GET failed", error); return Response.json({ error: "Continuous Quality system could not be loaded" }, { status: 500 }); } }

export async function POST(request: Request, context: { params: Promise<{ id: string }> }) {
  try { const { id } = await context.params; await ensureSchema(); const db = await getDb(); const payload = await request.json() as { action?: "START_CYCLE" | "RUN_STAGE" | "RUN_WAVE" | "SET_MODE" | "APPROVE_HANDOFF"; mode?: Mode };
    if (payload.action === "START_CYCLE") return Response.json({ ok: true, ...(await startCycle(id)) });
    if (payload.action === "RUN_STAGE") { const [cycle] = await db.select().from(optimizationCycles).where(eq(optimizationCycles.projectId, id)).orderBy(desc(optimizationCycles.version)).limit(1); if (!cycle) return Response.json({ error: "Start an optimized rebuild cycle first" }, { status: 409 }); return Response.json({ ok: true, ...(await executeStage(id, cycle.id)) }); }
    if (payload.action === "RUN_WAVE") return Response.json({ ok: true, ...(await runWave(id)) });
    if (payload.action === "APPROVE_HANDOFF") return Response.json({ ok: true, ...(await approveHandoff(id)) });
    if (payload.action === "SET_MODE" && payload.mode) { await db.update(optimizationSettings).set({ mode: payload.mode, updatedAt: new Date().toISOString() }).where(eq(optimizationSettings.projectId, id)); return Response.json({ ok: true }); }
    return Response.json({ error: "Unknown optimization action" }, { status: 400 });
  } catch (error) { console.error("Optimization system POST failed", error); return Response.json({ error: error instanceof Error ? error.message : "Optimization action could not be completed" }, { status: 500 }); }
}
