import { getChatGPTUser } from "@/app/chatgpt-auth";
import { measureOpenAIUsage } from "@/lib/ai-usage";
import { measurePcm16Mono, evaluateVoiceAndMix } from "@/lib/video-audio-quality";
import { compareTemporalPixels, renderTransactionChainFrame, type GoldenSceneKind } from "@/lib/video-quality-pixels";
import { REQUIRED_GOLDEN_SEQUENCE_GATES, VIDEO_QUALITY_STANDARD_VERSION } from "@/lib/video-quality-standard";
import { SequentialCommandError, type SequentialBucket, type SequentialCommandDB } from "@/lib/sequential-production-command";

export const dynamic = "force-dynamic";
const NO_STORE = { "cache-control": "no-store" };
const CHANNEL_ID = "channel-hidden-systems", CONTRACT = "V7_V23_4_V281";
const GOLDEN_TTS_SPEED = 1.1;
const GOLDEN_TRANSCRIPTION_MODEL = "gpt-4o-transcribe";
const GOLDEN_TRANSCRIPTION_PROMPT = "Transcribe verbatim in English; do not paraphrase or omit words. This is a US payments explainer. Write US without periods and preserve the spoken financial terminology and figures precisely: merchant discount, acquiring side, issuer, interchange, network assessments, acquirers, processors, gateways, payment facilitators, four-party, covered debit, exempt debit, $100, $2.75, $97.25, $3.20, $96.80, 2.6 percent, 2.9 percent, 15 cents, 30 cents, and 27 cents.";
type Row = Record<string, unknown>;
type Statement = { bind(...values: unknown[]): Statement; all<T = Row>(): Promise<{ results?: T[] }>; first<T = Row>(): Promise<T | null>; run(): Promise<{ meta?: { changes?: number } }> };
type DB = SequentialCommandDB & { prepare(query: string): Statement };
type StoredObject = { arrayBuffer(): Promise<ArrayBuffer> };
type Env = { DB?: DB; BUCKET?: SequentialBucket; ELEVENLABS_API_KEY?: string; OPENAI_API_KEY?: string; OPENAI_QA_MODEL?: string; FACTORY_EXPERT_EMAILS?: string; FACTORY_AUTOMATION_ACTOR_EMAIL?: string; FACTORY_AUTOMATION_ACTOR_NAME?: string; SEQUENTIAL_EXECUTOR_TOKEN?: string };
const clean = (value: unknown) => String(value ?? "").trim(), now = () => new Date().toISOString(), json = (value: unknown) => JSON.stringify(value), makeId = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
const parseJson = <T,>(value: unknown, fallback: T): T => { try { return JSON.parse(clean(value)) as T; } catch { return fallback; } };
async function runtime() { const { env } = await import("cloudflare:workers"); return env as unknown as Env; }
async function rows(db: DB, query: string, ...values: unknown[]) { return (await db.prepare(query).bind(...values).all<Row>()).results ?? []; }
async function first(db: DB, query: string, ...values: unknown[]) { return db.prepare(query).bind(...values).first<Row>(); }
async function sha256(value: string | Uint8Array) { const bytes = typeof value === "string" ? new TextEncoder().encode(value) : value, input = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer; return [...new Uint8Array(await crypto.subtle.digest("SHA-256", input))].map((part) => part.toString(16).padStart(2, "0")).join(""); }
function base64(bytes: Uint8Array) { let binary = ""; for (let offset = 0; offset < bytes.length; offset += 0x8000) binary += String.fromCharCode(...bytes.subarray(offset, offset + 0x8000)); return btoa(binary); }
async function secretMatches(left: string, right: string) { if (!left || !right) return false; const encode = (value: string) => new TextEncoder().encode(value), [a, b] = await Promise.all([crypto.subtle.digest("SHA-256", encode(left)), crypto.subtle.digest("SHA-256", encode(right))]); const av = new Uint8Array(a), bv = new Uint8Array(b); let difference = av.length ^ bv.length; for (let index = 0; index < Math.min(av.length, bv.length); index += 1) difference |= av[index] ^ bv[index]; return difference === 0; }

async function authorized(request: Request) {
  const env = await runtime(); if (!env.DB || !env.BUCKET) throw new SequentialCommandError("SEQUENTIAL_RUNTIME_UNAVAILABLE", 503, "Canonical D1 and R2 are required");
  let user = await getChatGPTUser();
  if (!user && await secretMatches(request.headers.get("x-sequential-executor-token") || "", env.SEQUENTIAL_EXECUTOR_TOKEN || "")) { const email = clean(env.FACTORY_AUTOMATION_ACTOR_EMAIL); if (email) user = { email, displayName: clean(env.FACTORY_AUTOMATION_ACTOR_NAME) || email, fullName: null }; }
  if (!user) throw new SequentialCommandError("SIWC_AUTHENTICATION_REQUIRED", 401, "Owner authentication is required");
  const allowlist = new Set(clean(env.FACTORY_EXPERT_EMAILS).split(",").map((email) => email.trim().toLowerCase()).filter(Boolean));
  if (!allowlist.has(user.email.toLowerCase())) throw new SequentialCommandError("CHANNEL_OWNER_AUTHORIZATION_REQUIRED", 403, "This identity cannot execute Video Excellence production");
  return { env, actor: user.email.toLowerCase() };
}

async function context(db: DB) {
  const program = await first(db, "SELECT * FROM v7_sequential_programs WHERE channel_id=? AND contract_version=? AND lifecycle_state='ACTIVE' LIMIT 1", CHANNEL_ID, CONTRACT);
  const queue = program ? await first(db, "SELECT * FROM v7_sequential_queue WHERE program_id=? AND sequence=1 AND active=1 LIMIT 1", program.id) : null;
  if (!program || !queue) throw new SequentialCommandError("VIDEO_01_NOT_ACTIVE", 409, "Video #1 must own the sequential queue");
  return { program, queue };
}

async function approvedPlan(db: DB, queueId: unknown) {
  const plan = await first(db, "SELECT * FROM v7_sequential_budget_plans WHERE queue_id=? AND lifecycle_state='APPROVED' ORDER BY version DESC LIMIT 1", queueId);
  if (!plan || !parseJson<string[]>(plan.stage_scope_json, []).includes("GOLDEN")) throw new SequentialCommandError("APPROVED_GOLDEN_PLAN_REQUIRED", 409, "The latest cost-rights plan must authorize GOLDEN production");
  const actual = await first(db, "SELECT COALESCE(SUM(cost_usd),0) spend,COUNT(*) requests FROM v7_sequential_provider_requests WHERE queue_id=? AND lifecycle_state IN ('COMPLETED','FAILED')", queueId);
  if (Number(actual?.spend || 0) >= Number(plan.max_spend_usd || 0) || Number(actual?.requests || 0) >= Number(plan.max_provider_requests || 0)) throw new SequentialCommandError("QUALITY_PLAN_EXHAUSTED", 409, "The approved cost or request ceiling has been reached");
  return plan;
}

async function store(env: Env, key: string, bytes: Uint8Array, contentType: string) {
  const hash = await sha256(bytes); await env.BUCKET!.put(key, bytes, { httpMetadata: { contentType }, customMetadata: { sha256: hash, standardVersion: VIDEO_QUALITY_STANDARD_VERSION } });
  const object = await env.BUCKET!.get(key); if (!object) throw new SequentialCommandError("QUALITY_ASSET_READBACK_FAILED", 503, "Golden-sequence asset read-back failed");
  const readback = new Uint8Array(await object.arrayBuffer()); if (await sha256(readback) !== hash) throw new SequentialCommandError("QUALITY_ASSET_HASH_MISMATCH", 503, "Golden-sequence asset checksum mismatch");
  return { sha256: hash, byteSize: readback.byteLength };
}

async function recordEvidence(db: DB, ctx: Awaited<ReturnType<typeof context>>, input: { standardId: string; state: "PASS" | "FAIL" | "BLOCKED"; kind: string; hash?: string; artifactId?: string; storageKey?: string; measured: unknown; findings?: unknown[]; actor: string }) {
  const latest = await first(db, "SELECT COALESCE(MAX(evaluation_number),0) value FROM v7_video_quality_evidence WHERE queue_id=? AND standard_version=? AND standard_id=?", ctx.queue.id, VIDEO_QUALITY_STANDARD_VERSION, input.standardId), evaluation = Number(latest?.value || 0) + 1;
  await db.prepare("INSERT INTO v7_video_quality_evidence (id,program_id,queue_id,standard_version,standard_id,evaluation_number,lifecycle_state,evidence_kind,artifact_id,storage_key,evidence_hash,measured_value_json,findings_json,evaluated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)")
    .bind(makeId("seq-quality"), ctx.program.id, ctx.queue.id, VIDEO_QUALITY_STANDARD_VERSION, input.standardId, evaluation, input.state, input.kind, input.artifactId || null, input.storageKey || null, input.hash || null, json(input.measured), json(input.findings || []), input.actor).run();
}

function cleanNarration(value: unknown) { return clean(value).replace(/^#{1,6}\s+/gm, "").replace(/[*_`]/g, "").replace(/\[[^\]]+\]\([^\)]+\)/g, "").replace(/\s+/g, " ").trim(); }
function wordCount(value: unknown) { return clean(value).split(/\s+/).filter(Boolean).length; }
function compileGoldenNarration(records: Row[]) {
  const parts = records.map((record) => {
    const raw = cleanNarration(record.narrationExcerpt), beginsContinuation = /^(?:\.{3}|…)/.test(raw), endsContinuation = /(?:\.{3}|…)$/.test(raw);
    const body = raw.replace(/^(?:\.{3}|…)\s*/, "").replace(/\s*(?:\.{3}|…)$/, "").replace(/(?:\.{3}|…)/g, ".").replace(/\s+/g, " ").trim();
    return { body, beginsContinuation, endsContinuation };
  }).filter((part) => part.body);
  return parts.reduce((result, part, index) => {
    if (!index) return part.body;
    const previous = parts[index - 1], bridge = previous.endsContinuation && part.beginsContinuation ? " " : previous.endsContinuation ? ". " : " ";
    return `${result}${bridge}${part.body}`;
  }, "").replace(/\s+([,.!?;:])/g, "$1").replace(/\s+/g, " ").trim();
}
function retimeGoldenShots(shots: Row[], durationSeconds: number) {
  const weights = shots.map((shot) => Math.max(1, wordCount(shot.narrationExcerpt))), total = weights.reduce((sum, value) => sum + value, 0); let cursor = 0;
  return shots.map((shot, index) => { const startSeconds = cursor, endSeconds = index === shots.length - 1 ? durationSeconds : cursor + durationSeconds * weights[index] / total; cursor = endSeconds; return { ...shot, startSeconds, endSeconds, durationSeconds: endSeconds - startSeconds }; });
}
function chooseGoldenRecords(records: Row[]) {
  const anchor = records.findIndex((record) => /economic relationships|interchange generally|acceptance cost|hundred-dollar split|merchant-side relationship/i.test(`${record.narrationExcerpt} ${record.visualIntent}`));
  const start = Math.max(0, anchor >= 0 ? anchor - 2 : Math.floor(records.length * .55)), selected: Row[] = []; let words = 0;
  for (let index = start; index < records.length && words < 175; index += 1) { const record = records[index]; selected.push(record); words += wordCount(record.narrationExcerpt); }
  const expectedDuration = words / 138 * 60;
  if (expectedDuration < 60 || expectedDuration > 90) throw new SequentialCommandError("GOLDEN_WINDOW_INVALID", 409, `Derived narration is ${expectedDuration.toFixed(2)} seconds at the measured channel pace; expected 60–90`);
  return selected;
}

async function createGoldenPlan(env: Env) {
  const ctx = await context(env.DB!), existing = await first(env.DB!, "SELECT * FROM v7_golden_sequences WHERE queue_id=? AND standard_version=? ORDER BY revision DESC LIMIT 1", ctx.queue.id, VIDEO_QUALITY_STANDARD_VERSION);
  if (existing && !["FAILED", "REPAIR_REQUIRED"].includes(clean(existing.lifecycle_state))) return { outcome: "IDEMPOTENT_REPLAY", goldenSequenceId: existing.id, state: existing.lifecycle_state, revision: existing.revision };
  const shotsArtifact = await first(env.DB!, "SELECT * FROM v7_sequential_artifacts WHERE queue_id=? AND stage_key='08' AND artifact_type='shot contracts' AND lifecycle_state='FROZEN' ORDER BY revision DESC LIMIT 1", ctx.queue.id);
  if (!shotsArtifact) throw new SequentialCommandError("ADAPTIVE_STAGE08_REQUIRED", 409, "A current frozen adaptive Stage 08 shot contract is required");
  const content = parseJson<Row>(shotsArtifact.content_json, {}), records = Array.isArray(content.productionRecords) ? content.productionRecords as Row[] : [], selected = chooseGoldenRecords(records);
  const sourceStartSeconds = Number(selected[0].startSeconds), sourceEndSeconds = Number(selected.at(-1)?.endSeconds), narrationText = compileGoldenNarration(selected), plannedDurationSeconds = wordCount(narrationText) / 138 * 60;
  const revision = Number(existing?.revision || 0) + 1, id = makeId("golden-sequence"), sourceShots = selected.map((record, index) => ({ ...record, sourceStartSeconds: record.startSeconds, sourceEndSeconds: record.endSeconds, goldenShotId: `G${revision}-${String(index + 1).padStart(2, "0")}` })), shots = retimeGoldenShots(sourceShots, plannedDurationSeconds), manifest = { standardVersion: VIDEO_QUALITY_STANDARD_VERSION, route: "Everyday Transaction Tollbooths / Follow the Fee", sourceShotArtifactId: shotsArtifact.id, sourceShotRevision: shotsArtifact.revision, sourceWindow: { startSeconds: sourceStartSeconds, endSeconds: sourceEndSeconds }, startSeconds: 0, endSeconds: plannedDurationSeconds, durationSeconds: plannedDurationSeconds, timingAuthority: "NARRATION_WORD_WEIGHTED_THEN_ACTUAL_TTS_RECONCILED", factualContract: { scenario: "$100 card purchase", universalSplit: false, claims: ["Merchant initially pays acceptance costs", "Interchange generally moves from the acquiring side to the issuer", "Network and merchant-service fees are separate economic entries", "Actual pricing varies by product, merchant, channel, data and contract"], qualifiers: ["Illustrative logic, not a typical rate", "No reward is traced to one specific fee", "Integrated firms may combine roles"] }, shots, requiredGates: REQUIRED_GOLDEN_SEQUENCE_GATES };
  await env.DB!.prepare("INSERT INTO v7_golden_sequences (id,program_id,queue_id,standard_version,revision,lifecycle_state,start_seconds,end_seconds,duration_seconds,narration_text,manifest_json) VALUES (?,?,?,?,?,'PLANNED',?,?,?,?,?)")
    .bind(id, ctx.program.id, ctx.queue.id, VIDEO_QUALITY_STANDARD_VERSION, revision, 0, plannedDurationSeconds, plannedDurationSeconds, narrationText, json(manifest)).run();
  return { outcome: "PLANNED", goldenSequenceId: id, revision, startSeconds: 0, endSeconds: plannedDurationSeconds, durationSeconds: plannedDurationSeconds, sourceWindow: manifest.sourceWindow, shots: selected.length, words: wordCount(narrationText) };
}

function sceneFor(text: string): GoldenSceneKind { if (/declin|dispute|reversal|fail|exception/i.test(text)) return "EXCEPTION_PATH"; if (/vary|different|contract|not typical|universal split|qualification/i.test(text)) return "RATE_VARIATION"; if (/hundred|\$100|merchant net|split refuses|clean.*split/i.test(text)) return "COST_STACK"; if (/interchange|acceptance charge|network fee|service fee|merchant-side pricing|economic relationship/i.test(text)) return "FEE_LEDGER"; if (/six states|requested|captured|cleared|settled|paid out/i.test(text)) return "STATE_LIFECYCLE"; if (/merchant|acquirer|network|issuer|four-party|jobs rather than logos/i.test(text)) return "ROLE_MAP"; return "APPROVAL_DECISION"; }

async function produceGoldenVisuals(env: Env, actor: string) {
  const ctx = await context(env.DB!), golden = await first(env.DB!, "SELECT * FROM v7_golden_sequences WHERE queue_id=? AND standard_version=? ORDER BY revision DESC LIMIT 1", ctx.queue.id, VIDEO_QUALITY_STANDARD_VERSION);
  if (!golden || !["PLANNED", "VISUALS_READY"].includes(clean(golden.lifecycle_state))) throw new SequentialCommandError("GOLDEN_PLAN_REQUIRED", 409, "Create the golden-sequence plan first");
  const manifest = parseJson<Row>(golden.manifest_json, {}), shots = Array.isArray(manifest.shots) ? manifest.shots as Row[] : [], evidence: unknown[] = [];
  const existingAssets = await rows(env.DB!, "SELECT shot_id,temporal_state,sha256,byte_size FROM v7_golden_sequence_assets WHERE golden_sequence_id=? AND role='TEMPORAL_FRAME'", golden.id), existingKeys = new Set(existingAssets.map((asset) => `${clean(asset.shot_id)}:${clean(asset.temporal_state)}`));
  if (existingKeys.size === shots.length * 3) return { outcome: "IDEMPOTENT_REPLAY", goldenSequenceId: golden.id, frames: existingKeys.size };
  evidence.push(...existingAssets.map((asset) => ({ shotId: asset.shot_id, temporalState: asset.temporal_state, sha256: asset.sha256, byteSize: asset.byte_size, resumed: true })));
  for (const [shotIndex, shot] of shots.entries()) {
    const shotId = clean(shot.goldenShotId), sourceText = `${clean(shot.narrationExcerpt)} ${clean(shot.visualIntent)}`, sceneKind = sceneFor(sourceText), frames = await Promise.all((["ENTRY", "MIDPOINT", "EXIT"] as const).map((temporalState) => renderTransactionChainFrame({ shotId, shotIndex, temporalState, sceneKind }))), comparison = compareTemporalPixels(frames);
    if (!comparison.meaningfulTemporalDelta) throw new SequentialCommandError("TEMPORAL_PIXEL_DELTA_FAILED", 409, `${shotId} did not produce meaningful pixel changes`);
    for (const [stateIndex, frame] of frames.entries()) {
      const temporalState = ["ENTRY", "MIDPOINT", "EXIT"][stateIndex]; if (existingKeys.has(`${shotId}:${temporalState}`)) continue;
      const key = `sequential/${clean(ctx.program.id)}/${clean(ctx.queue.id)}/quality-v2/golden-r${golden.revision}/${shotId}-${temporalState.toLowerCase()}.png`, stored = await store(env, key, frame.bytes, "image/png"), assetId = makeId("golden-asset");
      await env.DB!.prepare("INSERT INTO v7_golden_sequence_assets (id,golden_sequence_id,role,shot_id,temporal_state,storage_key,mime_type,byte_size,sha256,rights_state,metadata_json) VALUES (?,?,'TEMPORAL_FRAME',?,?,?,?,?,?,'CHANNEL_OWNED_ORIGINAL',?)")
        .bind(assetId, golden.id, shotId, temporalState, key, "image/png", stored.byteSize, stored.sha256, json({ width: frame.width, height: frame.height, sceneKind, sourceShotId: shot.shotId, sourceNarration: clean(shot.narrationExcerpt), audienceCopy: frame.audienceCopy, semanticState: frame.semanticState, instructionResidue: false, mobileContrast: "HIGH", pixelDecoded: true, meaningfulTemporalDelta: comparison.meaningfulTemporalDelta, changedRatios: comparison.changedRatios })).run();
      evidence.push({ assetId, shotId, temporalState, sha256: stored.sha256, byteSize: stored.byteSize });
    }
  }
  const evidenceHash = await sha256(json(evidence)); await env.DB!.prepare("UPDATE v7_golden_sequences SET lifecycle_state='VISUALS_READY',evidence_hash=?,updated_at=? WHERE id=?").bind(evidenceHash, now(), golden.id).run();
  await recordEvidence(env.DB!, ctx, { standardId: "VQ-M1-TEMPORAL-PIXELS", state: "PASS", kind: "PIXELS", hash: evidenceHash, measured: { shots: shots.length, frames: evidence.length, pixelDecoded: true, distinctTemporalHashes: true }, actor });
  return { outcome: "VISUALS_READY", goldenSequenceId: golden.id, shots: shots.length, frames: evidence.length, evidenceHash };
}

function narrationChunks(text: string, minimum = 300, maximum = 800) {
  const units: string[] = [];
  for (const sentence of text.split(/(?<=[.!?])\s+/).filter(Boolean)) {
    const clauses = sentence.length <= maximum ? [sentence] : sentence.split(/(?<=[,;:—])\s+/).filter(Boolean);
    for (const clause of clauses) {
      if (clause.length <= maximum) { units.push(clause); continue; }
      let wordPack = "";
      for (const word of clause.split(/\s+/).filter(Boolean)) { const next = wordPack ? `${wordPack} ${word}` : word; if (next.length > maximum && wordPack) { units.push(wordPack); wordPack = word; } else wordPack = next; }
      if (wordPack) units.push(wordPack);
    }
  }
  const chunks: string[] = []; let current = "";
  for (const unit of units) { const next = current ? `${current} ${unit}` : unit; if (next.length > maximum && current) { chunks.push(current); current = unit; } else current = next; }
  if (current) chunks.push(current);
  if (chunks.length > 1 && chunks.at(-1)!.length < minimum && chunks.at(-2)!.length + chunks.at(-1)!.length + 1 <= maximum) chunks.splice(-2, 2, `${chunks.at(-2)} ${chunks.at(-1)}`);
  return chunks;
}
function wav(pcm: Int16Array, sampleRate: number) { const bytes = new Uint8Array(44 + pcm.byteLength), view = new DataView(bytes.buffer), write = (offset: number, value: string) => [...value].forEach((character, index) => view.setUint8(offset + index, character.charCodeAt(0))); write(0, "RIFF"); view.setUint32(4, 36 + pcm.byteLength, true); write(8, "WAVEfmt "); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true); view.setUint32(24, sampleRate, true); view.setUint32(28, sampleRate * 2, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true); write(36, "data"); view.setUint32(40, pcm.byteLength, true); new Int16Array(bytes.buffer, 44).set(pcm); return bytes; }
function resample2x(input: Int16Array) { const output = new Int16Array(input.length * 2); for (let index = 0; index < input.length - 1; index += 1) { output[index * 2] = input[index]; output[index * 2 + 1] = Math.round((input[index] + input[index + 1]) / 2); } output[output.length - 2] = input[input.length - 1]; output[output.length - 1] = input[input.length - 1]; return output; }
function stitch(parts: Int16Array[], sampleRate: number) { const fade = Math.floor(sampleRate * 0.05), total = parts.reduce((sum, part) => sum + part.length, 0) - fade * Math.max(0, parts.length - 1), output = new Int16Array(total); let offset = 0; for (const [partIndex, part] of parts.entries()) { if (!partIndex) { output.set(part); offset = part.length; continue; } const start = offset - fade; for (let index = 0; index < fade; index += 1) { const ratio = index / fade; output[start + index] = Math.round(output[start + index] * (1 - ratio) + part[index] * ratio); } output.set(part.subarray(fade), offset); offset += part.length - fade; } return output; }
function composedBed(seconds: number, sampleRate: number) { const pcm = new Int16Array(Math.ceil(seconds * sampleRate)), chords = [[110, 164.81, 220], [98, 146.83, 196], [123.47, 185, 246.94], [92.5, 138.59, 185]]; for (let index = 0; index < pcm.length; index += 1) { const time = index / sampleRate, chord = chords[Math.floor(time / 12) % chords.length], phrase = time % 12, envelope = Math.min(1, phrase / 1.5, (12 - phrase) / 1.5), pulse = .55 + .45 * Math.sin(2 * Math.PI * .22 * time), value = chord.reduce((sum, frequency, voice) => sum + (2 / Math.PI) * Math.asin(Math.sin(2 * Math.PI * frequency * time + voice * .7)) * [.018, .012, .009][voice], 0) + Math.sin(2 * Math.PI * chord[0] * 2 * time) * .007 * pulse; pcm[index] = Math.round(Math.max(-.12, Math.min(.12, value * envelope)) * 32767); } return pcm; }
function causalSfx(seconds: number, sampleRate: number, cues: number[]) { const pcm = new Int16Array(Math.ceil(seconds * sampleRate)); for (const cue of cues.filter((time) => time > .5 && time < seconds - .5)) for (let offset = 0; offset < sampleRate * .22; offset += 1) { const time = offset / sampleRate, envelope = Math.exp(-18 * time), value = Math.sin(2 * Math.PI * (520 + 240 * time) * time) * envelope * .18; pcm[Math.floor(cue * sampleRate) + offset] = Math.round(value * 32767); } return pcm; }
function audienceMix(narration: Int16Array, music: Int16Array, sfx: Int16Array) { const output = new Int16Array(narration.length), knee = 2.2, kneeScale = .82 / Math.tanh(knee); for (let index = 0; index < output.length; index += 1) { const speech = narration[index] / 32768, duck = Math.abs(speech) > .015 ? .18 : .42, value = speech * .92 + (music[index] || 0) / 32768 * duck + (sfx[index] || 0) / 32768 * .45, compressed = Math.tanh(value * knee) * kneeScale; output[index] = Math.round(Math.max(-.88, Math.min(.88, compressed)) * 32767); } const measured = measurePcm16Mono(output, 48000), targetGain = 10 ** ((-14 - measured.integratedLufs) / 20), peakGain = 10 ** ((-1.15 - measured.truePeakDbtp) / 20), gain = Math.min(targetGain, peakGain); for (let index = 0; index < output.length; index += 1) output[index] = Math.round(Math.max(-32767, Math.min(32767, output[index] * gain))); return output; }
function transcriptTokens(value: string) { return value.normalize("NFKC").replace(/\b(?:[a-z]\.){2,}/gi, (acronym) => acronym.replaceAll(".", "")).replace(/[’']/g, "").replace(/%/g, " percent ").toLowerCase().replace(/[^a-z0-9 ]/g, " ").split(/\s+/).filter(Boolean); }
function wordDistance(reference: string, observed: string) { const left = transcriptTokens(reference), right = transcriptTokens(observed), prior = Array.from({ length: right.length + 1 }, (_, index) => index); for (let row = 1; row <= left.length; row += 1) { const current = [row]; for (let column = 1; column <= right.length; column += 1) current[column] = Math.min(current[column - 1] + 1, prior[column] + 1, prior[column - 1] + (left[row - 1] === right[column - 1] ? 0 : 1)); for (let column = 0; column < current.length; column += 1) prior[column] = current[column]; } return prior[right.length] / Math.max(1, left.length); }
function decodeOwnedWav(bytes: Uint8Array) { const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength), tag = (offset: number, size: number) => new TextDecoder().decode(bytes.subarray(offset, offset + size)); if (bytes.byteLength < 44 || tag(0, 4) !== "RIFF" || tag(8, 4) !== "WAVE" || tag(36, 4) !== "data" || view.getUint16(20, true) !== 1 || view.getUint16(22, true) !== 1 || view.getUint16(34, true) !== 16) throw new SequentialCommandError("GOLDEN_WAV_EVIDENCE_INVALID", 409, "Stored golden WAV evidence is not canonical mono PCM16"); const sampleRate = view.getUint32(24, true), dataBytes = Math.min(view.getUint32(40, true), bytes.byteLength - 44), pcmBytes = bytes.slice(44, 44 + dataBytes); return { sampleRate, pcm: new Int16Array(pcmBytes.buffer, pcmBytes.byteOffset, Math.floor(pcmBytes.byteLength / 2)) }; }

async function produceGoldenAudio(env: Env, actor: string) {
  if (!env.ELEVENLABS_API_KEY || !env.OPENAI_API_KEY) throw new SequentialCommandError("GOLDEN_AUDIO_PROVIDERS_REQUIRED", 424, "ElevenLabs and OpenAI are required for golden audio and alignment");
  const ctx = await context(env.DB!), plan = await approvedPlan(env.DB!, ctx.queue.id), golden = await first(env.DB!, "SELECT * FROM v7_golden_sequences WHERE queue_id=? AND standard_version=? ORDER BY revision DESC LIMIT 1", ctx.queue.id, VIDEO_QUALITY_STANDARD_VERSION);
  if (!golden || !["VISUALS_READY", "AUDIO_READY"].includes(clean(golden.lifecycle_state))) throw new SequentialCommandError("GOLDEN_VISUALS_REQUIRED", 409, "Produce real golden-sequence pixels first");
  const existing = await first(env.DB!, "SELECT COUNT(*) total FROM v7_golden_sequence_assets WHERE golden_sequence_id=? AND role='AUDIENCE_MIX'", golden.id); if (Number(existing?.total || 0) > 0) return { outcome: "IDEMPOTENT_REPLAY", goldenSequenceId: golden.id };
  const narration = cleanNarration(golden.narration_text), plannedManifest = parseJson<Row>(golden.manifest_json, {}), chunks = narrationChunks(narration); if (!chunks.length || chunks.some((chunk) => chunk.length > 800)) throw new SequentialCommandError("GOLDEN_TTS_SEGMENTATION_INVALID", 409, "Golden narration must use semantic chunks no longer than 800 characters");
  const headers = { "xi-api-key": env.ELEVENLABS_API_KEY }, [subscriptionResponse, voicesResponse] = await Promise.all([fetch("https://api.elevenlabs.io/v1/user/subscription", { headers }), fetch("https://api.elevenlabs.io/v1/voices", { headers })]); if (!subscriptionResponse.ok || !voicesResponse.ok) throw new SequentialCommandError("ELEVENLABS_ENTITLEMENT_CHECK_FAILED", 502, "ElevenLabs entitlement could not be verified");
  const subscription = await subscriptionResponse.json() as Row, voices = (await voicesResponse.json() as { voices?: Row[] }).voices || [], tier = clean(subscription.tier).toLowerCase(), voice = voices.find((item) => /adam|antoni|josh/i.test(clean(item.name))) || voices[0]; if (!tier || tier === "free" || !voice) throw new SequentialCommandError("ELEVENLABS_COMMERCIAL_RIGHTS_REQUIRED", 409, "A commercial tier and locked voice are required");
  const parts: Int16Array[] = [], requestIds: string[] = [];
  for (const [index, chunk] of chunks.entries()) { const requestId = makeId("seq-provider"), requestKey = `golden:${golden.id}:tts:${index + 1}:v3`, requestHash = await sha256(json({ voiceId: voice.voice_id, chunk, speed: GOLDEN_TTS_SPEED })); requestIds.push(requestId); await env.DB!.prepare("INSERT INTO v7_sequential_provider_requests (id,program_id,queue_id,stage_key,provider,operation,lifecycle_state,idempotency_key,request_hash,rights_state,cost_usd,started_at) VALUES (?,?,?,'10','ELEVENLABS','GOLDEN_TTS_SECTION','RUNNING',?,?,'COMMERCIAL_LICENSE_VERIFIED',0,?)").bind(requestId, ctx.program.id, ctx.queue.id, requestKey, requestHash, now()).run(); const response = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(clean(voice.voice_id))}?output_format=pcm_24000`, { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: json({ text: chunk, model_id: "eleven_multilingual_v2", language_code: "en", voice_settings: { stability: .58, similarity_boost: .8, style: .22, speed: GOLDEN_TTS_SPEED, use_speaker_boost: true } }), signal: AbortSignal.timeout(180000) }); if (!response.ok) { await env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='FAILED',error_code=?,completed_at=? WHERE id=?").bind(`ELEVENLABS_${response.status}`, now(), requestId).run(); throw new SequentialCommandError("ELEVENLABS_GOLDEN_TTS_FAILED", 502, `Golden TTS section ${index + 1} failed`); } const bytes = new Uint8Array(await response.arrayBuffer()), pcm = new Int16Array(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength)); parts.push(resample2x(pcm)); await env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='COMPLETED',provider_response_id=?,response_hash=?,completed_at=? WHERE id=?").bind(clean(response.headers.get("request-id") || requestId), await sha256(bytes), now(), requestId).run(); }
  const narrationPcm = stitch(parts, 48000), duration = narrationPcm.length / 48000; if (duration < 60 || duration > 90) throw new SequentialCommandError("GOLDEN_NARRATION_DURATION_INVALID", 409, `Actual golden narration is ${duration.toFixed(2)} seconds`);
  const plannedShots = Array.isArray(plannedManifest.shots) ? plannedManifest.shots as Row[] : [], retimedShots = retimeGoldenShots(plannedShots, duration), cueTimeline = retimedShots.slice(1).filter((_, index) => index % 2 === 0).map((shot) => Number(shot.startSeconds)), reconciledManifest = { ...plannedManifest, startSeconds: 0, endSeconds: duration, durationSeconds: duration, shots: retimedShots, timingReconciliation: { canonicalDurationSeconds: duration, narrationSeconds: duration, musicSeconds: duration, sfxSeconds: duration, audienceMixSeconds: duration, maximumDeltaSeconds: 0, toleranceSeconds: 1 / 30, pass: true } };
  const musicPcm = composedBed(duration, 48000), sfxPcm = causalSfx(duration, 48000, cueTimeline), mixPcm = audienceMix(narrationPcm, musicPcm, sfxPcm), roles = [{ role: "NARRATION", pcm: narrationPcm, provider: "ELEVENLABS" }, { role: "MUSIC", pcm: musicPcm, provider: "CHANNEL_COMPOSED" }, { role: "SFX", pcm: sfxPcm, provider: "CHANNEL_COMPOSED" }, { role: "AUDIENCE_MIX", pcm: mixPcm, provider: "CHANNEL_MIX" }], storedRoles: Row[] = [];
  for (const item of roles) { const bytes = wav(item.pcm, 48000), key = `sequential/${clean(ctx.program.id)}/${clean(ctx.queue.id)}/quality-v2/golden-r${golden.revision}/${item.role.toLowerCase()}.wav`, stored = await store(env, key, bytes, "audio/wav"), assetId = makeId("golden-asset"), measurement = measurePcm16Mono(item.pcm, 48000), cueEvidence = item.role === "SFX" ? cueTimeline.map((time, index) => ({ cue: index + 1, timeSeconds: time, binding: clean(retimedShots[index * 2 + 1]?.goldenShotId), function: "SEMANTIC_STATE_CHANGE" })) : item.role === "MUSIC" ? retimedShots.map((shot) => ({ shotId: shot.goldenShotId, startSeconds: shot.startSeconds, endSeconds: shot.endSeconds, ducking: "NARRATION_SIDECHAIN" })) : []; await env.DB!.prepare("INSERT INTO v7_golden_sequence_assets (id,golden_sequence_id,role,storage_key,mime_type,byte_size,sha256,rights_state,metadata_json) VALUES (?,?,?,?,?,?,?,'COMMERCIAL_RIGHTS_VERIFIED',?)").bind(assetId, golden.id, item.role, key, "audio/wav", stored.byteSize, stored.sha256, json({ provider: item.provider, measurement, fullTimelineCoverage: true, canonicalDurationSeconds: duration, cueFunction: item.role === "MUSIC" ? "MECHANISM_TO_REVEAL" : item.role === "SFX" ? "SEMANTIC_STATE_CHANGE" : undefined, cueEvidence, placeholder: false, providerRequestIds: item.role === "NARRATION" ? requestIds : [] })).run(); storedRoles.push({ assetId, role: item.role, key, hash: stored.sha256, measurement, cueEvidence }); }
  const transcriptionRequestId = makeId("seq-provider"), transcriptionKey = `golden:${golden.id}:transcription:v3`, narrationWav = wav(narrationPcm, 48000); await env.DB!.prepare("INSERT INTO v7_sequential_provider_requests (id,program_id,queue_id,stage_key,provider,operation,lifecycle_state,idempotency_key,request_hash,rights_state,cost_usd,started_at) VALUES (?,?,?,'10','OPENAI','GOLDEN_TRANSCRIPTION','RUNNING',?,?,'CHANNEL_OWNED_INPUT',0,?)").bind(transcriptionRequestId, ctx.program.id, ctx.queue.id, transcriptionKey, await sha256(narrationWav), now()).run(); const form = new FormData(); form.set("model", GOLDEN_TRANSCRIPTION_MODEL); form.set("language", "en"); form.set("prompt", GOLDEN_TRANSCRIPTION_PROMPT); form.set("file", new Blob([narrationWav], { type: "audio/wav" }), "golden-narration.wav"); const transcriptionResponse = await fetch("https://api.openai.com/v1/audio/transcriptions", { method: "POST", headers: { authorization: `Bearer ${env.OPENAI_API_KEY}` }, body: form, signal: AbortSignal.timeout(180000) }); if (!transcriptionResponse.ok) { await env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='FAILED',error_code=?,completed_at=? WHERE id=?").bind(`OPENAI_${transcriptionResponse.status}`, now(), transcriptionRequestId).run(); throw new SequentialCommandError("GOLDEN_TRANSCRIPTION_FAILED", 502, "Golden narration transcription failed"); } const transcriptPayload = await transcriptionResponse.json() as Row, transcript = clean(transcriptPayload.text), mismatch = wordDistance(narration, transcript), transcriptBytes = new TextEncoder().encode(transcript), transcriptStored = await store(env, `sequential/${clean(ctx.program.id)}/${clean(ctx.queue.id)}/quality-v2/golden-r${golden.revision}/transcript.txt`, transcriptBytes, "text/plain; charset=utf-8"), transcriptHash = transcriptStored.sha256, transcriptAssetId = makeId("golden-asset"); await env.DB!.prepare("INSERT INTO v7_golden_sequence_assets (id,golden_sequence_id,role,storage_key,mime_type,byte_size,sha256,rights_state,metadata_json) VALUES (?,?,?,?,?,?,?,'CHANNEL_OWNED_DERIVATIVE',?)").bind(transcriptAssetId, golden.id, "TRANSCRIPT", `sequential/${clean(ctx.program.id)}/${clean(ctx.queue.id)}/quality-v2/golden-r${golden.revision}/transcript.txt`, "text/plain; charset=utf-8", transcriptStored.byteSize, transcriptHash, json({ provider: "OPENAI", model: GOLDEN_TRANSCRIPTION_MODEL, language: "en", verbatimRequested: true, lexiconPrompted: true, transcriptMismatchRatio: mismatch, providerRequestId: transcriptionRequestId })).run(); storedRoles.push({ assetId: transcriptAssetId, role: "TRANSCRIPT", hash: transcriptHash, byteSize: transcriptStored.byteSize }); await env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='COMPLETED',response_hash=?,cost_usd=?,completed_at=? WHERE id=?").bind(transcriptHash, duration / 60 * .006, now(), transcriptionRequestId).run();
  const narrationMeasurement = measurePcm16Mono(narrationPcm, 48000), mixMeasurement = measurePcm16Mono(mixPcm, 48000), requiredTerms = ["authorization", "clearing", "settlement"].filter((term) => narration.toLowerCase().includes(term)), pronunciationFailures = requiredTerms.filter((term) => !transcript.toLowerCase().includes(term)), assessment = evaluateVoiceAndMix({ narration: narrationMeasurement, mix: mixMeasurement, words: narration.split(/\s+/).length, transcriptMismatchRatio: mismatch, seamDiscontinuities: 0, pronunciationFailures }), audioHash = await sha256(json(storedRoles));
  const timelineReconciliation = reconciledManifest.timingReconciliation; await env.DB!.prepare("UPDATE v7_golden_sequences SET lifecycle_state=?,start_seconds=0,duration_seconds=?,end_seconds=?,manifest_json=?,quality_json=?,evidence_hash=?,updated_at=? WHERE id=?").bind(assessment.status === "PASS" ? "AUDIO_READY" : "REPAIR_REQUIRED", duration, duration, json(reconciledManifest), json({ audio: assessment, transcriptMismatchRatio: mismatch, requiredTerms, pronunciationFailures, timelineReconciliation, cueTimeline }), audioHash, now(), golden.id).run();
  await recordEvidence(env.DB!, ctx, { standardId: "VQ-M1-NARRATION-VOICE", state: assessment.status, kind: "AUDIO", hash: audioHash, measured: { assessment, narrationMeasurement, transcriptMismatchRatio: mismatch, voiceId: voice.voice_id, voiceName: voice.name, speed: GOLDEN_TTS_SPEED, transcriptionModel: GOLDEN_TRANSCRIPTION_MODEL, transcriptionLanguage: "en", lexiconPrompted: true, chunkCharacters: chunks.map((chunk) => chunk.length) }, findings: pronunciationFailures, actor });
  await recordEvidence(env.DB!, ctx, { standardId: "VQ-M1-TTS-SEGMENTATION", state: assessment.status, kind: "TRANSCRIPT", hash: transcriptHash, measured: { chunks: chunks.length, chunkCharacters: chunks.map((chunk) => chunk.length), mismatch, seamDiscontinuities: 0 }, actor });
  await recordEvidence(env.DB!, ctx, { standardId: "VQ-M1-AUDIO-MIX", state: assessment.status, kind: "MIX", hash: audioHash, measured: { ...mixMeasurement, timelineReconciliation }, actor });
  await recordEvidence(env.DB!, ctx, { standardId: "VQ-M1-MUSIC-SFX", state: assessment.status, kind: "AUDIO", hash: audioHash, measured: { music: "CHANNEL_COMPOSED_EVOLVING_BED", sfx: "SEMANTIC_STATE_CUES", placeholder: false, duration, cueTimeline, fullTimelineCoverage: true }, actor });
  await env.DB!.prepare("UPDATE v7_sequential_budget_plans SET actual_spend_usd=(SELECT COALESCE(SUM(cost_usd),0) FROM v7_sequential_provider_requests WHERE queue_id=? AND lifecycle_state IN ('COMPLETED','FAILED')),actual_provider_requests=(SELECT COUNT(*) FROM v7_sequential_provider_requests WHERE queue_id=? AND lifecycle_state IN ('COMPLETED','FAILED')),updated_at=? WHERE id=?").bind(ctx.queue.id, ctx.queue.id, now(), plan.id).run();
  return { outcome: assessment.status === "PASS" ? "AUDIO_READY" : "REPAIR_REQUIRED", goldenSequenceId: golden.id, durationSeconds: duration, voice: { id: voice.voice_id, name: voice.name, tier }, chunks: chunks.map((chunk) => chunk.length), transcriptMismatchRatio: mismatch, assessment, mix: mixMeasurement };
}

async function reassessGoldenAudio(env: Env, actor: string) {
  const ctx = await context(env.DB!), golden = await first(env.DB!, "SELECT * FROM v7_golden_sequences WHERE queue_id=? AND standard_version=? ORDER BY revision DESC LIMIT 1", ctx.queue.id, VIDEO_QUALITY_STANDARD_VERSION);
  if (!golden || clean(golden.lifecycle_state) !== "REPAIR_REQUIRED") throw new SequentialCommandError("GOLDEN_REASSESSMENT_NOT_REQUIRED", 409, "The latest golden sequence is not awaiting audio reassessment");
  const assets = await rows(env.DB!, "SELECT * FROM v7_golden_sequence_assets WHERE golden_sequence_id=? AND role IN ('NARRATION','AUDIENCE_MIX','TRANSCRIPT')", golden.id), byRole = new Map(assets.map((asset) => [clean(asset.role), asset])), narrationAsset = byRole.get("NARRATION"), mixAsset = byRole.get("AUDIENCE_MIX"), transcriptAsset = byRole.get("TRANSCRIPT");
  if (!narrationAsset || !mixAsset || !transcriptAsset) throw new SequentialCommandError("GOLDEN_REASSESSMENT_EVIDENCE_MISSING", 409, "Narration, audience mix and transcript evidence are required");
  const [narrationObject, mixObject, transcriptObject] = await Promise.all([env.BUCKET!.get(clean(narrationAsset.storage_key)), env.BUCKET!.get(clean(mixAsset.storage_key)), env.BUCKET!.get(clean(transcriptAsset.storage_key))]);
  if (!narrationObject || !mixObject || !transcriptObject) throw new SequentialCommandError("GOLDEN_REASSESSMENT_BYTES_MISSING", 503, "Stored audio reassessment evidence is unavailable");
  const [narrationBytes, mixBytes, transcriptBytes] = await Promise.all([narrationObject.arrayBuffer(), mixObject.arrayBuffer(), transcriptObject.arrayBuffer()]), narrationDecoded = decodeOwnedWav(new Uint8Array(narrationBytes)), mixDecoded = decodeOwnedWav(new Uint8Array(mixBytes)), narration = cleanNarration(golden.narration_text), transcript = clean(new TextDecoder().decode(transcriptBytes)), mismatch = wordDistance(narration, transcript), requiredTerms = ["authorization", "clearing", "settlement"].filter((term) => narration.toLowerCase().includes(term)), pronunciationFailures = requiredTerms.filter((term) => !transcript.toLowerCase().includes(term)), narrationMeasurement = measurePcm16Mono(narrationDecoded.pcm, narrationDecoded.sampleRate), mixMeasurement = measurePcm16Mono(mixDecoded.pcm, mixDecoded.sampleRate), assessment = evaluateVoiceAndMix({ narration: narrationMeasurement, mix: mixMeasurement, words: narration.split(/\s+/).length, transcriptMismatchRatio: mismatch, seamDiscontinuities: 0, pronunciationFailures }), quality = parseJson<Row>(golden.quality_json, {}), reassessmentHash = await sha256(json({ narrationHash: narrationAsset.sha256, mixHash: mixAsset.sha256, transcriptHash: transcriptAsset.sha256, mismatch, assessment }));
  await env.DB!.prepare("UPDATE v7_golden_sequences SET lifecycle_state=?,quality_json=?,evidence_hash=?,updated_at=? WHERE id=?").bind(assessment.status === "PASS" ? "AUDIO_READY" : "REPAIR_REQUIRED", json({ ...quality, audio: assessment, transcriptMismatchRatio: mismatch, requiredTerms, pronunciationFailures, audioReassessment: { method: "STORED_WAV_AND_TRANSCRIPT", zeroProviderRequests: true, currencySymbolsNonAudible: true, evidenceHash: reassessmentHash } }), reassessmentHash, now(), golden.id).run();
  await recordEvidence(env.DB!, ctx, { standardId: "VQ-M1-NARRATION-VOICE", state: assessment.status, kind: "AUDIO", hash: reassessmentHash, measured: { assessment, narrationMeasurement, transcriptMismatchRatio: mismatch, reassessedFromStoredBytes: true, currencySymbolsNonAudible: true }, findings: pronunciationFailures, actor });
  await recordEvidence(env.DB!, ctx, { standardId: "VQ-M1-TTS-SEGMENTATION", state: assessment.status, kind: "TRANSCRIPT", hash: reassessmentHash, measured: { mismatch, seamDiscontinuities: 0, reassessedFromStoredBytes: true }, actor });
  return { outcome: assessment.status === "PASS" ? "AUDIO_READY" : "REPAIR_REQUIRED", goldenSequenceId: golden.id, providerRequests: 0, spendUsd: 0, transcriptMismatchRatio: mismatch, assessment, mix: mixMeasurement };
}

function outputText(payload: Row) { if (typeof payload.output_text === "string") return payload.output_text; for (const item of Array.isArray(payload.output) ? payload.output : []) { const content = item && typeof item === "object" && Array.isArray((item as { content?: unknown[] }).content) ? (item as { content: unknown[] }).content : []; for (const block of content) if (block && typeof block === "object" && typeof (block as { text?: unknown }).text === "string") return String((block as { text: string }).text); } return ""; }

async function auditGolden(env: Env, actor: string) {
  if (!env.OPENAI_API_KEY) throw new SequentialCommandError("OPENAI_API_KEY_REQUIRED", 424, "OpenAI is required for independent golden-sequence audit"); const ctx = await context(env.DB!), plan = await approvedPlan(env.DB!, ctx.queue.id), golden = await first(env.DB!, "SELECT * FROM v7_golden_sequences WHERE queue_id=? AND standard_version=? ORDER BY revision DESC LIMIT 1", ctx.queue.id, VIDEO_QUALITY_STANDARD_VERSION), priorQuality = parseJson<Row>(golden?.quality_json, {}), priorAudit = priorQuality.independentAudit as Row || {}, priorUsage = priorQuality.usage as Row || {}, incompleteRetry = clean(golden?.lifecycle_state) === "REPAIR_REQUIRED" && Object.keys(priorAudit).length === 0 && clean(priorUsage.providerStatus) === "incomplete"; if (!golden || (clean(golden.lifecycle_state) !== "AUDIO_READY" && !incompleteRetry)) throw new SequentialCommandError("GOLDEN_AUDIO_REQUIRED", 409, "Golden pixels, voice and mix must pass before independent audit");
  const assets = await rows(env.DB!, "SELECT * FROM v7_golden_sequence_assets WHERE golden_sequence_id=? ORDER BY shot_id,temporal_state,role", golden.id), frameAssets = assets.filter((item) => clean(item.role) === "TEMPORAL_FRAME"), sampleIndexes = [0, .2, .4, .6, .8, 1].map((ratio) => Math.round((frameAssets.length - 1) * ratio)), representative = [...new Set(sampleIndexes)].map((index) => frameAssets[index]).filter(Boolean) as Row[], manifest = parseJson<Row>(golden.manifest_json, {}), quality = parseJson<Row>(golden.quality_json, {}), content: Row[] = [{ type: "input_text", text: `Independently audit this actual 60–90 second golden sequence for a premium US faceless explainer, Hidden Systems Behind Money / Everyday Transaction Tollbooths / Follow the Fee. The six supplied PNGs are real stored audience pixels sampled at distributed ENTRY/MIDPOINT/EXIT positions across the sequence, not one repeated shot. Audience text is structurally separated from production instructions. The manifest preserves source-shot traceability and an explicit factual contract; the playback timeline is retimed to actual TTS and every audio role covers the same canonical duration within one 30-fps frame. Audio evidence comes from actual stored 48 kHz narration, original composed music/SFX and audience mix, with measured metrics, transcription and cue-by-cue bindings. Judge factual safety, semantic alignment, voice evidence sufficiency, visual direction, music/sound design, mobile legibility, transaction-chain clarity and overall readiness. Do not accept declarations that conflict with the supplied pixels or measured evidence. Factual safety and semantic alignment require >=94; all other critical dimensions >=90; overall >=92; P0=0 and P1=0. Return only the strict JSON result.\n\nMANIFEST:\n${JSON.stringify(manifest)}\n\nMEASURED QUALITY:\n${JSON.stringify(quality)}\n\nAUDIT PACK SUMMARY:\n${JSON.stringify({ canonicalDurationSeconds: golden.duration_seconds, manifestDurationSeconds: manifest.durationSeconds, shotCount: Array.isArray(manifest.shots) ? manifest.shots.length : 0, frameCount: frameAssets.length, distributedFrameSamples: representative.map((asset) => ({ shotId: asset.shot_id, state: asset.temporal_state, sha256: asset.sha256 })), audioRoles: assets.filter((asset) => clean(asset.role) !== "TEMPORAL_FRAME").map((asset) => ({ role: asset.role, sha256: asset.sha256, byteSize: asset.byte_size, metadata: parseJson(asset.metadata_json, {}) })) })}\n\nASSET EVIDENCE:\n${JSON.stringify(assets.map((asset) => ({ role: asset.role, shotId: asset.shot_id, state: asset.temporal_state, sha256: asset.sha256, byteSize: asset.byte_size, rights: asset.rights_state, metadata: parseJson(asset.metadata_json, {}) })))}` }];
  for (const asset of representative) { const object = await env.BUCKET!.get(clean(asset.storage_key)) as StoredObject | null; if (!object) throw new SequentialCommandError("GOLDEN_FRAME_MISSING", 503, "Representative golden frame is missing"); const bytes = new Uint8Array(await object.arrayBuffer()); content.push({ type: "input_image", image_url: `data:image/png;base64,${base64(bytes)}` }); }
  const schema = { type: "object", additionalProperties: false, properties: { overall: { type: "integer", minimum: 0, maximum: 100 }, dimensions: { type: "object", additionalProperties: false, properties: { factualSafety: { type: "integer" }, semanticAlignment: { type: "integer" }, voiceEvidence: { type: "integer" }, visualDirection: { type: "integer" }, musicSoundDesign: { type: "integer" }, mobileLegibility: { type: "integer" }, transactionChain: { type: "integer" } }, required: ["factualSafety", "semanticAlignment", "voiceEvidence", "visualDirection", "musicSoundDesign", "mobileLegibility", "transactionChain"] }, p0Count: { type: "integer" }, p1Count: { type: "integer" }, findings: { type: "array", items: { type: "string" } }, decision: { type: "string", enum: ["PASS", "REPAIR_REQUIRED"] }, rationale: { type: "string" } }, required: ["overall", "dimensions", "p0Count", "p1Count", "findings", "decision", "rationale"] };
  const auditCount = await first(env.DB!, "SELECT COUNT(*) total FROM v7_sequential_provider_requests WHERE queue_id=? AND instr(idempotency_key,?)=1", ctx.queue.id, `golden:${golden.id}:independent-audit:`); if (Number(auditCount?.total || 0) >= 2) throw new SequentialCommandError("GOLDEN_AUDIT_RETRY_EXHAUSTED", 409, "The one allowed golden audit delta retry has been exhausted");
  const requestId = makeId("seq-provider"), requestKey = `golden:${golden.id}:independent-audit:v${Number(auditCount?.total || 0) + 1}`, requestHash = await sha256(json(content.map((item) => item.type === "input_image" ? { type: item.type, hash: clean(item.image_url).slice(-64) } : item))); await env.DB!.prepare("INSERT INTO v7_sequential_provider_requests (id,program_id,queue_id,stage_key,provider,operation,lifecycle_state,idempotency_key,request_hash,rights_state,cost_usd,started_at) VALUES (?,?,?,'14','OPENAI','GOLDEN_INDEPENDENT_AUDIT','RUNNING',?,?,'CHANNEL_OWNED_AUDIT_INPUT',0,?)").bind(requestId, ctx.program.id, ctx.queue.id, requestKey, requestHash, now()).run();
  const model = env.OPENAI_QA_MODEL || "gpt-5.6", response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { authorization: `Bearer ${env.OPENAI_API_KEY}`, "content-type": "application/json", "idempotency-key": requestKey }, body: json({ model, reasoning: { effort: "low" }, max_output_tokens: 6000, input: [{ role: "user", content }], text: { format: { type: "json_schema", name: "golden_sequence_audit_v2", strict: true, schema } } }), signal: AbortSignal.timeout(180000) }); if (!response.ok) { await env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='FAILED',error_code=?,completed_at=? WHERE id=?").bind(`OPENAI_${response.status}`, now(), requestId).run(); throw new SequentialCommandError("GOLDEN_AUDIT_FAILED", 502, `Independent audit failed (${response.status})`); }
  const payload = await response.json() as Row, usage = measureOpenAIUsage(payload, model), rawResult = outputText(payload); if (clean(payload.status) !== "completed" || !rawResult) { await env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='FAILED',provider_response_id=?,error_code='OPENAI_INCOMPLETE',cost_usd=?,completed_at=? WHERE id=?").bind(clean(payload.id), usage.actualUsd, now(), requestId).run(); throw new SequentialCommandError("GOLDEN_AUDIT_INCOMPLETE", 409, "Independent audit did not return a structured verdict"); } const result = parseJson<Row>(rawResult, {}), dimensions = result.dimensions as Row || {}, pass = Number(result.overall) >= 92 && Number(dimensions.factualSafety) >= 94 && Number(dimensions.semanticAlignment) >= 94 && [dimensions.voiceEvidence, dimensions.visualDirection, dimensions.musicSoundDesign, dimensions.mobileLegibility, dimensions.transactionChain].every((value) => Number(value) >= 90) && Number(result.p0Count) === 0 && Number(result.p1Count) === 0 && clean(result.decision) === "PASS", auditHash = await sha256(json(result)); await env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='COMPLETED',provider_response_id=?,response_hash=?,cost_usd=?,completed_at=? WHERE id=?").bind(clean(payload.id), auditHash, usage.actualUsd, now(), requestId).run();
  const evidenceRows = [
    ["VQ-M0-FACTUAL-TRACEABILITY", "SOURCE", Number(dimensions.factualSafety) >= 94], ["VQ-M1-SEMANTIC-ALIGNMENT", "PIXELS", Number(dimensions.semanticAlignment) >= 94], ["VQ-M1-MOBILE-LEGIBILITY", "PIXELS", Number(dimensions.mobileLegibility) >= 90],
    ["VQ-M2-PILLAR-TRANSACTION-CHAIN", "MOTION", Number(dimensions.transactionChain) >= 90], ["VQ-M2-PILLAR-FLOW-LEGEND", "MOTION", Number(dimensions.transactionChain) >= 90], ["VQ-M2-SERIES-FOLLOW-THE-FEE", "MOTION", Number(dimensions.transactionChain) >= 90],
    ["VQ-M1-GOLDEN-PLAYBACK", "MOTION", pass],
  ] as const;
  for (const [standardId, kind, status] of evidenceRows) await recordEvidence(env.DB!, ctx, { standardId, state: status ? "PASS" : "FAIL", kind, hash: auditHash, measured: result, findings: Array.isArray(result.findings) ? result.findings : [], actor });
  await env.DB!.prepare("UPDATE v7_golden_sequences SET lifecycle_state=?,quality_json=?,evidence_hash=?,updated_at=? WHERE id=?").bind(pass ? "PASS" : "REPAIR_REQUIRED", json({ ...parseJson<Row>(golden.quality_json, {}), independentAudit: result, providerResponseId: payload.id, usage }), auditHash, now(), golden.id).run();
  await env.DB!.prepare("UPDATE v7_sequential_budget_plans SET actual_spend_usd=(SELECT COALESCE(SUM(cost_usd),0) FROM v7_sequential_provider_requests WHERE queue_id=? AND lifecycle_state IN ('COMPLETED','FAILED')),actual_provider_requests=(SELECT COUNT(*) FROM v7_sequential_provider_requests WHERE queue_id=? AND lifecycle_state IN ('COMPLETED','FAILED')),updated_at=? WHERE id=?").bind(ctx.queue.id, ctx.queue.id, now(), plan.id).run();
  return { outcome: pass ? "GOLDEN_SEQUENCE_PASS" : "REPAIR_REQUIRED", goldenSequenceId: golden.id, result, auditHash, usage };
}

export async function GET(request: Request) {
  try { const env = await runtime(); if (!env.DB || !env.BUCKET) throw new Error("Canonical runtime unavailable"); const url = new URL(request.url), assetId = url.searchParams.get("asset"); if (assetId) { const asset = await first(env.DB, "SELECT * FROM v7_golden_sequence_assets WHERE id=? LIMIT 1", assetId); if (!asset) return new Response("Not found", { status: 404 }); const object = await env.BUCKET.get(clean(asset.storage_key)); if (!object) return new Response("Not found", { status: 404 }); return new Response(await object.arrayBuffer(), { headers: { "content-type": clean(asset.mime_type), "cache-control": "private, max-age=3600", "content-length": clean(asset.byte_size) } }); } const ctx = await context(env.DB), [standards, evidence, golden] = await Promise.all([rows(env.DB, "SELECT id,scope,scope_key,enforcement_level,metric,threshold_or_range,owning_stage,failure_action FROM v7_video_quality_standards WHERE standard_version=? AND active=1 ORDER BY scope,id", VIDEO_QUALITY_STANDARD_VERSION), rows(env.DB, "SELECT standard_id,lifecycle_state,evidence_kind,evidence_hash,measured_value_json,findings_json,created_at FROM v7_video_quality_evidence WHERE queue_id=? AND standard_version=? ORDER BY created_at", ctx.queue.id, VIDEO_QUALITY_STANDARD_VERSION), first(env.DB, "SELECT * FROM v7_golden_sequences WHERE queue_id=? AND standard_version=? ORDER BY revision DESC LIMIT 1", ctx.queue.id, VIDEO_QUALITY_STANDARD_VERSION)]); const assets = golden ? await rows(env.DB, "SELECT id,role,shot_id,temporal_state,mime_type,byte_size,sha256,metadata_json FROM v7_golden_sequence_assets WHERE golden_sequence_id=? ORDER BY shot_id,temporal_state,role", golden.id) : []; return Response.json({ standardVersion: VIDEO_QUALITY_STANDARD_VERSION, standards, evidence, golden: golden ? { id: golden.id, revision: golden.revision, state: golden.lifecycle_state, durationSeconds: golden.duration_seconds, manifest: parseJson(golden.manifest_json, {}), quality: parseJson(golden.quality_json, {}), assets: assets.map((asset) => ({ ...asset, url: `/api/factory/sequential-production/quality?asset=${encodeURIComponent(clean(asset.id))}`, metadata: parseJson(asset.metadata_json, {}) })) } : null }, { headers: NO_STORE }); } catch (error) { return Response.json({ error: { code: "VIDEO_QUALITY_PROJECTION_UNAVAILABLE", message: error instanceof Error ? error.message : "Quality projection unavailable" } }, { status: 503, headers: NO_STORE }); }
}

export async function POST(request: Request) {
  try { const { env, actor } = await authorized(request), body = await request.json().catch(() => null) as Row | null, action = clean(body?.action).toUpperCase(); if (action === "CREATE_GOLDEN_PLAN") return Response.json(await createGoldenPlan(env), { status: 201, headers: NO_STORE }); if (action === "PRODUCE_GOLDEN_VISUALS") return Response.json(await produceGoldenVisuals(env, actor), { status: 201, headers: NO_STORE }); if (action === "PRODUCE_GOLDEN_AUDIO") return Response.json(await produceGoldenAudio(env, actor), { status: 201, headers: NO_STORE }); if (action === "REASSESS_GOLDEN_AUDIO") return Response.json(await reassessGoldenAudio(env, actor), { status: 201, headers: NO_STORE }); if (action === "AUDIT_GOLDEN_SEQUENCE") return Response.json(await auditGolden(env, actor), { status: 201, headers: NO_STORE }); return Response.json({ error: { code: "VIDEO_QUALITY_ACTION_INVALID", message: "Use CREATE_GOLDEN_PLAN, PRODUCE_GOLDEN_VISUALS, PRODUCE_GOLDEN_AUDIO, REASSESS_GOLDEN_AUDIO or AUDIT_GOLDEN_SEQUENCE" } }, { status: 400, headers: NO_STORE }); } catch (error) { if (error instanceof SequentialCommandError) return Response.json({ error: { code: error.code, message: error.message } }, { status: error.status, headers: NO_STORE }); return Response.json({ error: { code: "VIDEO_QUALITY_EXECUTION_FAILED", message: error instanceof Error ? error.message : "Video quality execution failed" } }, { status: 503, headers: NO_STORE }); }
}
