CREATE TABLE `v7_sequence_proofs` (
	`id` text PRIMARY KEY NOT NULL,
	`program_id` text NOT NULL,
	`run_id` text NOT NULL,
	`authorization_id` text NOT NULL,
	`canary_id` text NOT NULL,
	`version` text NOT NULL,
	`status` text NOT NULL,
	`sequence_file_id` text,
	`evidence_id` text,
	`source_manifest_json` text NOT NULL,
	`duration_seconds` real DEFAULT 30 NOT NULL,
	`fps` integer DEFAULT 30 NOT NULL,
	`unit_count` integer DEFAULT 10 NOT NULL,
	`frame_count` integer DEFAULT 30 NOT NULL,
	`score` integer DEFAULT 0 NOT NULL,
	`tier` text DEFAULT 'BLOCKED' NOT NULL,
	`dimensions_json` text DEFAULT '{}' NOT NULL,
	`findings_json` text DEFAULT '[]' NOT NULL,
	`provider_response_id` text,
	`request_id` text,
	`content_hash` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`completed_at` text
);
