CREATE TABLE IF NOT EXISTS `v7_production_batches` (
	`id` text PRIMARY KEY NOT NULL,
	`program_id` text NOT NULL,
	`run_id` text NOT NULL,
	`authorization_id` text NOT NULL,
	`wave_key` text NOT NULL,
	`version` text NOT NULL,
	`engine_version` text NOT NULL,
	`status` text NOT NULL,
	`scope_json` text NOT NULL,
	`specification_hash` text NOT NULL,
	`total_units` integer NOT NULL,
	`completed_units` integer DEFAULT 0 NOT NULL,
	`blocked_units` integer DEFAULT 0 NOT NULL,
	`current_index` integer DEFAULT 0 NOT NULL,
	`audit_sample_json` text DEFAULT '[]' NOT NULL,
	`production_dod_json` text NOT NULL,
	`root_cause_policy_json` text NOT NULL,
	`requests_before` integer NOT NULL,
	`cost_before` real NOT NULL,
	`request_budget` integer NOT NULL,
	`cost_budget` real NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`completed_at` text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `v7_shot_products` (
	`id` text PRIMARY KEY NOT NULL,
	`program_id` text NOT NULL,
	`run_id` text NOT NULL,
	`authorization_id` text NOT NULL,
	`batch_id` text NOT NULL,
	`brief_id` text NOT NULL,
	`logical_brief_id` text NOT NULL,
	`archetype` text NOT NULL,
	`engine_version` text NOT NULL,
	`status` text NOT NULL,
	`specification_json` text NOT NULL,
	`specification_hash` text NOT NULL,
	`frame_ids_json` text NOT NULL,
	`frame_hashes_json` text NOT NULL,
	`measurements_json` text NOT NULL,
	`product_hash` text NOT NULL,
	`supersedes_id` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`completed_at` text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `v7_batch_product_audits` (
	`id` text PRIMARY KEY NOT NULL,
	`program_id` text NOT NULL,
	`run_id` text NOT NULL,
	`authorization_id` text NOT NULL,
	`batch_id` text NOT NULL,
	`rubric_version` text NOT NULL,
	`status` text NOT NULL,
	`score` integer DEFAULT 0 NOT NULL,
	`tier` text DEFAULT 'BLOCKED' NOT NULL,
	`dimensions_json` text DEFAULT '{}' NOT NULL,
	`findings_json` text DEFAULT '[]' NOT NULL,
	`root_cause_json` text DEFAULT '{}' NOT NULL,
	`request_id` text,
	`provider_response_id` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`completed_at` text
);
