import { getChatGPTUser } from "@/app/chatgpt-auth";
import { ChannelStrategyActivationError, parseChannelStrategyActivationBody, submitChannelStrategyActivation, validateChannelStrategyActivationIdempotencyKey } from "@/lib/channel-strategy-activation-command";
import type { NicheGovernanceDB } from "@/lib/niche-governance-command";

export const dynamic = "force-dynamic";
const NO_STORE = { "cache-control": "no-store" };
const MAX_BODY_BYTES = 96_000;
function failure(code: string, message: string, status: number) { return Response.json({ error: { code, message }, fallback: false, providerRequests: 0, spendUsd: 0, aggregateScore: null, systemRankMutation: false, expertPriorityMutation: false, selectionMutation: false, commitmentMutation: false, axisMutation: false, evidenceSufficiencyMutation: false, eligibilityMutation: false, legacyChannelNicheMutation: false, channelStrategyBindingMutation: false, channelStrategyActivation: false }, { status, headers: NO_STORE }); }
async function runtime() { const { env } = await import("cloudflare:workers"); return env as unknown as { DB?: NicheGovernanceDB; FACTORY_EXPERT_EMAILS?: string }; }
async function readBody(request: Request) { const declared = Number(request.headers.get("content-length") || 0); if (declared > MAX_BODY_BYTES) throw new ChannelStrategyActivationError("COMMAND_BODY_TOO_LARGE", 413, "The activation command exceeds 96 KB"); if (!request.body) return ""; const reader = request.body.getReader(); const decoder = new TextDecoder(); let total = 0, result = ""; while (true) { const chunk = await reader.read(); if (chunk.done) break; total += chunk.value.byteLength; if (total > MAX_BODY_BYTES) { await reader.cancel(); throw new ChannelStrategyActivationError("COMMAND_BODY_TOO_LARGE", 413, "The activation command exceeds 96 KB"); } result += decoder.decode(chunk.value, { stream: true }); } return result + decoder.decode(); }

export async function POST(request: Request) {
  try {
    const user = await getChatGPTUser(); if (!user) return failure("SIWC_AUTHENTICATION_REQUIRED", "Sign in with ChatGPT before activating Channel Strategy", 401);
    const env = await runtime(); if (!env.DB) return failure("CANONICAL_DATABASE_UNAVAILABLE", "Canonical database binding is unavailable", 503);
    const allowlist = new Set(String(env.FACTORY_EXPERT_EMAILS || "").split(",").map((email) => email.trim().toLowerCase()).filter(Boolean)); if (!allowlist.size) return failure("EXPERT_ALLOWLIST_UNCONFIGURED", "The server-side governance allowlist is not configured", 503); if (!allowlist.has(user.email.trim().toLowerCase())) return failure("PORTFOLIO_GOVERNANCE_AUTHORIZATION_REQUIRED", "This identity is not authorized to activate Channel Strategy", 403);
    const contentType = request.headers.get("content-type")?.toLowerCase() || "", formRequest = contentType.includes("application/x-www-form-urlencoded") || contentType.includes("multipart/form-data");
    let json: unknown, formKey: string | null = null;
    if (formRequest) { if (Number(request.headers.get("content-length") || 0) > MAX_BODY_BYTES) throw new ChannelStrategyActivationError("COMMAND_BODY_TOO_LARGE", 413, "The activation command exceeds 96 KB"); const form = await request.formData(), value = (name: string) => String(form.get(name) || ""), lines = (name: string) => value(name).split("\n").map((item) => item.trim()).filter(Boolean); formKey = value("idempotencyKey"); json = { action: value("action"), expectedActivationVersion: Number(value("expectedActivationVersion")), expectedChannelStrategyVersion: Number(value("expectedChannelStrategyVersion")), expectedCommitmentVersion: Number(value("expectedCommitmentVersion")), commitmentId: value("commitmentId"), strategy: { owner: value("owner"), rationale: value("rationale"), viewerPromise: value("viewerPromise"), differentiation: value("differentiation"), audienceFocus: value("audienceFocus"), contentBoundaries: lines("contentBoundaries"), successMeasures: lines("successMeasures"), reviewCadenceDays: Number(value("reviewCadenceDays")), commitmentReviewed: value("commitmentReviewed") === "true", activationAcknowledged: value("activationAcknowledged") === "true" } }; }
    else { if (!contentType.includes("application/json")) return failure("JSON_CONTENT_TYPE_REQUIRED", "Content-Type must be application/json", 415); try { json = JSON.parse(await readBody(request)); } catch (error) { if (error instanceof ChannelStrategyActivationError) throw error; return failure("COMMAND_JSON_INVALID", "The request body is not valid JSON", 400); } }
    const body = parseChannelStrategyActivationBody(json);
    const receipt = await submitChannelStrategyActivation(env.DB, { body, actor: { email: user.email, displayName: user.displayName, role: "PORTFOLIO_GOVERNANCE" }, idempotencyKey: validateChannelStrategyActivationIdempotencyKey(formKey || request.headers.get("idempotency-key")), correlationId: request.headers.get("x-correlation-id"), causationId: request.headers.get("x-causation-id") });
    if (formRequest) return Response.redirect(new URL(`/niche-discovery?channel=${encodeURIComponent(receipt.activation.channelId)}&activation=${receipt.outcome.toLowerCase()}`, request.url), 303);
    return Response.json(receipt, { status: receipt.outcome === "RECORDED" ? 201 : 200, headers: NO_STORE });
  } catch (error) { if (error instanceof ChannelStrategyActivationError) return failure(error.code, error.message, error.status); return failure("CHANNEL_STRATEGY_ACTIVATION_UNAVAILABLE", "The Channel Strategy activation command is unavailable", 503); }
}
