import { desc, eq } from "drizzle-orm";
import { getDb } from "../../../../../db";
import { evidenceRecords, videoRenders, workflowEvents } from "../../../../../db/schema";

type RuntimeEnv = { OPENAI_API_KEY?: string; OPENAI_QA_MODEL?: string };
type FrameInput = { shotId: string; title: string; family: string; timestamp: number; intent: string; imageDataUrl: string };
type Finding = { timestamp: number; shotId: string; severity: "P0" | "P1" | "P2"; category: string; observation: string; evidence: string; rootCause: string; repairAction: string; acceptanceTest: string; confidence: number };

const CRITICS = ["Executive producer", "Story & retention", "Visual director", "Semantic alignment", "Sound director", "Audience simulator", "Competitive editor", "Factual & brand safety"];
const SCORE_KEYS = ["story", "semanticFit", "visualQuality", "visualVariety", "pacing", "emphasis", "soundDesign", "competitiveReadiness"];

async function runtimeEnv() { const { env } = await import("cloudflare:workers"); return env as unknown as RuntimeEnv; }
function parse(value: string | null) { try { return value ? JSON.parse(value) as Record<string, unknown> : {}; } catch { return {}; } }
function outputText(payload: Record<string, unknown>) { const direct = payload.output_text; if (typeof direct === "string") return direct; const output = Array.isArray(payload.output) ? payload.output : []; for (const item of output) { const content = item && typeof item === "object" && Array.isArray((item as { content?: unknown[] }).content) ? (item as { content: unknown[] }).content : []; for (const block of content) if (block && typeof block === "object" && typeof (block as { text?: unknown }).text === "string") return String((block as { text: string }).text); } throw new Error("OpenAI returned no structured QA output"); }
async function openaiStructured(name: string, schema: Record<string, unknown>, content: Array<Record<string, unknown>>) {
  const env = await runtimeEnv(); if (!env.OPENAI_API_KEY) throw new Error("Connect OPENAI_API_KEY in Factory Connections before AI Perceptual QA");
  const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { authorization: `Bearer ${env.OPENAI_API_KEY}`, "content-type": "application/json" }, body: JSON.stringify({ model: env.OPENAI_QA_MODEL || "gpt-5.6", reasoning: { effort: "high" }, input: [{ role: "user", content }], text: { format: { type: "json_schema", name, strict: true, schema } } }), signal: AbortSignal.timeout(180000) });
  if (!response.ok) { const detail = await response.text().catch(() => ""); throw new Error(`OpenAI perceptual critic failed (${response.status})${detail ? ` · ${detail.slice(0, 240)}` : ""}`); }
  return JSON.parse(outputText(await response.json() as Record<string, unknown>)) as Record<string, unknown>;
}

const findingSchema = { type: "object", additionalProperties: false, properties: { findings: { type: "array", items: { type: "object", additionalProperties: false, properties: { timestamp: { type: "number" }, shotId: { type: "string" }, severity: { type: "string", enum: ["P0", "P1", "P2"] }, category: { type: "string" }, observation: { type: "string" }, evidence: { type: "string" }, rootCause: { type: "string" }, repairAction: { type: "string" }, acceptanceTest: { type: "string" }, confidence: { type: "integer", minimum: 0, maximum: 100 } }, required: ["timestamp", "shotId", "severity", "category", "observation", "evidence", "rootCause", "repairAction", "acceptanceTest", "confidence"] } }, batchVerdict: { type: "string" } }, required: ["findings", "batchVerdict"] };
const finalSchema = { type: "object", additionalProperties: false, properties: { decision: { type: "string", enum: ["PASS", "REPAIR_REQUIRED", "BLOCKED"] }, overallScore: { type: "integer", minimum: 0, maximum: 100 }, scores: { type: "object", additionalProperties: false, properties: Object.fromEntries(SCORE_KEYS.map((key) => [key, { type: "integer", minimum: 0, maximum: 100 }])), required: SCORE_KEYS }, criticConsensus: { type: "array", items: { type: "object", additionalProperties: false, properties: { critic: { type: "string" }, score: { type: "integer", minimum: 0, maximum: 100 }, verdict: { type: "string" }, decisiveFinding: { type: "string" } }, required: ["critic", "score", "verdict", "decisiveFinding"] } }, systemicDiagnosis: { type: "string" }, repairOrder: { type: "array", items: { type: "string" } }, releaseRationale: { type: "string" } }, required: ["decision", "overallScore", "scores", "criticConsensus", "systemicDiagnosis", "repairOrder", "releaseRationale"] };

async function qaSnapshot(projectId: string) {
  const db = await getDb(); const [runs, renders, records] = await Promise.all([db.select().from(evidenceRecords).where(eq(evidenceRecords.projectId, projectId)), db.select().from(videoRenders).where(eq(videoRenders.projectId, projectId)).orderBy(desc(videoRenders.version)), db.select().from(evidenceRecords).where(eq(evidenceRecords.projectId, projectId))]);
  const latestRun = runs.filter((row) => row.entityType === "PERCEPTUAL_QA_RUN").sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))[0]; const latestRender = renders.find((render) => render.id.includes("V5-MASTER")) || null;
  const shots = records.filter((row) => row.entityType === "SHOT" && Number(parse(row.settingsJson).productionExpansionVersion) === 51).map((row) => { const settings = parse(row.settingsJson); return { id: row.id, title: row.title, startSeconds: Number(settings.startSeconds || 0), endSeconds: Number(settings.endSeconds || 0), family: String(settings.primaryFamily || "UNKNOWN"), intent: String(settings.exactClaim || settings.visualIntent || row.title) }; }).sort((a, b) => a.startSeconds - b.startSeconds);
  const settings = latestRun ? parse(latestRun.settingsJson) : null; const env = await runtimeEnv();
  return { policy: { mode: "MAXIMUM_QUALITY", costOptimization: "DEFERRED", frameCoverage: "THREE_TEMPORAL_SAMPLES_PER_EDITORIAL_SHOT", criticCount: CRITICS.length, autoPassFloor: 90, dimensionFloor: 86, p0Tolerance: 0 }, provider: { connected: Boolean(env.OPENAI_API_KEY), model: env.OPENAI_QA_MODEL || "gpt-5.6" }, render: latestRender ? { id: latestRender.id, version: latestRender.version, status: latestRender.status, durationSeconds: latestRender.durationSeconds, videoUrl: `/api/projects/${projectId}/render?video=${encodeURIComponent(latestRender.id)}` } : null, shots, latestRun: latestRun ? { id: latestRun.id, status: latestRun.lifecycleState, ...settings } : null };
}

export async function GET(_: Request, context: { params: Promise<{ id: string }> }) { try { const { id } = await context.params; return Response.json(await qaSnapshot(id)); } catch (error) { console.error("Perceptual QA GET failed", error); return Response.json({ error: "AI Perceptual QA could not load" }, { status: 500 }); } }

export async function POST(request: Request, context: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await context.params; const body = await request.json() as { action?: string; runId?: string; frames?: FrameInput[]; audioMetrics?: Record<string, unknown> }; const db = await getDb();
    if (body.action === "START_RUN") { const env = await runtimeEnv(); if (!env.OPENAI_API_KEY) return Response.json({ error: "OPENAI_API_KEY_REQUIRED" }, { status: 424 }); const snap = await qaSnapshot(id); if (!snap.render || snap.shots.length < 1) return Response.json({ error: "A stored V5 master and frozen shot contract are required" }, { status: 409 }); const runId = `${id}-PQA-${Date.now()}`; const settings = { role: "AI_PERCEPTUAL_QA_RUN", renderId: snap.render.id, mode: "MAXIMUM_QUALITY", costOptimization: "DEFERRED", phase: "CAPTURING", framesExpected: snap.shots.length * 3, framesAnalyzed: 0, batches: [], findings: [], startedAt: new Date().toISOString() }; await db.insert(evidenceRecords).values({ id: runId, projectId: id, entityType: "PERCEPTUAL_QA_RUN", pipelineVersion: 5, lifecycleState: "PLAN", title: `AI Perceptual QA · ${snap.render.id}`, provider: "OpenAI Responses Vision", modelId: env.OPENAI_QA_MODEL || "gpt-5.6", settingsJson: JSON.stringify(settings), licenseStatus: "INTERNAL_QA_EVIDENCE", commercialUseStatus: "ALLOWED", revalidationStatus: "IN_PROGRESS", updatedAt: new Date().toISOString() }); return Response.json({ ok: true, runId, snapshot: await qaSnapshot(id) }); }
    const runId = String(body.runId || ""); const run = (await db.select().from(evidenceRecords).where(eq(evidenceRecords.id, runId)).limit(1))[0]; if (!run || run.projectId !== id || run.entityType !== "PERCEPTUAL_QA_RUN") return Response.json({ error: "Perceptual QA run not found" }, { status: 404 }); const state = parse(run.settingsJson);
    if (body.action === "ANALYZE_BATCH") { const frames = body.frames || []; if (!frames.length || frames.length > 12) return Response.json({ error: "Each vision batch must contain 1–12 frames" }, { status: 400 }); const frameContext = frames.map(({ imageDataUrl: _, ...frame }) => frame); const content: Array<Record<string, unknown>> = [{ type: "input_text", text: `You are an adversarial YouTube documentary quality panel. Evaluate these consecutive master-video frames against their timecodes, shot intent and narration meaning. Judge what a demanding human executive producer actually sees, not metadata or production claims. Detect semantic mismatch, generic or meaningless AI imagery, repetition, poor crop/aspect fit, illegible diagrams, weak composition, insufficient visual change, missing emphasis and confusing continuity. Never pass polish that is only decorative. Return only concrete timecoded defects that merit repair; use P0 for release-blocking, P1 for clearly below competitive quality, P2 for material polish. Frame contract: ${JSON.stringify(frameContext)}` }, ...frames.map((frame) => ({ type: "input_image", image_url: frame.imageDataUrl, detail: "high" }))]; const result = await openaiStructured("perceptual_frame_findings", findingSchema, content); const previousBatches = Array.isArray(state.batches) ? state.batches : []; const previousFindings = Array.isArray(state.findings) ? state.findings : []; const nextFindings = [...previousFindings, ...(Array.isArray(result.findings) ? result.findings : [])]; const next = { ...state, phase: "VISION_ANALYSIS", framesAnalyzed: Number(state.framesAnalyzed || 0) + frames.length, batches: [...previousBatches, { shots: frameContext.map((frame) => frame.shotId), verdict: result.batchVerdict, analyzedAt: new Date().toISOString() }], findings: nextFindings }; await db.update(evidenceRecords).set({ lifecycleState: "FETCHED", settingsJson: JSON.stringify(next), updatedAt: new Date().toISOString() }).where(eq(evidenceRecords.id, runId)); return Response.json({ ok: true, framesAnalyzed: next.framesAnalyzed, findings: result.findings || [] }); }
    if (body.action === "FINALIZE_RUN") { const findings = (Array.isArray(state.findings) ? state.findings : []) as Finding[]; const audio = body.audioMetrics || {}; const content: Array<Record<string, unknown>> = [{ type: "input_text", text: `Act as an independent adjudicator for a premium US YouTube explainer documentary. Eight critics must reach a defensible consensus: ${CRITICS.join(", ")}. This phase is MAXIMUM QUALITY; cost must not reduce coverage, critic depth, repair scope or thresholds. Use the timecoded visual findings and measured audio evidence below. PASS is allowed only with zero P0, no unresolved material P1, overall >=90 and every score >=86. A technically valid file is not a quality pass. Diagnose systemic root causes, order repairs by viewer impact, and be strict about generic/repeated visuals, semantic mismatch, crop/legibility, weak emphasis, absent music/ambience/SFX, and monotony. Findings: ${JSON.stringify(findings)} Audio evidence: ${JSON.stringify(audio)}` }]; const result = await openaiStructured("perceptual_master_verdict", finalSchema, content); const scores = result.scores && typeof result.scores === "object" ? result.scores as Record<string, number> : {}; const hasP0 = findings.some((item) => item.severity === "P0"); const materialP1 = findings.filter((item) => item.severity === "P1" && item.confidence >= 75).length; const floor = Math.min(...SCORE_KEYS.map((key) => Number(scores[key] || 0))); const declared = String(result.decision || "BLOCKED"); const decision = !hasP0 && materialP1 === 0 && Number(result.overallScore || 0) >= 90 && floor >= 86 && declared === "PASS" ? "PASS" : "REPAIR_REQUIRED"; const final = { ...state, phase: "COMPLETE", decision, overallScore: Number(result.overallScore || 0), scores, criticConsensus: result.criticConsensus, systemicDiagnosis: result.systemicDiagnosis, repairOrder: result.repairOrder, releaseRationale: result.releaseRationale, audioMetrics: audio, p0Count: findings.filter((item) => item.severity === "P0").length, p1Count: findings.filter((item) => item.severity === "P1").length, completedAt: new Date().toISOString() }; await db.update(evidenceRecords).set({ lifecycleState: decision === "PASS" ? "AUDITED" : "VERIFIED", settingsJson: JSON.stringify(final), semanticScore: Number(result.overallScore || 0), revalidationStatus: decision === "PASS" ? "CURRENT" : "REPAIR_REQUIRED", updatedAt: new Date().toISOString() }).where(eq(evidenceRecords.id, runId)); await db.insert(workflowEvents).values({ projectId: id, toStatus: decision === "PASS" ? "AI_PERCEPTUAL_QA_PASSED" : "AI_PERCEPTUAL_REPAIR_REQUIRED", eventType: `AI_PERCEPTUAL_QA_${decision}`, summary: `${CRITICS.length}-critic AI master review ${decision.toLowerCase().replaceAll("_", " ")} · ${Number(result.overallScore || 0)}/100 · ${findings.length} timecoded findings` }); return Response.json({ ok: true, decision, result: final }); }
    return Response.json({ error: "Unknown AI Perceptual QA action" }, { status: 400 });
  } catch (error) { console.error("Perceptual QA POST failed", error); return Response.json({ error: error instanceof Error ? error.message : "AI Perceptual QA stopped safely" }, { status: 500 }); }
}
