import type { AutomationMode, ContentAutopilotReceipt } from "@/app/content-planning-contract";

export const CONTENT_AUTOPILOT_COMMAND_VERSION = "CONTENT_AUTOPILOT_COMMAND_V1" as const;
type Row = Record<string, unknown>;
type D1Result = { meta?: { changes?: number } };
type Statement = { bind: (...values: unknown[]) => Statement; all: <T>() => Promise<{ results?: T[] }>; run: () => Promise<D1Result> };
export type ContentAutopilotDB = { prepare: (query: string) => Statement; batch: (statements: Statement[]) => Promise<D1Result[]> };
export type ContentAutopilotActor = { email: string; displayName: string; role: "CHANNEL_OWNER" | "PORTFOLIO_GOVERNANCE" };

type PolicyInput = { mode: AutomationMode; dailyBudgetUsd: number; monthlyBudgetUsd: number; perVideoCostCeilingUsd: number; cadencePerMonth: number; repairLimit: number; riskTolerance: "LOW" | "MEDIUM" | "HIGH"; autoProduction: boolean; autoPublish: boolean; escalationRules: string[] };
type CommandBody = { action: ContentAutopilotReceipt["action"]; channelId: string; expectedPolicyVersion: number; expectedRunVersion: number; policy?: PolicyInput };
type Command = { body: CommandBody; actor: ContentAutopilotActor; idempotencyKey: string };

export class ContentAutopilotError extends Error { constructor(public readonly code: string, public readonly status: number, message: string) { super(message); this.name = "ContentAutopilotError"; } }
function clean(value: unknown) { return String(value ?? "").trim(); }
function object(value: unknown, field: string) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new ContentAutopilotError("COMMAND_VALIDATION_FAILED", 400, `${field} must be an object`); return value as Row; }
function text(value: unknown, field: string, min = 1, max = 1000) { const result = clean(value); if (result.length < min || result.length > max) throw new ContentAutopilotError("COMMAND_VALIDATION_FAILED", 400, `${field} must contain ${min}-${max} characters`); return result; }
function integer(value: unknown, field: string, min: number, max: number) { const result = Number(value); if (!Number.isInteger(result) || result < min || result > max) throw new ContentAutopilotError("COMMAND_VALIDATION_FAILED", 400, `${field} must be an integer between ${min} and ${max}`); return result; }
function money(value: unknown, field: string, min: number, max: number) { const result = Number(value); if (!Number.isFinite(result) || result < min || result > max) throw new ContentAutopilotError("COMMAND_VALIDATION_FAILED", 400, `${field} must be between ${min} and ${max}`); return Math.round(result * 100) / 100; }
function bool(value: unknown, field: string) { if (typeof value !== "boolean") throw new ContentAutopilotError("COMMAND_VALIDATION_FAILED", 400, `${field} must be boolean`); return value; }
function lines(value: unknown, field: string) { if (!Array.isArray(value) || value.length < 1 || value.length > 20) throw new ContentAutopilotError("COMMAND_VALIDATION_FAILED", 400, `${field} must contain 1-20 items`); const result = value.map((item, index) => text(item, `${field}[${index}]`, 5, 500)); if (new Set(result).size !== result.length) throw new ContentAutopilotError("COMMAND_VALIDATION_FAILED", 400, `${field} must not contain duplicates`); return result; }
async function first(db: ContentAutopilotDB, query: string, ...values: unknown[]) { return ((await db.prepare(query).bind(...values).all<Row>()).results || [])[0] || null; }
async function sha256(value: string) { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
function json(value: unknown) { return JSON.stringify(value); }
function parseJson<T>(value: unknown, fallback: T): T { try { return JSON.parse(clean(value)) as T; } catch { return fallback; } }

export function parseContentAutopilotBody(value: unknown): CommandBody {
  const row = object(value, "command"), action = clean(row.action).toUpperCase() as CommandBody["action"];
  if (!["CONFIGURE_AUTOMATION_POLICY", "RUN_CONTENT_AUTOPILOT", "PAUSE_AUTOPILOT", "RESUME_AUTOPILOT", "EMERGENCY_STOP"].includes(action)) throw new ContentAutopilotError("COMMAND_VALIDATION_FAILED", 400, "Unsupported content autopilot action");
  const body: CommandBody = { action, channelId: text(row.channelId, "channelId", 3, 256), expectedPolicyVersion: integer(row.expectedPolicyVersion, "expectedPolicyVersion", 0, Number.MAX_SAFE_INTEGER), expectedRunVersion: integer(row.expectedRunVersion ?? 0, "expectedRunVersion", 0, Number.MAX_SAFE_INTEGER) };
  if (action === "CONFIGURE_AUTOMATION_POLICY") {
    const policy = object(row.policy, "policy"), mode = clean(policy.mode).toUpperCase() as AutomationMode, riskTolerance = clean(policy.riskTolerance).toUpperCase() as PolicyInput["riskTolerance"];
    if (!["FULL_AUTOPILOT", "EXCEPTIONS_ONLY", "EXPERT_REVIEW"].includes(mode)) throw new ContentAutopilotError("COMMAND_VALIDATION_FAILED", 400, "policy.mode is invalid");
    if (!["LOW", "MEDIUM", "HIGH"].includes(riskTolerance)) throw new ContentAutopilotError("COMMAND_VALIDATION_FAILED", 400, "policy.riskTolerance is invalid");
    body.policy = { mode, dailyBudgetUsd: money(policy.dailyBudgetUsd, "policy.dailyBudgetUsd", 0, 100000), monthlyBudgetUsd: money(policy.monthlyBudgetUsd, "policy.monthlyBudgetUsd", 0, 1000000), perVideoCostCeilingUsd: money(policy.perVideoCostCeilingUsd, "policy.perVideoCostCeilingUsd", 0, 100000), cadencePerMonth: integer(policy.cadencePerMonth, "policy.cadencePerMonth", 1, 60), repairLimit: integer(policy.repairLimit, "policy.repairLimit", 0, 4), riskTolerance, autoProduction: bool(policy.autoProduction, "policy.autoProduction"), autoPublish: bool(policy.autoPublish, "policy.autoPublish"), escalationRules: lines(policy.escalationRules, "policy.escalationRules") };
    if (body.policy.autoPublish && !body.policy.autoProduction) throw new ContentAutopilotError("COMMAND_VALIDATION_FAILED", 400, "Auto-publish requires auto-production authority");
  }
  return body;
}
export function validateContentAutopilotIdempotencyKey(value: unknown) { const key = text(value, "Idempotency-Key", 12, 200); if (!/^[A-Za-z0-9._:-]+$/.test(key)) throw new ContentAutopilotError("COMMAND_VALIDATION_FAILED", 400, "Idempotency-Key contains unsupported characters"); return key; }

function receipt(action: CommandBody["action"], channelId: string, policyVersion: number, runVersion: number, state: string, actor: string, replay: boolean): ContentAutopilotReceipt {
  return { contract: CONTENT_AUTOPILOT_COMMAND_VERSION, outcome: replay ? "IDEMPOTENT_REPLAY" : "RECORDED", action, channelId, policyVersion, runVersion, state, authority: { actor, systemActor: "SYSTEM_AUTOPILOT", providerRequests: 0, spendUsd: 0, channelStrategyMutation: false, providerDispatch: false, productionMutation: false, publishingMutation: false } };
}

async function activeStrategy(db: ContentAutopilotDB, channelId: string) {
  const strategy = await first(db, "SELECT * FROM channel_strategy_activations WHERE channel_id=? ORDER BY channel_strategy_version DESC LIMIT 1", channelId);
  if (!strategy || clean(strategy.lifecycle_state) !== "ACTIVATED") throw new ContentAutopilotError("ACTIVE_CHANNEL_STRATEGY_REQUIRED", 409, "Content planning requires an active Channel Strategy");
  return strategy;
}

function policyFromRow(row: Row): PolicyInput { return { mode: clean(row.mode) as AutomationMode, dailyBudgetUsd: Number(row.daily_budget_usd), monthlyBudgetUsd: Number(row.monthly_budget_usd), perVideoCostCeilingUsd: Number(row.per_video_cost_ceiling_usd), cadencePerMonth: Number(row.cadence_per_month), repairLimit: Number(row.repair_limit), riskTolerance: clean(row.risk_tolerance) as PolicyInput["riskTolerance"], autoProduction: Boolean(row.auto_production), autoPublish: Boolean(row.auto_publish), escalationRules: parseJson<string[]>(row.escalation_rules_json, []) }; }

async function recordPolicy(db: ContentAutopilotDB, command: Command, requestHash: string, idempotencyKey: string) {
  const body = command.body, strategy = await activeStrategy(db, body.channelId), latest = await first(db, "SELECT * FROM content_automation_policies WHERE channel_id=? ORDER BY policy_version DESC LIMIT 1", body.channelId);
  if (Number(latest?.policy_version || 0) !== body.expectedPolicyVersion) throw new ContentAutopilotError("POLICY_VERSION_CONFLICT", 409, "A newer automation policy exists; reload before submitting");
  let policy = body.policy, lifecycleState = "ACTIVE";
  if (body.action !== "CONFIGURE_AUTOMATION_POLICY") {
    if (!latest) throw new ContentAutopilotError("AUTOMATION_POLICY_REQUIRED", 409, "Configure an automation policy first");
    policy = policyFromRow(latest);
    lifecycleState = body.action === "PAUSE_AUTOPILOT" ? "PAUSED" : body.action === "EMERGENCY_STOP" ? "EMERGENCY_STOPPED" : "ACTIVE";
  }
  if (!policy) throw new ContentAutopilotError("AUTOMATION_POLICY_REQUIRED", 409, "Configure an automation policy first");
  const policyVersion = body.expectedPolicyVersion + 1, id = `content-policy:${body.channelId}:v${policyVersion}`, now = new Date().toISOString(), actorEmail = clean(command.actor.email).toLowerCase();
  await db.batch([
    db.prepare("INSERT INTO content_automation_policies (id,channel_id,policy_version,strategy_activation_id,strategy_version,mode,lifecycle_state,daily_budget_usd,monthly_budget_usd,per_video_cost_ceiling_usd,cadence_per_month,repair_limit,risk_tolerance,auto_production,auto_publish,escalation_rules_json,actor_email,actor_display_name,actor_role,idempotency_key,request_hash,supersedes_policy_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id, body.channelId, policyVersion, clean(strategy.id), Number(strategy.channel_strategy_version), policy.mode, lifecycleState, policy.dailyBudgetUsd, policy.monthlyBudgetUsd, policy.perVideoCostCeilingUsd, policy.cadencePerMonth, policy.repairLimit, policy.riskTolerance, policy.autoProduction, policy.autoPublish, json(policy.escalationRules), actorEmail, command.actor.displayName, command.actor.role, idempotencyKey, requestHash, clean(latest?.id) || null, now),
    db.prepare("INSERT INTO content_planning_audits (id,channel_id,entity_type,entity_id,event_type,actor_type,actor_email,policy_version,strategy_version,idempotency_key,request_hash,detail_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(`${id}:audit`, body.channelId, "AUTOMATION_POLICY", id, body.action, "OWNER_EXPERT", actorEmail, policyVersion, Number(strategy.channel_strategy_version), idempotencyKey, requestHash, json({ mode: policy.mode, lifecycleState, authority: "PLANNING_ONLY" }), now),
  ]);
  return receipt(body.action, body.channelId, policyVersion, Number((await first(db, "SELECT run_version FROM content_planning_runs WHERE channel_id=? ORDER BY run_version DESC LIMIT 1", body.channelId))?.run_version || 0), lifecycleState, command.actor.displayName, false);
}

type PillarSeed = { title: string; purpose: string; audienceNeed: string; differentiation: string; evidenceRequirement: string; winningCriteria: string[]; series: Array<{ title: string; format: string; promise: string; weight: number }> };
type OpportunitySeed = { title: string; audienceProblem: string; question: string; series: number; axes: [number, number, number, number]; complexity: "LOW" | "MEDIUM" | "HIGH"; evidence: string[]; rationale: string };
const PILLARS: PillarSeed[] = [
  { title: "Everyday Transaction Tollbooths", purpose: "Reveal how ordinary purchases route fees, data, rewards and risk through payment institutions.", audienceNeed: "Understand where each dollar goes and why visible rewards coexist with hidden funding flows.", differentiation: "Transaction-led institutional reconstruction rather than merchant tutorials or personal-finance advice.", evidenceRequirement: "Primary payment-rail, interchange and consumer-cost sources with dated scope qualifications.", winningCriteria: ["Trace one transaction end to end", "Separate issuer, acquirer, network, processor and merchant roles"], series: [{ title: "Follow the Fee", format: "Cinematic system documentary", promise: "Follow one purchase through every institutional handoff.", weight: 2 }, { title: "The Rails Under It", format: "Mechanism explainer", promise: "Map the infrastructure beneath a familiar payment action.", weight: 1 }] },
  { title: "Invisible Price Architecture", purpose: "Expose defaults, sequencing, personalization and cancellation mechanics embedded in prices.", audienceNeed: "Recognize why a quoted price changes and which design choices shape the final amount.", differentiation: "Evidence-led price-system maps that avoid single-company outrage.", evidenceRequirement: "Primary regulatory, academic or audited pricing evidence plus counterexamples.", winningCriteria: ["Show a concrete unit economic chain", "Distinguish documented mechanism from inference"], series: [{ title: "Receipt X-Ray", format: "Visual unit-economics investigation", promise: "Turn one bill into a map of hidden price components.", weight: 2 }, { title: "Default by Design", format: "Behavioral-system documentary", promise: "Reveal how defaults and interfaces change outcomes.", weight: 1 }] },
  { title: "Risk and Reputation Machines", purpose: "Explain how records become scores, approvals, disputes and institutional decisions.", audienceNeed: "See which data and decision engines evaluate consumers and how fragmented events become connected.", differentiation: "Machinery-centered dossiers instead of score-improvement advice.", evidenceRequirement: "Primary consumer-reporting, regulator and market-structure evidence with jurisdiction boundaries.", winningCriteria: ["Separate data furnishing, matching, scoring and action", "Keep individual remedies outside scope"], series: [{ title: "Who Decides?", format: "Decision-pipeline documentary", promise: "Trace a record until it becomes an institutional decision.", weight: 1 }, { title: "The Dispute Machine", format: "Process reconstruction", promise: "Map how a disputed record moves between institutions.", weight: 1 }] },
  { title: "Defaults, Friction and Forgotten Value", purpose: "Map the slow systems that retain money, transfer losses or shape outcomes without an active choice.", audienceNeed: "Understand why recovery is slow and where responsibility changes hands.", differentiation: "Procedural reconstructions spanning institutions rather than seasonal victim stories.", evidenceRequirement: "Primary fraud, unclaimed-property, housing and retirement-system evidence.", winningCriteria: ["Show responsibility at every stage", "Keep uncertainty and recovery limits visible"], series: [{ title: "Vanishing Balance", format: "Recovery-chain investigation", promise: "Trace money that appears to disappear and identify each recovery boundary.", weight: 1 }, { title: "Household Infrastructure", format: "Long-horizon system map", promise: "Connect separate household bills to the institutional stack behind them.", weight: 1 }] },
];
const OPPORTUNITIES: OpportunitySeed[] = [
  { title: "What Really Happens to a $100 Card Purchase?", audienceProblem: "Rewards and fees are visible, but the institutional pass-through is not.", question: "How does one card purchase split across merchant, acquirer, network, issuer and rewards?", series: 0, axes: [98, 96, 96, 95], complexity: "MEDIUM", evidence: ["S05", "S06", "S10", "S11", "S12"], rationale: "A familiar transaction, strong primary evidence and concrete unit economics create the clearest first episode." },
  { title: "Why the Price Changes Between Search and Checkout", audienceProblem: "Consumers cannot see which pricing layer changed the final amount.", question: "Which sequencing, data and fee mechanisms transform an advertised price into the checkout total?", series: 2, axes: [96, 94, 93, 92], complexity: "MEDIUM", evidence: ["S05", "S08", "S09", "S24"], rationale: "High-frequency tension and a repeatable visual price stack fit the active strategy." },
  { title: "The Hidden Economics of Credit-Card Rewards", audienceProblem: "Rewards feel individualized while funding sources remain indirect and embedded.", question: "Who funds card rewards, who captures value and when are pass-through claims unsafe?", series: 0, axes: [95, 94, 95, 94], complexity: "HIGH", evidence: ["S06", "S10", "S11", "S12"], rationale: "Strong tension and differentiation, with explicit qualification controls for pass-through variation." },
  { title: "Inside a Chargeback: Who Holds the Loss?", audienceProblem: "Instant payment and slow dispute systems create uncertainty about responsibility.", question: "How does a chargeback move evidence, provisional credit, liability and loss across institutions?", series: 1, axes: [94, 93, 91, 90], complexity: "HIGH", evidence: ["S05", "S07", "S15"], rationale: "A procedural investigation directly supports the channel's transaction-led promise." },
  { title: "The Files That Quietly Decide Your Financial Life", audienceProblem: "Consumers are evaluated by more than the three nationwide credit bureaus.", question: "How do specialty reports become eligibility, pricing and fraud decisions?", series: 4, axes: [93, 91, 94, 93], complexity: "MEDIUM", evidence: ["S13", "S14", "S15"], rationale: "Primary directories and studies support a defensible decision-machine episode." },
  { title: "Why Subscription Cancellation Is Designed as a Maze", audienceProblem: "Recurring charges and cancellation friction make price comparison and exit costly.", question: "Which interface, billing and retention systems turn cancellation into a multi-stage process?", series: 3, axes: [92, 90, 89, 88], complexity: "LOW", evidence: ["S08", "S09", "S24"], rationale: "Strong consumer familiarity and low production complexity make this an efficient early release." },
  { title: "Where Unused Gift-Card Money Goes", audienceProblem: "Unused stored value appears forgotten, but accounting and escheat systems retain ownership rules.", question: "How does unused stored value become breakage, liability or unclaimed property?", series: 6, axes: [89, 91, 90, 87], complexity: "MEDIUM", evidence: ["S05", "S07", "S09"], rationale: "A concrete money trail exploits a clear procedural coverage gap." },
  { title: "The Retirement Plan Decisions Made Before You Arrive", audienceProblem: "Default funds, fees and recordkeepers shape outcomes before employees make an active choice.", question: "Which institutions and defaults govern workplace retirement money after payroll?", series: 7, axes: [88, 89, 92, 91], complexity: "HIGH", evidence: ["S18", "S19", "S20"], rationale: "High evidence confidence and durable relevance diversify the first 30-day plan." },
];

async function runAutopilot(db: ContentAutopilotDB, command: Command, requestHash: string, idempotencyKey: string) {
  const body = command.body, strategy = await activeStrategy(db, body.channelId), policyRow = await first(db, "SELECT * FROM content_automation_policies WHERE channel_id=? ORDER BY policy_version DESC LIMIT 1", body.channelId);
  if (!policyRow) throw new ContentAutopilotError("AUTOMATION_POLICY_REQUIRED", 409, "Configure an automation policy first");
  if (Number(policyRow.policy_version) !== body.expectedPolicyVersion) throw new ContentAutopilotError("POLICY_VERSION_CONFLICT", 409, "The requested policy is no longer active");
  if (clean(policyRow.lifecycle_state) !== "ACTIVE") throw new ContentAutopilotError("AUTOPILOT_NOT_ACTIVE", 409, "Resume the automation policy before running Autopilot");
  if (clean(policyRow.strategy_activation_id) !== clean(strategy.id) || Number(policyRow.strategy_version) !== Number(strategy.channel_strategy_version)) throw new ContentAutopilotError("AUTOMATION_POLICY_STALE", 409, "The automation policy is stale against Channel Strategy");
  const latestRun = await first(db, "SELECT * FROM content_planning_runs WHERE channel_id=? ORDER BY run_version DESC LIMIT 1", body.channelId);
  if (Number(latestRun?.run_version || 0) !== body.expectedRunVersion) throw new ContentAutopilotError("RUN_VERSION_CONFLICT", 409, "A newer content planning run exists; reload before submitting");
  const policy = policyFromRow(policyRow), runVersion = body.expectedRunVersion + 1, planVersion = runVersion, runId = `content-run:${body.channelId}:v${runVersion}`, planId = `${runId}:plan`, now = new Date().toISOString();
  const statements: Statement[] = [];
  const pillarIds = PILLARS.map((_, index) => `${runId}:pillar:${index + 1}`), seriesSeeds = PILLARS.flatMap((pillar, pillarIndex) => pillar.series.map((series) => ({ ...series, pillarIndex }))), seriesIds = seriesSeeds.map((_, index) => `${runId}:series:${index + 1}`), opportunityIds = OPPORTUNITIES.map((_, index) => `${runId}:opportunity:${index + 1}`);
  const runSnapshot = { mode: policy.mode, lifecycleState: clean(policyRow.lifecycle_state), budgets: { daily: policy.dailyBudgetUsd, monthly: policy.monthlyBudgetUsd, perVideo: policy.perVideoCostCeilingUsd }, cadencePerMonth: policy.cadencePerMonth, repairLimit: policy.repairLimit, riskTolerance: policy.riskTolerance, autoProduction: policy.autoProduction, autoPublish: policy.autoPublish, escalationRules: policy.escalationRules };
  statements.push(db.prepare("INSERT INTO content_planning_runs (id,channel_id,run_version,policy_id,policy_version,strategy_activation_id,strategy_version,lifecycle_state,horizon_days,pillar_count,series_count,opportunity_count,plan_item_count,brief_count,exception_count,provider_requests,spend_usd,actor_type,policy_snapshot_json,idempotency_key,request_hash,created_at) VALUES (?,?,?,?,?,?,?,'COMPLETE',30,?,?,?,?,?,0,0,0,'SYSTEM_AUTOPILOT',?,?,?,?)").bind(runId, body.channelId, runVersion, clean(policyRow.id), Number(policyRow.policy_version), clean(strategy.id), Number(strategy.channel_strategy_version), PILLARS.length, seriesSeeds.length, OPPORTUNITIES.length, OPPORTUNITIES.length, OPPORTUNITIES.length, json(runSnapshot), idempotencyKey, requestHash, now));
  for (let index = 0; index < PILLARS.length; index += 1) { const seed = PILLARS[index], contentHash = await sha256(json(seed)); statements.push(db.prepare("INSERT INTO content_pillars (id,run_id,channel_id,position,title,purpose,audience_need,differentiation,evidence_requirement,winning_criteria_json,lifecycle_state,content_hash,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,'ACTIVE',?,?)").bind(pillarIds[index], runId, body.channelId, index + 1, seed.title, seed.purpose, seed.audienceNeed, seed.differentiation, seed.evidenceRequirement, json(seed.winningCriteria), contentHash, now)); }
  for (let index = 0; index < seriesSeeds.length; index += 1) { const seed = seriesSeeds[index], contentHash = await sha256(json(seed)); statements.push(db.prepare("INSERT INTO content_series (id,run_id,pillar_id,channel_id,position,title,format,repeatable_promise,cadence_weight,lifecycle_state,content_hash,created_at) VALUES (?,?,?,?,?,?,?,?,?,'ACTIVE',?,?)").bind(seriesIds[index], runId, pillarIds[seed.pillarIndex], body.channelId, index + 1, seed.title, seed.format, seed.promise, seed.weight, contentHash, now)); }
  for (let index = 0; index < OPPORTUNITIES.length; index += 1) { const seed = OPPORTUNITIES[index], contentHash = await sha256(json(seed)); statements.push(db.prepare("INSERT INTO content_opportunities (id,run_id,series_id,channel_id,system_rank,title,audience_problem,core_question,evidence_refs_json,strategy_fit,audience_demand,differentiation,evidence_readiness,production_complexity,estimated_cost_usd,lifecycle_state,rationale,content_hash,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'PRIORITIZED',?,?,?)").bind(opportunityIds[index], runId, seriesIds[seed.series], body.channelId, index + 1, seed.title, seed.audienceProblem, seed.question, json(seed.evidence), seed.axes[0], seed.axes[1], seed.axes[2], seed.axes[3], seed.complexity, Math.min(policy.perVideoCostCeilingUsd, seed.complexity === "HIGH" ? 25 : seed.complexity === "MEDIUM" ? 18 : 12), seed.rationale, contentHash, now)); }
  const planRationale = "SYSTEM_AUTOPILOT balances the active strategy across four pillars, sequences the strongest evidence-ready opportunity first and keeps every independent decision axis visible.";
  statements.push(db.prepare("INSERT INTO editorial_plans (id,run_id,channel_id,plan_version,horizon_days,cadence_per_month,lifecycle_state,rationale,content_hash,created_at) VALUES (?,?,?,?,30,?,'AUTO_APPROVED',?,?,?)").bind(planId, runId, body.channelId, planVersion, policy.cadencePerMonth, planRationale, await sha256(planRationale), now));
  for (let index = 0; index < OPPORTUNITIES.length; index += 1) {
    const seed = OPPORTUNITIES[index], itemId = `${planId}:item:${index + 1}`, briefId = `${runId}:brief:${index + 1}`, offset = Math.min(29, Math.round(index * (30 / Math.max(1, OPPORTUNITIES.length))));
    statements.push(db.prepare("INSERT INTO editorial_plan_items (id,plan_id,opportunity_id,sequence,publish_offset_days,lifecycle_state,created_at) VALUES (?,?,?,?,?,'PLANNED',?)").bind(itemId, planId, opportunityIds[index], index + 1, offset, now));
    const narrative = ["Familiar transaction or decision", "Institutional handoff map", "Concrete unit economics or data flow", "Counterevidence and scope boundary", "Durable viewer mental model"], claims = [`The episode must answer: ${seed.question}`, "Every material mechanism must bind dated evidence and preserve uncertainty."], evidenceRequirements = seed.evidence.map((ref) => `Canonical Intelligence evidence ${ref}`), visuals = ["Transaction or decision flow map", "Institution role separation", "Before/after unit economics", "Evidence qualification card"], risks = parseJson<string[]>(strategy.content_boundaries_json, []).concat(["No personalized financial advice", "No unsupported company accusations"]), viewerPayoff = `The viewer can explain ${seed.question.toLowerCase()} without relying on personal-finance advice.`, hook = `A familiar financial action looks simple—until the money, data and risk leave the screen.`;
    const brief = { viewerPayoff, hook, narrative, claims, evidenceRequirements, visuals, risks, duration: 720, costCeiling: policy.perVideoCostCeilingUsd };
    statements.push(db.prepare("INSERT INTO production_briefs_v1 (id,run_id,plan_item_id,opportunity_id,brief_version,viewer_payoff,hook,narrative_structure_json,claims_json,evidence_requirements_json,visual_opportunities_json,risk_controls_json,target_duration_seconds,cost_ceiling_usd,lifecycle_state,content_hash,created_at) VALUES (?,?,?,?,1,?,?,?,?,?,?,?,?,?,'READY_FOR_PRODUCTION',?,?)").bind(briefId, runId, itemId, opportunityIds[index], viewerPayoff, hook, json(narrative), json(claims), json(evidenceRequirements), json(visuals), json(risks), 720, policy.perVideoCostCeilingUsd, await sha256(json(brief)), now));
  }
  statements.push(db.prepare("INSERT INTO content_planning_audits (id,channel_id,entity_type,entity_id,event_type,actor_type,actor_email,policy_version,strategy_version,idempotency_key,request_hash,detail_json,created_at) VALUES (?,?,?,?, 'CONTENT_AUTOPILOT_COMPLETED','SYSTEM_AUTOPILOT',NULL,?,?,?,?,?,?)").bind(`${runId}:audit`, body.channelId, "CONTENT_PLANNING_RUN", runId, Number(policyRow.policy_version), Number(strategy.channel_strategy_version), idempotencyKey, requestHash, json({ pillars: PILLARS.length, series: seriesSeeds.length, opportunities: OPPORTUNITIES.length, briefs: OPPORTUNITIES.length, providerRequests: 0, spendUsd: 0 }), now));
  await db.batch(statements);
  return receipt(body.action, body.channelId, Number(policyRow.policy_version), runVersion, "COMPLETE", "SYSTEM_AUTOPILOT", false);
}

export async function submitContentAutopilotCommand(db: ContentAutopilotDB, command: Command) {
  if (!command.actor.email || !["CHANNEL_OWNER", "PORTFOLIO_GOVERNANCE"].includes(command.actor.role)) throw new ContentAutopilotError("CHANNEL_OWNER_AUTHORIZATION_REQUIRED", 403, "Content Autopilot requires channel owner authority");
  const body = parseContentAutopilotBody(command.body), idempotencyKey = validateContentAutopilotIdempotencyKey(command.idempotencyKey), actorEmail = clean(command.actor.email).toLowerCase(), requestHash = await sha256(json({ actorEmail, ...body }));
  const policyReplay = await first(db, "SELECT * FROM content_automation_policies WHERE idempotency_key=? LIMIT 1", idempotencyKey);
  if (policyReplay) { if (clean(policyReplay.request_hash) !== requestHash) throw new ContentAutopilotError("IDEMPOTENCY_KEY_REUSED", 409, "The idempotency key is bound to another policy command"); return receipt(body.action, body.channelId, Number(policyReplay.policy_version), Number((await first(db, "SELECT run_version FROM content_planning_runs WHERE channel_id=? ORDER BY run_version DESC LIMIT 1", body.channelId))?.run_version || 0), clean(policyReplay.lifecycle_state), command.actor.displayName, true); }
  const runReplay = await first(db, "SELECT * FROM content_planning_runs WHERE idempotency_key=? LIMIT 1", idempotencyKey);
  if (runReplay) { if (clean(runReplay.request_hash) !== requestHash) throw new ContentAutopilotError("IDEMPOTENCY_KEY_REUSED", 409, "The idempotency key is bound to another planning run"); return receipt(body.action, body.channelId, Number(runReplay.policy_version), Number(runReplay.run_version), clean(runReplay.lifecycle_state), "SYSTEM_AUTOPILOT", true); }
  try { return body.action === "RUN_CONTENT_AUTOPILOT" ? await runAutopilot(db, command, requestHash, idempotencyKey) : await recordPolicy(db, command, requestHash, idempotencyKey); }
  catch (error) { if (error instanceof ContentAutopilotError) throw error; const retryPolicy = await first(db, "SELECT * FROM content_automation_policies WHERE idempotency_key=? LIMIT 1", idempotencyKey), retryRun = await first(db, "SELECT * FROM content_planning_runs WHERE idempotency_key=? LIMIT 1", idempotencyKey); if (retryPolicy && clean(retryPolicy.request_hash) === requestHash) return receipt(body.action, body.channelId, Number(retryPolicy.policy_version), 0, clean(retryPolicy.lifecycle_state), command.actor.displayName, true); if (retryRun && clean(retryRun.request_hash) === requestHash) return receipt(body.action, body.channelId, Number(retryRun.policy_version), Number(retryRun.run_version), clean(retryRun.lifecycle_state), "SYSTEM_AUTOPILOT", true); throw new ContentAutopilotError("CONTENT_AUTOPILOT_COMMIT_FAILED", 503, "The Content Autopilot command could not be recorded atomically"); }
}
