import type { AutomationMode, ContentPlanningProjection } from "@/app/content-planning-contract";
type Row = Record<string, unknown>;
type Statement = { bind: (...values: unknown[]) => Statement; all: <T>() => Promise<{ results?: T[] }> };
export type ContentPlanningReadDB = { prepare: (query: string) => Statement };
function clean(value: unknown) { return String(value ?? "").trim(); }
function number(value: unknown) { return Number(value || 0); }
function bool(value: unknown) { return Boolean(value); }
function parse<T>(value: unknown, fallback: T): T { try { return JSON.parse(clean(value)) as T; } catch { return fallback; } }
async function rows(db: ContentPlanningReadDB, query: string, ...values: unknown[]) { return (await db.prepare(query).bind(...values).all<Row>()).results || []; }
async function first(db: ContentPlanningReadDB, query: string, ...values: unknown[]) { return (await rows(db, query, ...values))[0] || null; }

export async function contentPlanningProjection(channelId: string, db: ContentPlanningReadDB): Promise<ContentPlanningProjection> {
  const strategy = await first(db, "SELECT * FROM channel_strategy_activations WHERE channel_id=? ORDER BY channel_strategy_version DESC LIMIT 1", channelId);
  const policy = await first(db, "SELECT * FROM content_automation_policies WHERE channel_id=? ORDER BY policy_version DESC LIMIT 1", channelId);
  const run = await first(db, "SELECT * FROM content_planning_runs WHERE channel_id=? ORDER BY run_version DESC LIMIT 1", channelId);
  const strategyState = !strategy ? "MISSING" : clean(strategy.lifecycle_state) === "ACTIVATED" ? "ACTIVE" : "STALE";
  const policyStale = Boolean(policy && strategy && (clean(policy.strategy_activation_id) !== clean(strategy.id) || number(policy.strategy_version) !== number(strategy.channel_strategy_version)));
  const policyState = !policy ? "NOT_CONFIGURED" : policyStale ? "STALE" : clean(policy.lifecycle_state) as ContentPlanningProjection["policy"]["state"];
  const runStale = Boolean(run && strategy && (clean(run.strategy_activation_id) !== clean(strategy.id) || number(run.strategy_version) !== number(strategy.channel_strategy_version) || clean(run.policy_id) !== clean(policy?.id)));
  const runState = !run ? "NOT_RUN" : runStale ? "STALE" : clean(run.lifecycle_state) === "COMPLETE" ? "COMPLETE" : "BLOCKED";
  const runId = clean(run?.id);
  const [pillarRows, seriesRows, opportunityRows, planRows, itemRows, briefRows, exceptionRows, auditRows] = runId ? await Promise.all([
    rows(db, "SELECT * FROM content_pillars WHERE run_id=? ORDER BY position,id", runId), rows(db, "SELECT * FROM content_series WHERE run_id=? ORDER BY position,id", runId), rows(db, "SELECT * FROM content_opportunities WHERE run_id=? ORDER BY system_rank,id", runId), rows(db, "SELECT * FROM editorial_plans WHERE run_id=? ORDER BY plan_version DESC LIMIT 1", runId), rows(db, "SELECT i.*,o.title FROM editorial_plan_items i JOIN content_opportunities o ON o.id=i.opportunity_id WHERE i.plan_id IN (SELECT id FROM editorial_plans WHERE run_id=?) ORDER BY i.sequence,i.id", runId), rows(db, "SELECT b.*,o.title FROM production_briefs_v1 b JOIN content_opportunities o ON o.id=b.opportunity_id WHERE b.run_id=? ORDER BY b.created_at,b.id", runId), rows(db, "SELECT * FROM content_planning_exceptions WHERE run_id=? ORDER BY created_at DESC,id", runId), rows(db, "SELECT * FROM content_planning_audits WHERE channel_id=? ORDER BY created_at DESC,id LIMIT 20", channelId),
  ]) : [[], [], [], [], [], [], [], policy ? await rows(db, "SELECT * FROM content_planning_audits WHERE channel_id=? ORDER BY created_at DESC,id LIMIT 20", channelId) : []];
  const plan = planRows[0] || null;
  const pillars = pillarRows.map((row) => ({ id: clean(row.id), position: number(row.position), title: clean(row.title), purpose: clean(row.purpose), audienceNeed: clean(row.audience_need), differentiation: clean(row.differentiation), evidenceRequirement: clean(row.evidence_requirement), winningCriteria: parse<string[]>(row.winning_criteria_json, []), state: clean(row.lifecycle_state) }));
  const series = seriesRows.map((row) => ({ id: clean(row.id), pillarId: clean(row.pillar_id), position: number(row.position), title: clean(row.title), format: clean(row.format), repeatablePromise: clean(row.repeatable_promise), cadenceWeight: number(row.cadence_weight), state: clean(row.lifecycle_state) }));
  const opportunities = opportunityRows.map((row) => ({ id: clean(row.id), seriesId: clean(row.series_id), systemRank: number(row.system_rank), title: clean(row.title), audienceProblem: clean(row.audience_problem), coreQuestion: clean(row.core_question), evidenceRefs: parse<string[]>(row.evidence_refs_json, []), axes: { strategyFit: number(row.strategy_fit), audienceDemand: number(row.audience_demand), differentiation: number(row.differentiation), evidenceReadiness: number(row.evidence_readiness) }, productionComplexity: clean(row.production_complexity), estimatedCostUsd: number(row.estimated_cost_usd), state: clean(row.lifecycle_state), rationale: clean(row.rationale) }));
  const briefs = briefRows.map((row) => ({ id: clean(row.id), opportunityId: clean(row.opportunity_id), title: clean(row.title), version: number(row.brief_version), viewerPayoff: clean(row.viewer_payoff), hook: clean(row.hook), narrativeStructure: parse<string[]>(row.narrative_structure_json, []), claims: parse<string[]>(row.claims_json, []), evidenceRequirements: parse<string[]>(row.evidence_requirements_json, []), visualOpportunities: parse<string[]>(row.visual_opportunities_json, []), riskControls: parse<string[]>(row.risk_controls_json, []), targetDurationSeconds: number(row.target_duration_seconds), costCeilingUsd: number(row.cost_ceiling_usd), state: clean(row.lifecycle_state) }));
  const exceptions = exceptionRows.map((row) => ({ id: clean(row.id), type: clean(row.exception_type), severity: clean(row.severity), state: clean(row.lifecycle_state), title: clean(row.title), detail: clean(row.detail), owningAuthority: clean(row.owning_authority), resolution: clean(row.resolution) || null, createdAt: clean(row.created_at) }));
  const openExceptions = exceptions.filter((item) => item.state === "OPEN").length, briefsReady = briefs.filter((item) => item.state === "READY_FOR_PRODUCTION").length;
  const blockers = [...(strategyState !== "ACTIVE" ? ["An active Channel Strategy is required."] : []), ...(policyState === "NOT_CONFIGURED" ? ["Configure an Automation Policy."] : []), ...(["PAUSED", "EMERGENCY_STOPPED", "STALE"].includes(policyState) ? [`Automation policy is ${policyState.toLowerCase().replaceAll("_", " ")}.`] : []), ...(runState !== "COMPLETE" ? ["Run Content Autopilot against the current strategy and policy."] : []), ...(openExceptions ? [`${openExceptions} owner/expert exception(s) require resolution.`] : [])];
  const handoffState = strategyState !== "ACTIVE" ? "STRATEGY_REQUIRED" : policyState === "NOT_CONFIGURED" ? "POLICY_REQUIRED" : ["PAUSED", "EMERGENCY_STOPPED"].includes(policyState) ? "PAUSED" : runState === "COMPLETE" && briefsReady > 0 && !openExceptions ? "READY_FOR_PRODUCTION" : "PLANNING_REQUIRED";
  return {
    contract: "CONTENT_SYSTEM_PLANNING_PROJECTION_V1", generatedAt: new Date().toISOString(), channelId,
    strategy: { state: strategyState, activationId: clean(strategy?.id) || null, version: number(strategy?.channel_strategy_version), niche: clean(strategy?.opportunity_id) || null, viewerPromise: clean(strategy?.viewer_promise) || null },
    policy: { state: policyState, id: clean(policy?.id) || null, version: number(policy?.policy_version), mode: clean(policy?.mode) ? clean(policy?.mode) as AutomationMode : null, dailyBudgetUsd: number(policy?.daily_budget_usd), monthlyBudgetUsd: number(policy?.monthly_budget_usd), perVideoCostCeilingUsd: number(policy?.per_video_cost_ceiling_usd), cadencePerMonth: number(policy?.cadence_per_month), repairLimit: number(policy?.repair_limit), riskTolerance: (clean(policy?.risk_tolerance) || "LOW") as "LOW" | "MEDIUM" | "HIGH", autoProduction: bool(policy?.auto_production), autoPublish: bool(policy?.auto_publish), escalationRules: parse<string[]>(policy?.escalation_rules_json, []), configuredBy: clean(policy?.actor_display_name) || clean(policy?.actor_email) || null, configuredAt: clean(policy?.created_at) || null },
    run: { state: runState, id: runId || null, version: number(run?.run_version), horizonDays: number(run?.horizon_days), actorType: run ? "SYSTEM_AUTOPILOT" : null, providerRequests: number(run?.provider_requests), spendUsd: number(run?.spend_usd), createdAt: clean(run?.created_at) || null },
    pillars, series, opportunities,
    editorialPlan: { id: clean(plan?.id) || null, version: number(plan?.plan_version), horizonDays: number(plan?.horizon_days), cadencePerMonth: number(plan?.cadence_per_month), state: !plan ? "NOT_CREATED" : runStale ? "STALE" : clean(plan.lifecycle_state) as ContentPlanningProjection["editorialPlan"]["state"], rationale: clean(plan?.rationale) || null, items: itemRows.map((row) => ({ id: clean(row.id), sequence: number(row.sequence), publishOffsetDays: number(row.publish_offset_days), opportunityId: clean(row.opportunity_id), title: clean(row.title), state: clean(row.lifecycle_state) })) },
    briefs, exceptions,
    audit: auditRows.map((row) => ({ id: clean(row.id), entityType: clean(row.entity_type), entityId: clean(row.entity_id), eventType: clean(row.event_type), actorType: clean(row.actor_type), policyVersion: number(row.policy_version), strategyVersion: number(row.strategy_version), createdAt: clean(row.created_at) })),
    summary: { pillars: pillars.length, series: series.length, opportunities: opportunities.length, planned: itemRows.length, briefsReady, openExceptions, providerRequests: number(run?.provider_requests), spendUsd: number(run?.spend_usd) },
    handoff: { state: handoffState, eligibleBriefs: briefsReady, productionDispatchAuthorized: Boolean(policy?.auto_production) && handoffState === "READY_FOR_PRODUCTION", publishingAuthorized: Boolean(policy?.auto_publish) && handoffState === "READY_FOR_PRODUCTION", blockers },
    integrity: { state: policyStale || runStale ? "RECONCILIATION_REQUIRED" : "READY", notes: [...(policyStale ? ["Automation Policy is stale against Channel Strategy."] : []), ...(runStale ? ["Content plan is stale against current policy or strategy."] : [])] },
  };
}
