export const NICHE_SCORING_COMMAND_VERSION = "NICHE_SCORING_COMMAND_V1" as const;
export type NicheScoringOrigin = "SYSTEM_DISCOVERED" | "EXPERT_SEEDED";
export type NicheScoringEligibility = "ELIGIBLE" | "BLOCKED_BY_PREREQUISITE" | "RESEARCH_REQUIRED";
export type NicheConditionAssessment = {
  id: string; label: string; status: "PASS" | "GAP" | "UNKNOWN"; basis: string;
  evidenceEventIds: string[]; closingAction: string; proofMethod: string;
};
export type NicheAxisAssessment = { score: number; basis: string; evidenceEventIds: string[] };
export type NicheScoringBody = {
  action: "RECORD_NICHE_SCORING_ASSESSMENT";
  channelId: string; programId: string; opportunityId: string; opportunityOrigin: NicheScoringOrigin;
  expectedAggregateVersion: number; expectedEvidenceVersion: number; expectedScoringVersion: number;
  marketAttractiveness: NicheAxisAssessment; abilityToWin: NicheAxisAssessment; evidenceConfidence: NicheAxisAssessment;
  prerequisites: NicheConditionAssessment[]; winningCriteria: NicheConditionAssessment[];
};
export type NicheScoringActor = { email: string; displayName: string; role: "OWNER_EXPERT" };
export type NicheScoringCommand = { body: NicheScoringBody; actor: NicheScoringActor; idempotencyKey: string; correlationId?: string | null; causationId?: string | null };
export type NicheScoringReceipt = {
  contract: typeof NICHE_SCORING_COMMAND_VERSION; outcome: "RECORDED" | "IDEMPOTENT_REPLAY";
  assessment: { id: string; scoringVersion: number; evidenceVersion: number; sufficiencyState: "SUFFICIENT" | "INSUFFICIENT"; sufficiencyGaps: string[]; comparisonEligibility: NicheScoringEligibility; opportunityId: string; createdAt: string };
  authority: { authenticated: true; authorized: true; providerRequests: 0; spendUsd: 0; aggregateScore: null; expertPriorityMutation: false; nicheSelection: false; nicheCommitment: false; channelNicheMutation: false; channelStrategyActivation: false };
  nextAction: "COMPARE_PORTFOLIO" | "CLOSE_PREREQUISITE_GAPS" | "CONTINUE_EVIDENCE_RESEARCH";
};

type Row = Record<string, unknown>;
type D1Result = { meta?: { changes?: number } };
type Statement = { bind: (...values: unknown[]) => Statement; all: <T>() => Promise<{ results?: T[] }>; run: () => Promise<D1Result> };
export type NicheScoringDB = { prepare: (query: string) => Statement; batch: (statements: Statement[]) => Promise<D1Result[]> };

export class NicheScoringCommandError extends Error {
  constructor(public readonly code: string, public readonly status: number, message: string) { super(message); this.name = "NicheScoringCommandError"; }
}

function clean(value: unknown) { return String(value ?? "").trim(); }
function text(value: unknown, field: string, min = 1, max = 2000) { const result = clean(value); if (result.length < min || result.length > max) throw new NicheScoringCommandError("COMMAND_VALIDATION_FAILED", 400, `${field} must contain ${min}-${max} characters`); return result; }
function integer(value: unknown, field: string, min: number, max: number) { const result = Number(value); if (!Number.isInteger(result) || result < min || result > max) throw new NicheScoringCommandError("COMMAND_VALIDATION_FAILED", 400, `${field} must be an integer between ${min} and ${max}`); return result; }
function oneOf<T extends string>(value: unknown, field: string, values: readonly T[]) { const result = clean(value).toUpperCase() as T; if (!values.includes(result)) throw new NicheScoringCommandError("COMMAND_VALIDATION_FAILED", 400, `${field} is not supported`); return result; }
function ids(value: unknown, field: string) { if (!Array.isArray(value)) throw new NicheScoringCommandError("COMMAND_VALIDATION_FAILED", 400, `${field} must be an array`); const result = [...new Set(value.map((item) => text(item, `${field} item`, 1, 256)))]; if (!result.length || result.length > 20) throw new NicheScoringCommandError("COMMAND_VALIDATION_FAILED", 400, `${field} must contain 1-20 distinct evidence event IDs`); return result; }
function axis(value: unknown, field: string): NicheAxisAssessment { if (!value || typeof value !== "object" || Array.isArray(value)) throw new NicheScoringCommandError("COMMAND_VALIDATION_FAILED", 400, `${field} is required`); const row = value as Row; return { score: integer(row.score, `${field}.score`, 0, 100), basis: text(row.basis, `${field}.basis`, 20, 2000), evidenceEventIds: ids(row.evidenceEventIds, `${field}.evidenceEventIds`) }; }
function conditions(value: unknown, field: string): NicheConditionAssessment[] {
  if (!Array.isArray(value) || !value.length || value.length > 12) throw new NicheScoringCommandError("COMMAND_VALIDATION_FAILED", 400, `${field} must contain 1-12 assessed conditions`);
  const parsed = value.map((item, index) => { if (!item || typeof item !== "object" || Array.isArray(item)) throw new NicheScoringCommandError("COMMAND_VALIDATION_FAILED", 400, `${field}[${index}] must be an object`); const row = item as Row; return { id: text(row.id, `${field}[${index}].id`, 1, 160), label: text(row.label, `${field}[${index}].label`, 4, 300), status: oneOf(row.status, `${field}[${index}].status`, ["PASS", "GAP", "UNKNOWN"] as const), basis: text(row.basis, `${field}[${index}].basis`, 20, 2000), evidenceEventIds: ids(row.evidenceEventIds, `${field}[${index}].evidenceEventIds`), closingAction: text(row.closingAction, `${field}[${index}].closingAction`, 4, 1000), proofMethod: text(row.proofMethod, `${field}[${index}].proofMethod`, 4, 1000) }; });
  if (new Set(parsed.map((item) => item.id)).size !== parsed.length) throw new NicheScoringCommandError("COMMAND_VALIDATION_FAILED", 400, `${field} IDs must be unique`);
  return parsed;
}

export function parseNicheScoringBody(value: unknown): NicheScoringBody {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new NicheScoringCommandError("COMMAND_VALIDATION_FAILED", 400, "A JSON scoring command is required");
  const row = value as Row;
  return {
    action: oneOf(row.action, "action", ["RECORD_NICHE_SCORING_ASSESSMENT"] as const), channelId: text(row.channelId, "channelId", 1, 256), programId: text(row.programId, "programId", 1, 256), opportunityId: text(row.opportunityId, "opportunityId", 1, 256),
    opportunityOrigin: oneOf(row.opportunityOrigin, "opportunityOrigin", ["SYSTEM_DISCOVERED", "EXPERT_SEEDED"] as const), expectedAggregateVersion: integer(row.expectedAggregateVersion, "expectedAggregateVersion", 1, Number.MAX_SAFE_INTEGER), expectedEvidenceVersion: integer(row.expectedEvidenceVersion, "expectedEvidenceVersion", 1, Number.MAX_SAFE_INTEGER), expectedScoringVersion: integer(row.expectedScoringVersion, "expectedScoringVersion", 0, Number.MAX_SAFE_INTEGER),
    marketAttractiveness: axis(row.marketAttractiveness, "marketAttractiveness"), abilityToWin: axis(row.abilityToWin, "abilityToWin"), evidenceConfidence: axis(row.evidenceConfidence, "evidenceConfidence"), prerequisites: conditions(row.prerequisites, "prerequisites"), winningCriteria: conditions(row.winningCriteria, "winningCriteria"),
  };
}
export function validateNicheScoringIdempotencyKey(value: unknown) { const key = text(value, "Idempotency-Key", 12, 200); if (!/^[A-Za-z0-9._:-]+$/.test(key)) throw new NicheScoringCommandError("COMMAND_VALIDATION_FAILED", 400, "Idempotency-Key contains unsupported characters"); return key; }
async function first(db: NicheScoringDB, query: string, ...values: unknown[]) { return ((await db.prepare(query).bind(...values).all<Row>()).results || [])[0] || null; }
async function all(db: NicheScoringDB, query: string, ...values: unknown[]) { return (await db.prepare(query).bind(...values).all<Row>()).results || []; }
async function sha256(value: string) { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
function parseArtifactOpportunity(row: Row | null, opportunityId: string) { if (!row) return false; try { const artifact = JSON.parse(clean(row.content_json)) as { nicheOpportunities?: Row[] }; return Array.isArray(artifact.nicheOpportunities) && artifact.nicheOpportunities.some((item, index) => clean(item.entityType) === "NICHE_OPPORTUNITY" && (clean(item.opportunityId) || clean(item.id) || `${clean(row.id)}:niche:${index + 1}`) === opportunityId); } catch { return false; } }
function json(value: unknown) { try { return JSON.parse(clean(value)); } catch { return []; } }
function receipt(row: Row, replay: boolean): NicheScoringReceipt { const eligibility = clean(row.comparison_eligibility) as NicheScoringEligibility; return { contract: NICHE_SCORING_COMMAND_VERSION, outcome: replay ? "IDEMPOTENT_REPLAY" : "RECORDED", assessment: { id: clean(row.id), scoringVersion: Number(row.scoring_version), evidenceVersion: Number(row.evidence_version), sufficiencyState: clean(row.sufficiency_state) as "SUFFICIENT" | "INSUFFICIENT", sufficiencyGaps: json(row.sufficiency_gaps_json) as string[], comparisonEligibility: eligibility, opportunityId: clean(row.opportunity_id), createdAt: clean(row.created_at) }, authority: { authenticated: true, authorized: true, providerRequests: 0, spendUsd: 0, aggregateScore: null, expertPriorityMutation: false, nicheSelection: false, nicheCommitment: false, channelNicheMutation: false, channelStrategyActivation: false }, nextAction: eligibility === "ELIGIBLE" ? "COMPARE_PORTFOLIO" : eligibility === "BLOCKED_BY_PREREQUISITE" ? "CLOSE_PREREQUISITE_GAPS" : "CONTINUE_EVIDENCE_RESEARCH" }; }

export async function submitNicheScoringCommand(db: NicheScoringDB, command: NicheScoringCommand): Promise<NicheScoringReceipt> {
  const body = parseNicheScoringBody(command.body); const idempotencyKey = validateNicheScoringIdempotencyKey(command.idempotencyKey); const actorEmail = clean(command.actor.email).toLowerCase(); const actorDisplayName = text(command.actor.displayName, "actor.displayName", 1, 256);
  if (!actorEmail || command.actor.role !== "OWNER_EXPERT") throw new NicheScoringCommandError("OWNER_EXPERT_AUTHORIZATION_REQUIRED", 403, "An authorized owner/expert identity is required");
  const requestHash = await sha256(JSON.stringify({ actorEmail, ...body })); const existing = await first(db, "SELECT * FROM niche_scoring_assessments WHERE idempotency_key=? LIMIT 1", idempotencyKey);
  if (existing) { if (clean(existing.request_hash) !== requestHash) throw new NicheScoringCommandError("IDEMPOTENCY_KEY_REUSED", 409, "The idempotency key is already bound to a different scoring command"); return receipt(existing, true); }
  const program = await first(db, "SELECT id,channel_id,version FROM v7_program_contracts WHERE id=? AND channel_id=? LIMIT 1", body.programId, body.channelId);
  if (!program) throw new NicheScoringCommandError("CROSS_CHANNEL_PROGRAM_REFERENCE", 409, "The selected program does not belong to this channel");
  if (Number(program.version) !== body.expectedAggregateVersion) throw new NicheScoringCommandError("AGGREGATE_VERSION_CONFLICT", 409, "The channel aggregate changed; reload before submitting");
  const expert = await first(db, "SELECT id FROM niche_hypotheses WHERE id=? AND channel_id=? AND program_id=? LIMIT 1", body.opportunityId, body.channelId, body.programId); const artifact = expert ? null : await first(db, "SELECT id,content_json FROM v7_intelligence_artifacts WHERE program_id=? AND stage_key='01' ORDER BY updated_at DESC,id LIMIT 1", body.programId);
  const origin: NicheScoringOrigin | null = expert ? "EXPERT_SEEDED" : parseArtifactOpportunity(artifact, body.opportunityId) ? "SYSTEM_DISCOVERED" : null;
  if (!origin) throw new NicheScoringCommandError("NICHE_OPPORTUNITY_NOT_FOUND", 404, "The typed niche opportunity is not available in this channel program");
  if (origin !== body.opportunityOrigin) throw new NicheScoringCommandError("OPPORTUNITY_ORIGIN_CONFLICT", 409, "The opportunity origin does not match its canonical identity");
  const latestEvidence = await first(db, "SELECT evidence_version FROM niche_evidence_workflow_events WHERE opportunity_id=? ORDER BY evidence_version DESC LIMIT 1", body.opportunityId);
  if (Number(latestEvidence?.evidence_version || 0) !== body.expectedEvidenceVersion) throw new NicheScoringCommandError("EVIDENCE_VERSION_CONFLICT", 409, "The scoring assessment must bind the latest evidence version");
  const latestScoring = await first(db, "SELECT scoring_version FROM niche_scoring_assessments WHERE opportunity_id=? ORDER BY scoring_version DESC LIMIT 1", body.opportunityId);
  if (Number(latestScoring?.scoring_version || 0) !== body.expectedScoringVersion) throw new NicheScoringCommandError("SCORING_VERSION_CONFLICT", 409, "A newer scoring assessment exists; reload before submitting");
  const reviews = await all(db, "SELECT * FROM niche_evidence_workflow_events WHERE opportunity_id=? AND action='RECORD_NICHE_EVIDENCE_REVIEW' AND evidence_version<=? ORDER BY evidence_version", body.opportunityId, body.expectedEvidenceVersion);
  const byId = new Map(reviews.map((row) => [clean(row.id), row]));
  const bindings: Array<[string, string[], string]> = [["Market Attractiveness", body.marketAttractiveness.evidenceEventIds, "MARKET_ATTRACTIVENESS"], ["Ability to Win", body.abilityToWin.evidenceEventIds, "ABILITY_TO_WIN"], ["Evidence Confidence", body.evidenceConfidence.evidenceEventIds, "EVIDENCE_CONFIDENCE"], ...body.prerequisites.map((item) => [item.label, item.evidenceEventIds, "PREREQUISITE"] as [string, string[], string]), ...body.winningCriteria.map((item) => [item.label, item.evidenceEventIds, "WINNING_CRITERION"] as [string, string[], string])];
  for (const [label, eventIds, affectedAxis] of bindings) for (const eventId of eventIds) { const review = byId.get(eventId); if (!review || clean(review.review_disposition) !== "ACCEPTED" || clean(review.affected_axis) !== affectedAxis) throw new NicheScoringCommandError("INVALID_EVIDENCE_BINDING", 409, `${label} must bind accepted ${affectedAxis} evidence reviews from this opportunity`); }
  const bound = [...new Set(bindings.flatMap(([, eventIds]) => eventIds))].map((id) => byId.get(id)!).filter(Boolean); const directions = new Set(bound.map((row) => clean(row.claim_direction))); const gaps: string[] = [];
  if (!directions.has("SUPPORTS")) gaps.push("No accepted supporting evidence is bound"); if (!directions.has("CONTRADICTS")) gaps.push("No accepted contradicting evidence is bound"); if (!directions.has("UNKNOWN")) gaps.push("No accepted unknown-finding evidence is bound"); if (!bound.some((row) => clean(row.source_authority) === "PRIMARY")) gaps.push("No primary source is bound"); if (bound.some((row) => ["STALE", "UNKNOWN"].includes(clean(row.freshness)))) gaps.push("A bound evidence review is stale or has unknown freshness");
  const sufficiencyState = gaps.length ? "INSUFFICIENT" : "SUFFICIENT"; const prerequisiteBlocked = body.prerequisites.some((item) => item.status !== "PASS"); const comparisonEligibility: NicheScoringEligibility = sufficiencyState === "INSUFFICIENT" ? "RESEARCH_REQUIRED" : prerequisiteBlocked ? "BLOCKED_BY_PREREQUISITE" : "ELIGIBLE";
  const scoringVersion = body.expectedScoringVersion + 1; const assessmentId = `niche-scoring:${crypto.randomUUID()}`; const auditId = `${assessmentId}:audit`; const lineageId = `${assessmentId}:lineage`; const now = new Date().toISOString(); const correlationId = command.correlationId ? text(command.correlationId, "X-Correlation-Id", 1, 256) : `niche-scoring:${idempotencyKey}`; const causationId = command.causationId ? text(command.causationId, "X-Causation-Id", 1, 256) : null;
  const insert = "INSERT INTO niche_scoring_assessments (id,portfolio_id,channel_id,program_id,opportunity_id,opportunity_origin,aggregate_version,evidence_version,scoring_version,action,sufficiency_state,sufficiency_gaps_json,market_attractiveness_score,market_attractiveness_basis,market_attractiveness_evidence_json,ability_to_win_score,ability_to_win_basis,ability_to_win_evidence_json,evidence_confidence_score,evidence_confidence_basis,evidence_confidence_evidence_json,prerequisites_json,winning_criteria_json,comparison_eligibility,actor_email,actor_display_name,actor_role,idempotency_key,request_hash,correlation_id,causation_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,'RECORD_NICHE_SCORING_ASSESSMENT',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'OWNER_EXPERT',?,?,?,?,?)";
  try { await db.batch([
    db.prepare(insert).bind(assessmentId, "CANONICAL_PORTFOLIO", body.channelId, body.programId, body.opportunityId, origin, body.expectedAggregateVersion, body.expectedEvidenceVersion, scoringVersion, sufficiencyState, JSON.stringify(gaps), body.marketAttractiveness.score, body.marketAttractiveness.basis, JSON.stringify(body.marketAttractiveness.evidenceEventIds), body.abilityToWin.score, body.abilityToWin.basis, JSON.stringify(body.abilityToWin.evidenceEventIds), body.evidenceConfidence.score, body.evidenceConfidence.basis, JSON.stringify(body.evidenceConfidence.evidenceEventIds), JSON.stringify(body.prerequisites), JSON.stringify(body.winningCriteria), comparisonEligibility, actorEmail, actorDisplayName, idempotencyKey, requestHash, correlationId, causationId, now),
    db.prepare("INSERT INTO niche_scoring_assessment_audits (id,assessment_id,program_id,channel_id,opportunity_id,event_type,actor_email,actor_role,idempotency_key,request_hash,correlation_id,causation_id,evidence_lineage_id,created_at) VALUES (?,?,?,?,?,'NICHE_SCORING_ASSESSMENT_RECORDED',?,'OWNER_EXPERT',?,?,?,?,?,?)").bind(auditId, assessmentId, body.programId, body.channelId, body.opportunityId, actorEmail, idempotencyKey, requestHash, correlationId, causationId, lineageId, now),
    db.prepare("INSERT INTO v7_evidence_lineage (id,program_id,project_id,entity_type,title,lifecycle_state,upstream_evidence_id,artifact_key,content_hash,storage_state,rights_state,cost_state,quarantine_state,pipeline_version,created_at,updated_at) VALUES (?,?,?,?,?,'FROZEN',?,?,?,'CANONICAL_D1','NOT_APPLICABLE','ZERO_SPEND','CLEAR',7,?,?)").bind(lineageId, body.programId, null, "NICHE_SCORING_ASSESSMENT", `Niche scoring assessment v${scoringVersion}`, body.opportunityId, assessmentId, requestHash, now, now),
  ]); } catch { const replay = await first(db, "SELECT * FROM niche_scoring_assessments WHERE idempotency_key=? LIMIT 1", idempotencyKey); if (replay && clean(replay.request_hash) === requestHash) return receipt(replay, true); const current = await first(db, "SELECT scoring_version FROM niche_scoring_assessments WHERE opportunity_id=? ORDER BY scoring_version DESC LIMIT 1", body.opportunityId); if (Number(current?.scoring_version || 0) !== body.expectedScoringVersion) throw new NicheScoringCommandError("SCORING_VERSION_CONFLICT", 409, "A concurrent scoring assessment won; reload before submitting"); throw new NicheScoringCommandError("SCORING_COMMIT_FAILED", 503, "The scoring assessment could not be recorded atomically"); }
  const stored = await first(db, "SELECT * FROM niche_scoring_assessments WHERE id=? LIMIT 1", assessmentId); if (!stored || clean(stored.request_hash) !== requestHash) throw new NicheScoringCommandError("SCORING_COMMIT_NOT_VERIFIED", 503, "The scoring write could not be verified"); return receipt(stored, false);
}
