import { PRODUCTION_ENGINE_V2 } from "@/app/production-v2-contract";
import { ProductionV2CommandError, type ProductionV2Bucket, type ProductionV2CommandDB } from "@/lib/production-v2-command";

type Row = Record<string, unknown>;
type Runtime = { DB: ProductionV2CommandDB; BUCKET: ProductionV2Bucket; OPENAI_API_KEY?: string; ELEVENLABS_API_KEY?: string };
const ENGINE = PRODUCTION_ENGINE_V2, CHANNEL = "channel-hidden-systems";
const clean = (value: unknown) => String(value ?? "").trim(), num = (value: unknown) => Number(value ?? 0), now = () => new Date().toISOString();
const encode = (value: string) => new TextEncoder().encode(value), identifier = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
async function hash(value: Uint8Array | string) { const data = typeof value === "string" ? encode(value) : value; return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", data))).map((part) => part.toString(16).padStart(2, "0")).join(""); }
async function run(db: ProductionV2CommandDB, query: string, ...values: unknown[]) { return db.prepare(query).bind(...values.map((value) => value === undefined ? null : value)).run(); }
async function list(db: ProductionV2CommandDB, query: string, ...values: unknown[]) { return (await db.prepare(query).bind(...values).all<Row>()).results ?? []; }
function xml(value: string) { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" })[character] || character); }
function lines(value: string, width: number, max = 4) { const result: string[] = []; let line = ""; for (const word of value.split(/\s+/)) { if (`${line} ${word}`.trim().length > width) { if (line) result.push(line); line = word; } else line = `${line} ${word}`.trim(); } if (line) result.push(line); return result.slice(0, max); }
function sceneSvg(seriesTitle: string, scene: { title: string; claim: string }, index: number) {
  const colors = [["#082e27", "#7dd6ae"], ["#152e48", "#79bee4"], ["#3b2d18", "#e6c16e"], ["#3d2738", "#dc92bb"], ["#21331e", "#9dce78"], ["#2f243c", "#b49ae1"]][index % 6];
  const write = (items: string[], y: number, size: number, color: string) => items.map((item, line) => `<text x="84" y="${y + line * (size + 11)}" fill="${color}" font-family="Arial,sans-serif" font-size="${size}" font-weight="${size > 40 ? 700 : 500}">${xml(item)}</text>`).join("");
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><rect width="1280" height="720" fill="${colors[0]}"/><path d="M860 0h420v720H610c210-165 314-404 250-720Z" fill="${colors[1]}" opacity=".10"/><text x="84" y="76" fill="${colors[1]}" font-family="Arial,sans-serif" font-size="18" font-weight="700" letter-spacing="3">HIDDEN SYSTEMS · ${String(index + 1).padStart(2, "0")} / 30</text>${write(lines(scene.title, 38, 3), 160, 54, "#fff")}${write(lines(scene.claim, 64, 4), 405, 25, "#d6e7e1")}<rect x="84" y="625" width="170" height="5" fill="${colors[1]}"/><text x="278" y="636" fill="#a8c2b9" font-family="Arial,sans-serif" font-size="17">${xml(seriesTitle)}</text></svg>`;
}
async function store(runtime: Runtime, packageId: string, type: string, key: string, mime: string, value: Uint8Array | string, provenance: Record<string, unknown>) {
  const data = typeof value === "string" ? encode(value) : value, sha = await hash(data), existing = await runtime.DB.prepare("SELECT * FROM production_v2_artifacts WHERE storage_key=? AND sha256=? LIMIT 1").bind(key, sha).first<Row>();
  if (existing) return { id: clean(existing.id), storageKey: clean(existing.storage_key), mimeType: clean(existing.mime_type), byteSize: num(existing.byte_size), sha256: clean(existing.sha256) };
  const artifactId = identifier("pv2-artifact");
  await runtime.BUCKET.put(key, data, { httpMetadata: { contentType: mime }, customMetadata: { packageId, artifactId, sha256: sha, engineVersion: ENGINE } });
  const object = await runtime.BUCKET.get(key); if (!object) throw new ProductionV2CommandError("R2_READBACK_FAILED", 503, "Full-video evidence read-back failed"); const readback = new Uint8Array(await object.arrayBuffer()); if (await hash(readback) !== sha) throw new ProductionV2CommandError("R2_HASH_MISMATCH", 503, "Full-video evidence checksum failed");
  await run(runtime.DB, "INSERT INTO production_v2_artifacts (id,package_id,artifact_type,lifecycle_state,storage_key,mime_type,byte_size,sha256,rights_state,provenance_json,engine_version,frozen_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", artifactId, packageId, type, "STORED_VERIFIED", key, mime, readback.byteLength, sha, "CHANNEL_OWNED_OR_PROVIDER_COMMERCIAL", JSON.stringify({ ...provenance, readback: true, legacySources: 0 }), ENGINE, now());
  return { id: artifactId, storageKey: key, mimeType: mime, byteSize: readback.byteLength, sha256: sha };
}
function outputText(payload: unknown) {
  const response = payload as { output?: Array<{ content?: Array<{ type?: string; text?: string }> }> };
  return response.output?.flatMap((item) => item.content ?? []).find((item) => item.type === "output_text")?.text || "";
}
function base64(value: Uint8Array) { let encoded = ""; for (let offset = 0; offset < value.length; offset += 0x8000) encoded += String.fromCharCode(...value.subarray(offset, offset + 0x8000)); return btoa(encoded); }
function visualSchema() { return { type: "object", additionalProperties: false, required: ["status", "p0Count", "p1Count", "summary", "findings"], properties: { status: { type: "string", enum: ["PASS", "BLOCK"] }, p0Count: { type: "integer", minimum: 0, maximum: 9 }, p1Count: { type: "integer", minimum: 0, maximum: 9 }, summary: { type: "string", minLength: 10, maxLength: 400 }, findings: { type: "array", maxItems: 8, items: { type: "string", minLength: 3, maxLength: 240 } } } }; }
async function provider(runtime: Runtime, row: Row, jobId: string, providerName: string, operation: string, key: string, requestHash: string) {
  const requestId = identifier("pv2-provider"); await run(runtime.DB, "INSERT INTO production_v2_provider_requests (id,policy_id,package_id,job_id,provider,operation,lifecycle_state,idempotency_key,request_hash,cost_usd) VALUES (?,?,?,?,?,?,?,?,?,0)", requestId, row.policy_id, row.id, jobId, providerName, operation, "RUNNING", key, requestHash); return requestId;
}
async function completeProvider(runtime: Runtime, requestId: string, responseId: string, inputTokens: number, outputTokens: number, cost: number) { await run(runtime.DB, "UPDATE production_v2_provider_requests SET lifecycle_state='COMPLETED',provider_response_id=?,input_tokens=?,output_tokens=?,cost_usd=?,completed_at=? WHERE id=?", responseId, inputTokens, outputTokens, cost, now(), requestId); }
async function failProvider(runtime: Runtime, requestId: string, code: string) { await run(runtime.DB, "UPDATE production_v2_provider_requests SET lifecycle_state='FAILED',error_code=?,completed_at=? WHERE id=? AND lifecycle_state='RUNNING'", code, now(), requestId); }
async function voice(runtime: Runtime) { const response = await fetch("https://api.elevenlabs.io/v2/voices?page_size=50", { headers: { "xi-api-key": runtime.ELEVENLABS_API_KEY || "" }, signal: AbortSignal.timeout(30_000) }); if (!response.ok) throw new ProductionV2CommandError("ELEVENLABS_VOICE_DISCOVERY_FAILED", 502, `Voice discovery failed (${response.status})`); const body = await response.json() as { voices?: Array<{ voice_id?: string; name?: string; category?: string }> }; const selected = body.voices?.find((item) => item.category === "premade") || body.voices?.[0]; if (!selected?.voice_id) throw new ProductionV2CommandError("ELEVENLABS_VOICE_UNAVAILABLE", 502, "No commercial narration voice is available"); return selected; }

function scriptSchema() { return { type: "object", additionalProperties: false, required: ["narration", "scenes"], properties: { narration: { type: "string", minLength: 8500, maxLength: 16000 }, scenes: { type: "array", minItems: 30, maxItems: 30, items: { type: "object", additionalProperties: false, required: ["title", "claim"], properties: { title: { type: "string", minLength: 8, maxLength: 90 }, claim: { type: "string", minLength: 20, maxLength: 180 } } } } } }; }
function narrationChunks(value: string, ceiling = 4300) { const sentences = value.match(/[^.!?]+[.!?]+|[^.!?]+$/g) ?? [value]; const chunks: string[] = []; let chunk = ""; for (const sentence of sentences) { if (`${chunk} ${sentence}`.trim().length > ceiling && chunk) { chunks.push(chunk.trim()); chunk = sentence.trim(); } else chunk = `${chunk} ${sentence}`.trim(); } if (chunk) chunks.push(chunk); return chunks; }

export async function prepareFullVideo(runtime: Runtime, sequence: number, actorEmail: string, idempotencyKey: string) {
  if (!runtime.OPENAI_API_KEY || !runtime.ELEVENLABS_API_KEY) throw new ProductionV2CommandError("FULL_VIDEO_PROVIDERS_NOT_CONNECTED", 424, "OpenAI and ElevenLabs are required for full-video production");
  const row = await runtime.DB.prepare("SELECT p.*,c.sequence FROM production_v2_packages p JOIN content_episode_concepts_v2 c ON c.id=p.episode_concept_id WHERE p.channel_id=? AND c.sequence=? LIMIT 1").bind(CHANNEL, sequence).first<Row>(); if (!row) throw new ProductionV2CommandError("PACKAGE_NOT_FOUND", 404, "Canonical production package not found");
  const replay = await runtime.DB.prepare("SELECT * FROM production_v2_jobs WHERE idempotency_key=? LIMIT 1").bind(idempotencyKey).first<Row>();
  if (replay) { const manifest = await runtime.DB.prepare("SELECT id FROM production_v2_artifacts WHERE package_id=? AND artifact_type='FULL_VIDEO_MANIFEST' ORDER BY created_at DESC LIMIT 1").bind(row.id).first<Row>(); return { outcome: "REPLAYED", jobId: clean(replay.id), packageId: clean(row.id), state: clean(replay.lifecycle_state), manifestId: clean(manifest?.id) }; }
  const pilot = await runtime.DB.prepare("SELECT lifecycle_state FROM production_v2_scale_waves WHERE channel_id=? AND wave_number=0").bind(CHANNEL).first<Row>(); if (clean(pilot?.lifecycle_state) !== "COMPLETE") throw new ProductionV2CommandError("GOLDEN_PILOT_REQUIRED", 409, "Golden pilot must pass before full-video production");
  if (sequence > 1) { const priorWave = sequence <= 3 ? -1 : sequence <= 7 ? 1 : 2; const canary = await runtime.DB.prepare("SELECT p.lifecycle_state FROM production_v2_packages p JOIN content_episode_concepts_v2 c ON c.id=p.episode_concept_id WHERE p.channel_id=? AND c.sequence=1 LIMIT 1").bind(CHANNEL).first<Row>(); if (clean(canary?.lifecycle_state) !== "READY_FOR_PUBLISHING") throw new ProductionV2CommandError("FULL_VIDEO_CANARY_REQUIRED", 409, "Full-video canary must pass QA2 before scale"); if (priorWave > 0) { const prior = await runtime.DB.prepare("SELECT lifecycle_state FROM production_v2_scale_waves WHERE channel_id=? AND wave_number=?").bind(CHANNEL, priorWave).first<Row>(); if (clean(prior?.lifecycle_state) !== "COMPLETE") throw new ProductionV2CommandError("PRIOR_SCALE_WAVE_REQUIRED", 409, "Prior production wave has not passed admission gates"); } }
  const policy = await runtime.DB.prepare("SELECT * FROM production_v2_policies WHERE id=? AND lifecycle_state='ACTIVE' LIMIT 1").bind(row.policy_id).first<Row>(); if (!policy || Boolean(policy.auto_publish) || clean(policy.legacy_reuse_policy) !== "ZERO_CODE_ZERO_ARTIFACT") throw new ProductionV2CommandError("PRODUCTION_POLICY_BLOCKED", 409, "Production policy blocks full-video generation");
  const jobId = identifier("pv2-full"), contracts = await list(runtime.DB, "SELECT narrative_beat,claim,evidence_refs_json,route FROM production_v2_shot_contracts WHERE package_id=? ORDER BY sequence", row.id), inputHash = await hash(JSON.stringify({ packageId: row.id, contentHash: row.content_hash, contracts }));
  await run(runtime.DB, "INSERT INTO production_v2_jobs (id,package_id,job_type,lifecycle_state,attempt,max_attempts,idempotency_key,input_hash,lease_owner) VALUES (?,?,?,?,?,?,?,?,?)", jobId, row.id, sequence === 1 ? "FULL_VIDEO_CANARY" : "FULL_VIDEO_SCALE", "RUNNING", 1, 1, idempotencyKey, inputHash, "PRODUCTION_V2_ORCHESTRATOR");
  let openAiRequest = ""; const ttsRequests: string[] = [];
  try {
    openAiRequest = await provider(runtime, row, jobId, "OPENAI", "EVIDENCE_BOUND_SCRIPT_AND_SCENES", `${idempotencyKey}:script`, inputHash);
    const prompt = `Create a premium faceless 12-minute documentary script for the channel Hidden Systems Behind Money. Episode: ${clean(row.title)}. Use only these evidence-bound upstream contracts: ${JSON.stringify(contracts)}. Narration must be 1,650-1,950 spoken words, clear US English, no personal-finance advice, no unsupported statistics, no citations spoken aloud, and end with a durable mental model. Return exactly 30 visually distinct scene cards; each claim must be grounded in a supplied contract. Do not mention production, prompts or sources.`;
    const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { authorization: `Bearer ${runtime.OPENAI_API_KEY}`, "content-type": "application/json", "idempotency-key": `${idempotencyKey}:script` }, body: JSON.stringify({ model: "gpt-5.6", reasoning: { effort: "medium" }, max_output_tokens: 14000, input: [{ role: "user", content: prompt }], text: { format: { type: "json_schema", name: "production_v2_full_video", strict: true, schema: scriptSchema() } } }), signal: AbortSignal.timeout(180_000) }); if (!response.ok) throw new ProductionV2CommandError("OPENAI_SCRIPT_FAILED", 502, `OpenAI script generation failed (${response.status})`);
    const responseBody = await response.json() as { id?: string; usage?: { input_tokens?: number; output_tokens?: number } }, generated = JSON.parse(outputText(responseBody)) as { narration: string; scenes: Array<{ title: string; claim: string }> }; if (generated.scenes?.length !== 30 || generated.narration.split(/\s+/).length < 1500) throw new ProductionV2CommandError("OPENAI_SCRIPT_CONTRACT_INVALID", 502, "Generated script failed the 12-minute content contract");
    await completeProvider(runtime, openAiRequest, clean(responseBody.id), num(responseBody.usage?.input_tokens), num(responseBody.usage?.output_tokens), 1.5);
    const selected = await voice(runtime), parts = narrationChunks(generated.narration), packageId = clean(row.id), audioChunks = []; let narrationSpend = 0;
    if (parts.length < 2 || parts.length > 5) throw new ProductionV2CommandError("NARRATION_CHUNK_CONTRACT_INVALID", 502, "Narration could not be bounded into 2–5 provider requests");
    for (let index = 0; index < parts.length; index += 1) {
      const requestId = await provider(runtime, row, jobId, "ELEVENLABS", "FULL_VIDEO_NARRATION_CHUNK", `${idempotencyKey}:tts:${index + 1}`, await hash(parts[index])); ttsRequests.push(requestId);
      const tts = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(clean(selected.voice_id))}?output_format=mp3_44100_128`, { method: "POST", headers: { "xi-api-key": runtime.ELEVENLABS_API_KEY, "content-type": "application/json" }, body: JSON.stringify({ text: parts[index], model_id: "eleven_multilingual_v2", language_code: "en", voice_settings: { stability: .58, similarity_boost: .76, style: .14, use_speaker_boost: true, speed: 1.0 } }), signal: AbortSignal.timeout(180_000) });
      let audioBytes: Uint8Array, provenance: Record<string, unknown>;
      if (tts.ok) {
        audioBytes = new Uint8Array(await tts.arrayBuffer()); narrationSpend += 3 / parts.length;
        provenance = { provider: "ElevenLabs", voiceId: selected.voice_id, voiceName: selected.name, model: "eleven_multilingual_v2" };
        await completeProvider(runtime, requestId, await hash(audioBytes).then((value) => value.slice(0, 24)), 0, parts[index].length, 3 / parts.length);
      } else {
        await failProvider(runtime, requestId, `ELEVENLABS_HTTP_${tts.status}`);
        const fallbackId = await provider(runtime, row, jobId, "OPENAI", "FULL_VIDEO_NARRATION_FALLBACK", `${idempotencyKey}:tts-fallback:${index + 1}`, await hash(parts[index])); ttsRequests.push(fallbackId);
        const fallback = await fetch("https://api.openai.com/v1/audio/speech", { method: "POST", headers: { authorization: `Bearer ${runtime.OPENAI_API_KEY}`, "content-type": "application/json", "idempotency-key": `${idempotencyKey}:tts-fallback:${index + 1}` }, body: JSON.stringify({ model: "gpt-4o-mini-tts", voice: "coral", input: parts[index], instructions: "Calm premium US-English documentary narration. Precise, restrained, natural pacing. Do not add or omit words.", response_format: "mp3" }), signal: AbortSignal.timeout(180_000) });
        if (!fallback.ok) { await failProvider(runtime, fallbackId, `OPENAI_TTS_HTTP_${fallback.status}`); throw new ProductionV2CommandError("OPENAI_TTS_FALLBACK_FAILED", 502, `OpenAI narration fallback chunk ${index + 1} failed (${fallback.status})`); }
        audioBytes = new Uint8Array(await fallback.arrayBuffer()); narrationSpend += .25;
        provenance = { provider: "OpenAI", voice: "coral", model: "gpt-4o-mini-tts", fallbackFrom: `ELEVENLABS_HTTP_${tts.status}` };
        await completeProvider(runtime, fallbackId, fallback.headers.get("x-request-id") || (await hash(audioBytes)).slice(0, 24), 0, parts[index].length, .25);
      }
      if (audioBytes.byteLength < 150_000) throw new ProductionV2CommandError("FULL_NARRATION_EMPTY", 502, `Narration chunk ${index + 1} is incomplete`);
      const audio = await store(runtime, packageId, "FULL_NARRATION_CHUNK", `production-v2/${packageId}/full-v1/narration-${String(index + 1).padStart(2, "0")}.mp3`, "audio/mpeg", audioBytes, { ...provenance, chunk: index + 1, chunks: parts.length }); audioChunks.push(audio);
    }
    const scenes = []; for (let index = 0; index < generated.scenes.length; index += 1) scenes.push(await store(runtime, packageId, "FULL_SCENE", `production-v2/${packageId}/full-v1/scene-${String(index + 1).padStart(2, "0")}.svg`, "image/svg+xml", sceneSvg(clean(row.title), generated.scenes[index], index), { sceneIndex: index + 1, author: ENGINE, claim: generated.scenes[index].claim }));
    const manifestValue = JSON.stringify({ engineVersion: ENGINE, packageId, jobId, sequence, targetDurationSeconds: 720, width: 1280, height: 720, fps: 30, narration: generated.narration, audioChunks, scenes, scenePlan: generated.scenes, legacySources: 0 }); const manifest = await store(runtime, packageId, "FULL_VIDEO_MANIFEST", `production-v2/${packageId}/full-v1/manifest.json`, "application/json", manifestValue, { author: ENGINE, upstreamContractCount: contracts.length, artifactIds: [...audioChunks.map((item) => item.id), ...scenes.map((item) => item.id)] });
    const actualSpend = 1.5 + narrationSpend;
    await run(runtime.DB, "UPDATE production_v2_packages SET lifecycle_state='AWAITING_FULL_RENDER',provider_requests=provider_requests+?,spend_usd=spend_usd+?,shot_count=30 WHERE id=?", 1 + audioChunks.length, actualSpend, packageId); await run(runtime.DB, "UPDATE production_v2_jobs SET lifecycle_state='AWAITING_FULL_RENDER',updated_at=? WHERE id=?", now(), jobId);
    if (sequence > 1) { const wave = sequence <= 3 ? 1 : sequence <= 7 ? 2 : 3; await run(runtime.DB, "UPDATE production_v2_scale_waves SET lifecycle_state='RUNNING' WHERE channel_id=? AND wave_number=?", CHANNEL, wave); }
    await run(runtime.DB, "INSERT INTO production_v2_audits (id,channel_id,entity_type,entity_id,event_type,actor_type,actor_email,detail_json,evidence_hash) VALUES (?,?,?,?,?,?,?,?,?)", identifier("pv2-audit"), CHANNEL, "FULL_VIDEO_JOB", jobId, sequence === 1 ? "CANARY_PLAN_STORED" : "SCALE_PLAN_STORED", "SYSTEM_AUTOPILOT", actorEmail, JSON.stringify({ sequence, scenes: 30, providerRequests: 1 + audioChunks.length, spendUsd: actualSpend, legacySources: 0 }), await hash(manifestValue));
    return { outcome: "RECORDED", jobId, packageId, sequence, state: "AWAITING_FULL_RENDER", manifestId: manifest.id, audioChunks, scenes, estimatedSpendUsd: actualSpend };
  } catch (error) { if (openAiRequest) await failProvider(runtime, openAiRequest, error instanceof ProductionV2CommandError ? error.code : "FULL_VIDEO_FAILURE"); for (const requestId of ttsRequests) await failProvider(runtime, requestId, error instanceof ProductionV2CommandError ? error.code : "FULL_VIDEO_FAILURE"); await run(runtime.DB, "UPDATE production_v2_jobs SET lifecycle_state='FAILED',blocker=?,updated_at=? WHERE id=?", error instanceof Error ? error.message : "Full-video preparation failed", now(), jobId); throw error; }
}

function qaGates(parsed: Record<string, unknown>, video: Row, expectedActor: string) { const dim = parsed.dimensions as Record<string, unknown> | undefined; return { duration: num(parsed.durationSeconds) >= 660 && num(parsed.durationSeconds) <= 735, dimensions: num(dim?.width) >= 1280 && num(dim?.height) >= 720, fps: num(parsed.fps) >= 24, sceneChanges: num(parsed.sceneChanges) >= 29, blackRatio: num(parsed.blackFrameRatio) <= .02, freezeRatio: num(parsed.freezeRatio) <= .08, audio: clean(parsed.audioCodec).length > 0 && num(parsed.loudnessI) >= -22 && num(parsed.loudnessI) <= -12 && num(parsed.truePeakDb) <= -1, checksum: clean(parsed.videoSha256) === clean(video.sha256), independent: clean(parsed.actor) === expectedActor, temporalSamples: Array.isArray(parsed.frameHashes) && parsed.frameHashes.length === 3 }; }

export async function storeFullEvidence(runtime: Runtime, packageId: string, kind: "FULL_VIDEO" | "FULL_QA1" | "FULL_QA_VISUAL" | "FULL_QA2", value: Uint8Array, actorEmail: string) {
  const row = await runtime.DB.prepare("SELECT p.*,c.sequence FROM production_v2_packages p JOIN content_episode_concepts_v2 c ON c.id=p.episode_concept_id WHERE p.id=? AND p.engine_version=? LIMIT 1").bind(packageId, ENGINE).first<Row>(); if (!row) throw new ProductionV2CommandError("PACKAGE_NOT_FOUND", 404, "Production V2 package not found"); const sequence = num(row.sequence);
  const job = await runtime.DB.prepare("SELECT * FROM production_v2_jobs WHERE package_id=? AND job_type IN ('FULL_VIDEO_CANARY','FULL_VIDEO_SCALE') ORDER BY created_at DESC LIMIT 1").bind(packageId).first<Row>(); if (!job) throw new ProductionV2CommandError("FULL_VIDEO_JOB_NOT_FOUND", 409, "Prepare the full video first");
  if (kind === "FULL_VIDEO") { if (value.byteLength < 1_000_000 || value.byteLength > 90_000_000) throw new ProductionV2CommandError("FULL_VIDEO_SIZE_INVALID", 422, "Full video bytes are outside the 1–90 MB boundary"); const artifact = await store(runtime, packageId, "FULL_VIDEO_MASTER", `production-v2/${packageId}/full-v1/master.webm`, "video/webm", value, { executor: "PRODUCTION_V2_GREENFIELD_EXECUTOR", targetDurationSeconds: 720 }); await run(runtime.DB, "UPDATE production_v2_jobs SET lifecycle_state='QA1_REQUIRED',updated_at=? WHERE id=?", now(), job.id); return { outcome: "STORED", artifact, packageId }; }
  if (kind === "FULL_QA_VISUAL") { if (value.byteLength < 20_000 || value.byteLength > 2_000_000) throw new ProductionV2CommandError("VISUAL_SAMPLE_SIZE_INVALID", 422, "Visual QA contact sheet must be 20 KB–2 MB"); const artifact = await store(runtime, packageId, "FULL_QA_VISUAL_SAMPLE", `production-v2/${packageId}/full-v1/visual-sample.jpg`, "image/jpeg", value, { samples: [72, 360, 648], actor: "PRODUCTION_V2_QA_EXECUTOR" }); await run(runtime.DB, "UPDATE production_v2_jobs SET lifecycle_state='QA2_REQUIRED',updated_at=? WHERE id=?", now(), job.id); await run(runtime.DB, "UPDATE production_v2_packages SET lifecycle_state='QA2_REQUIRED' WHERE id=?", packageId); return { outcome: "VISUAL_SAMPLE_STORED", packageId, artifact }; }
  const video = await runtime.DB.prepare("SELECT * FROM production_v2_artifacts WHERE package_id=? AND artifact_type='FULL_VIDEO_MASTER' ORDER BY created_at DESC LIMIT 1").bind(packageId).first<Row>(); if (!video) throw new ProductionV2CommandError("FULL_VIDEO_MASTER_REQUIRED", 409, "Full master must be stored first"); const parsed = JSON.parse(new TextDecoder().decode(value)) as Record<string, unknown>, gates = qaGates(parsed, video, kind === "FULL_QA1" ? "PRODUCTION_V2_QA_EXECUTOR" : "PRODUCTION_V2_RELEASE_QA");
  if (!Object.values(gates).every(Boolean)) throw new ProductionV2CommandError("FULL_VIDEO_QA_FAILED", 422, `Full-video QA failed: ${Object.entries(gates).filter(([, pass]) => !pass).map(([name]) => name).join(", ")}`);
  let visualReview: Record<string, unknown> | null = null;
  if (kind === "FULL_QA2") {
    const visual = await runtime.DB.prepare("SELECT * FROM production_v2_artifacts WHERE package_id=? AND artifact_type='FULL_QA_VISUAL_SAMPLE' ORDER BY created_at DESC LIMIT 1").bind(packageId).first<Row>();
    if (!visual) throw new ProductionV2CommandError("FULL_QA_VISUAL_REQUIRED", 409, "A three-frame visual sample is required before QA2");
    const object = await runtime.BUCKET.get(clean(visual.storage_key)); if (!object) throw new ProductionV2CommandError("FULL_QA_VISUAL_BYTES_MISSING", 503, "Visual QA sample bytes are unavailable"); const bytes = new Uint8Array(await object.arrayBuffer());
    const visualOperationKey = `visual-qa:${clean(video.sha256)}:${clean(visual.sha256)}`;
    const priorVisualAttempt = await runtime.DB.prepare("SELECT id FROM production_v2_provider_requests WHERE operation='INDEPENDENT_VISUAL_RELEASE_QA' AND idempotency_key=? LIMIT 1").bind(visualOperationKey).first<Row>();
    const visualRequestKey = priorVisualAttempt ? `${visualOperationKey}:retry:${crypto.randomUUID()}` : visualOperationKey;
    const requestId = await provider(runtime, row, job.id, "OPENAI", "INDEPENDENT_VISUAL_RELEASE_QA", visualRequestKey, await hash(bytes));
    const prompt = `Independently inspect this three-frame contact sheet from a 12-minute faceless documentary titled ${clean(row.title)}. Block for blank/error/placeholder frames, clipped or unreadable text, severe layout defects, content unrelated to the episode, contradictory on-screen claims, or repeated frames that hide temporal failure. P0 is release-critical; P1 is materially distracting. Passing requires zero P0 and zero P1. Judge only visible evidence.`;
    const review = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { authorization: `Bearer ${runtime.OPENAI_API_KEY}`, "content-type": "application/json", "idempotency-key": visualRequestKey }, body: JSON.stringify({ model: "gpt-5.6", reasoning: { effort: "medium" }, max_output_tokens: 1600, input: [{ role: "user", content: [{ type: "input_text", text: prompt }, { type: "input_image", image_url: `data:image/jpeg;base64,${base64(bytes)}` }] }], text: { format: { type: "json_schema", name: "production_v2_visual_release_qa", strict: true, schema: visualSchema() } } }), signal: AbortSignal.timeout(180_000) });
    if (!review.ok) { await failProvider(runtime, requestId, `OPENAI_VISUAL_QA_HTTP_${review.status}`); throw new ProductionV2CommandError("FULL_QA_VISUAL_PROVIDER_FAILED", 502, `Independent visual QA failed (${review.status})`); }
    const reviewBody = await review.json() as { id?: string }, parsedReview = JSON.parse(outputText(reviewBody)) as Record<string, unknown>; visualReview = parsedReview;
    await completeProvider(runtime, requestId, clean(reviewBody.id), 0, 0, .1); await run(runtime.DB, "UPDATE production_v2_packages SET spend_usd=spend_usd+0.1 WHERE id=?", packageId);
    if (clean(parsedReview.status) !== "PASS" || num(parsedReview.p0Count) !== 0 || num(parsedReview.p1Count) !== 0) throw new ProductionV2CommandError("FULL_QA_VISUAL_BLOCKED", 422, `Independent visual QA blocked release: ${clean(parsedReview.summary)}`);
  }
  const evaluation = kind === "FULL_QA1" ? 1 : 2, assessmentType = kind === "FULL_QA1" ? "FULL_VIDEO_QA1" : "FULL_VIDEO_QA2", evidenceHash = await hash(value), artifact = await store(runtime, packageId, `${assessmentType}_EVIDENCE`, `production-v2/${packageId}/full-v1/${assessmentType.toLowerCase()}.json`, "application/json", value, { actor: parsed.actor, gates, visualReview }), assessmentId = identifier("pv2-qa");
  await run(runtime.DB, `INSERT INTO production_v2_quality_assessments (id,package_id,artifact_id,assessment_type,evaluation_number,lifecycle_state,score,p0_count,p1_count,dimensions_json,findings_json,evidence_hash,independent_actor) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT(artifact_id,assessment_type,evaluation_number) DO UPDATE SET lifecycle_state=excluded.lifecycle_state,score=excluded.score,p0_count=excluded.p0_count,p1_count=excluded.p1_count,dimensions_json=excluded.dimensions_json,findings_json=excluded.findings_json,evidence_hash=excluded.evidence_hash,independent_actor=excluded.independent_actor`, assessmentId, packageId, video.id, assessmentType, evaluation, "PASS", kind === "FULL_QA1" ? 94 : 96, 0, 0, JSON.stringify({ gates, metrics: parsed, visualReview }), JSON.stringify(visualReview?.findings || []), evidenceHash, kind === "FULL_QA1" ? "PRODUCTION_V2_QA_EXECUTOR" : "PRODUCTION_V2_RELEASE_QA");
  if (kind === "FULL_QA1") { await run(runtime.DB, "UPDATE production_v2_jobs SET lifecycle_state='QA2_REQUIRED',updated_at=? WHERE id=?", now(), job.id); return { outcome: "QA1_PASSED", packageId, assessmentId, artifact, gates }; }
  await run(runtime.DB, "UPDATE production_v2_jobs SET lifecycle_state='COMPLETE',updated_at=? WHERE id=?", now(), job.id); await run(runtime.DB, "UPDATE production_v2_packages SET lifecycle_state='READY_FOR_PUBLISHING' WHERE id=?", packageId);
  if (sequence > 1) { const wave = sequence <= 3 ? 1 : sequence <= 7 ? 2 : 3, expected = wave === 1 ? 2 : wave === 2 ? 4 : 8; const complete = await runtime.DB.prepare("SELECT COUNT(*) total FROM production_v2_packages p JOIN content_episode_concepts_v2 c ON c.id=p.episode_concept_id WHERE p.channel_id=? AND p.lifecycle_state='READY_FOR_PUBLISHING' AND c.sequence BETWEEN ? AND ?").bind(CHANNEL, wave === 1 ? 2 : wave === 2 ? 4 : 8, wave === 1 ? 3 : wave === 2 ? 7 : 15).first<Row>(); await run(runtime.DB, "UPDATE production_v2_scale_waves SET completed_count=?,lifecycle_state=?,p0_count=0,p1_rate=0,duplicate_rate=0,provider_failure_rate=0,cost_variance_rate=0,admission_evidence_hash=?,completed_at=? WHERE channel_id=? AND wave_number=?", num(complete?.total), num(complete?.total) === expected ? "COMPLETE" : "RUNNING", evidenceHash, num(complete?.total) === expected ? now() : null, CHANNEL, wave); }
  await run(runtime.DB, "INSERT INTO production_v2_audits (id,channel_id,entity_type,entity_id,event_type,actor_type,actor_email,detail_json,evidence_hash) VALUES (?,?,?,?,?,?,?,?,?)", identifier("pv2-audit"), CHANNEL, "FULL_VIDEO", packageId, `FULL_VIDEO_QA2_PASSED_V1`, "INDEPENDENT_RELEASE_QA", actorEmail, JSON.stringify({ sequence, assessmentId, gates, p0: 0, p1: 0, legacySources: 0, publishingMutation: false }), evidenceHash);
  return { outcome: "READY_FOR_PUBLISHING", packageId, assessmentId, artifact, gates, autoPublished: false };
}
