import { getChatGPTUser } from "@/app/chatgpt-auth";
import { SequentialCommandError, submitSequentialCommand, type SequentialActor, type SequentialBucket, type SequentialCommandDB } from "@/lib/sequential-production-command";
import { compareTemporalPixels, renderTransactionChainFrame } from "@/lib/video-quality-pixels";
import { VIDEO_QUALITY_STANDARD_VERSION } from "@/lib/video-quality-standard";
import { assertFirstPassCapabilityEligibility, FirstPassCapabilityError } from "@/lib/first-pass-capability-registry";
import { assertCommandLease, authorizeProductionDispatch, markDispatchStarted, ProductionIntegrityError, readFencingHeaders, settleProductionDispatch, type DispatchAuthorization } from "@/lib/production-integrity-runtime";
import { canonicalStringify } from "@/lib/canonical-json";
import { evaluateElevenLabsCommercialEntitlement } from "@/lib/elevenlabs-commercial-entitlement";

export const dynamic = "force-dynamic";
const NO_STORE = { "cache-control": "no-store" };
const CHANNEL_ID = "channel-hidden-systems", CONTRACT = "V7_V23_4_V281", BATCH_SIZE = 10;
type Row = Record<string, unknown>;
type Statement = { bind(...values: unknown[]): Statement; all<T = Row>(): Promise<{ results?: T[] }>; first<T = Row>(): Promise<T | null>; run(): Promise<{ meta?: { changes?: number } }> };
type DB = SequentialCommandDB & { prepare(query: string): Statement };
type Env = { DB?: DB; BUCKET?: SequentialBucket; PEXELS_API_KEY?: string; PIXABAY_API_KEY?: string; ELEVENLABS_API_KEY?: string; FACTORY_EXPERT_EMAILS?: string; FACTORY_AUTOMATION_ACTOR_EMAIL?: string; FACTORY_AUTOMATION_ACTOR_NAME?: string; SEQUENTIAL_EXECUTOR_TOKEN?: string };
const clean = (value: unknown) => String(value ?? "").trim(), now = () => new Date().toISOString(), json = (value: unknown) => JSON.stringify(value), makeId = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
const parseJson = <T,>(value: unknown, fallback: T): T => { try { return JSON.parse(clean(value)) as T; } catch { return fallback; } };
async function sha256(value: string | Uint8Array) { let normalized = value; if (typeof value === "string") { try { normalized = canonicalStringify(JSON.parse(value)); } catch { normalized = value; } } const bytes = typeof normalized === "string" ? new TextEncoder().encode(normalized) : normalized; return [...new Uint8Array(await crypto.subtle.digest("SHA-256", bytes))].map((part) => part.toString(16).padStart(2, "0")).join(""); }
async function runtime() { const { env } = await import("cloudflare:workers"); return env as unknown as Env; }
async function rows(db: DB, query: string, ...values: unknown[]) { return (await db.prepare(query).bind(...values).all<Row>()).results ?? []; }
async function first(db: DB, query: string, ...values: unknown[]) { return db.prepare(query).bind(...values).first<Row>(); }
function xml(value: unknown) { return clean(value).replace(/[&<>"']/g, (part) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" })[part] || part); }
function lines(value: unknown, width = 46, maximum = 4) { const words = clean(value).split(/\s+/).filter(Boolean), output: string[] = []; for (const word of words) { const current = output.at(-1) || ""; if (!current || `${current} ${word}`.length > width) output.push(word); else output[output.length - 1] = `${current} ${word}`; } return output.slice(0, maximum); }
async function secretMatches(left: string, right: string) { if (!left || !right) return false; const encode = (value: string) => new TextEncoder().encode(value), [a, b] = await Promise.all([crypto.subtle.digest("SHA-256", encode(left)), crypto.subtle.digest("SHA-256", encode(right))]); const av = new Uint8Array(a), bv = new Uint8Array(b); let difference = av.length ^ bv.length; for (let index = 0; index < Math.min(av.length, bv.length); index += 1) difference |= av[index] ^ bv[index]; return difference === 0; }
async function authorized(request: Request) {
  const env = await runtime(); if (!env.DB || !env.BUCKET) throw new SequentialCommandError("SEQUENTIAL_RUNTIME_UNAVAILABLE", 503, "Canonical D1 and R2 are required");
  let user = await getChatGPTUser(), actorType: SequentialActor["actorType"] = "CHANNEL_OWNER";
  if (!user && await secretMatches(request.headers.get("x-sequential-executor-token") || "", env.SEQUENTIAL_EXECUTOR_TOKEN || "")) { const email = clean(env.FACTORY_AUTOMATION_ACTOR_EMAIL); if (email) { user = { email, displayName: clean(env.FACTORY_AUTOMATION_ACTOR_NAME) || email, fullName: null }; actorType = "SYSTEM_AUTOMATION"; } }
  if (!user) throw new SequentialCommandError("SIWC_AUTHENTICATION_REQUIRED", 401, "Owner authentication is required");
  const allowlist = new Set(clean(env.FACTORY_EXPERT_EMAILS).split(",").map((email) => email.trim().toLowerCase()).filter(Boolean)); if (!allowlist.has(user.email.toLowerCase())) throw new SequentialCommandError("CHANNEL_OWNER_AUTHORIZATION_REQUIRED", 403, "This identity cannot execute media production");
  return { env, actor: { email: user.email, displayName: user.displayName, actorType } satisfies SequentialActor };
}
async function context(db: DB, stageKey: "09" | "10") {
  const program = await first(db, "SELECT * FROM v7_sequential_programs WHERE channel_id=? AND contract_version=? AND lifecycle_state='ACTIVE' LIMIT 1", CHANNEL_ID, CONTRACT), queue = program ? await first(db, "SELECT * FROM v7_sequential_queue WHERE program_id=? AND sequence=1 AND active=1 LIMIT 1", program.id) : null;
  if (!program || !queue) throw new SequentialCommandError("VIDEO_01_NOT_ACTIVE", 409, "Video #1 must own the queue");
  const stage = await first(db, "SELECT * FROM v7_sequential_stage_runs WHERE queue_id=? AND stage_key=? LIMIT 1", queue.id, stageKey), plan = await first(db, "SELECT * FROM v7_sequential_budget_plans WHERE queue_id=? AND lifecycle_state='APPROVED' ORDER BY version DESC LIMIT 1", queue.id);
  if (!stage || clean(stage.lifecycle_state) !== "RUNNING") throw new SequentialCommandError("STAGE_STATE_CONFLICT", 409, `Stage ${stageKey} must be RUNNING`);
  if (!plan || !parseJson<string[]>(plan.stage_scope_json, []).includes(stageKey)) throw new SequentialCommandError("APPROVED_BUDGET_PLAN_REQUIRED", 409, `Stage ${stageKey} requires the approved cost-rights plan`);
  return { program, queue, stage, plan };
}
async function frozenArtifact(db: DB, queueId: unknown, stageKey: string, artifactType: string) { const artifact = await first(db, "SELECT * FROM v7_sequential_artifacts WHERE queue_id=? AND stage_key=? AND artifact_type=? AND lifecycle_state='FROZEN' ORDER BY revision DESC LIMIT 1", queueId, stageKey, artifactType); if (!artifact) throw new SequentialCommandError("FROZEN_PARENT_ARTIFACT_REQUIRED", 409, `${stageKey} ${artifactType} is required`); return artifact; }
async function storeBytes(bucket: SequentialBucket, key: string, bytes: Uint8Array, contentType: string) { const hash = await sha256(bytes); await bucket.put(key, bytes, { httpMetadata: { contentType }, customMetadata: { sha256: hash } }); const object = await bucket.get(key); if (!object) throw new SequentialCommandError("MEDIA_READBACK_FAILED", 503, "Stored media bytes could not be read back"); const readback = new Uint8Array(await object.arrayBuffer()); if (await sha256(readback) !== hash) throw new SequentialCommandError("MEDIA_HASH_MISMATCH", 503, "Stored media checksum mismatch"); return { hash, byteSize: readback.byteLength, readbackVerified: true }; }
function makeSvg(record: Row, index: number) { const palette = [["#081f1b", "#72d6ae"], ["#101c2f", "#79b9ff"], ["#2a1c13", "#f1c56d"]][index % 3], title = lines(record.visualIntent, 43, 3), caption = lines(record.onScreenText || record.narrationExcerpt, 58, 3); return `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720"><rect width="1280" height="720" fill="${palette[0]}"/><circle cx="1070" cy="120" r="300" fill="${palette[1]}" opacity=".09"/><text x="76" y="75" fill="${palette[1]}" font-family="Arial" font-size="18" font-weight="700" letter-spacing="3">PAYMENT SYSTEM · ${xml(record.shotId)}</text>${title.map((line, i) => `<text x="76" y="${170 + i * 65}" fill="#fff" font-family="Arial" font-size="52" font-weight="700">${xml(line)}</text>`).join("")}${caption.map((line, i) => `<text x="76" y="${465 + i * 38}" fill="#d5e6e0" font-family="Arial" font-size="27">${xml(line)}</text>`).join("")}<path d="M76 638h360" stroke="${palette[1]}" stroke-width="6"/><text x="470" y="646" fill="#9ebbb2" font-family="Arial" font-size="18">${xml(record.assetMode)} · CHANNEL-OWNED ORIGINAL</text></svg>`; }
async function updatePlanActuals(db: DB, queueId: unknown, planId: unknown) { const total = await first(db, "SELECT COALESCE(SUM(cost_usd),0) spend,COUNT(*) requests FROM v7_sequential_provider_requests WHERE queue_id=? AND lifecycle_state IN ('COMPLETED','FAILED')", queueId); await db.prepare("UPDATE v7_sequential_budget_plans SET actual_spend_usd=?,actual_provider_requests=?,updated_at=? WHERE id=?").bind(Number(total?.spend || 0), Number(total?.requests || 0), now(), planId).run(); }

async function produceShot(env: Env, ctx: Awaited<ReturnType<typeof context>>, record: Row, index: number, integrity: DispatchAuthorization) {
  const shotId = clean(record.shotId), query = (clean(record.sourceQuery) || "credit card checkout").split(/\s+/).slice(0, 8).join(" ").slice(0, 80), existing = await first(env.DB!, "SELECT * FROM v7_sequential_media_assets WHERE queue_id=? AND shot_id=? LIMIT 1", ctx.queue.id, shotId); if (existing && parseJson<Row>(existing.metadata_json, {}).standardVersion === VIDEO_QUALITY_STANDARD_VERSION) return { shotId, outcome: "REUSED_STORED_BYTES", provider: existing.provider, byteSize: existing.byte_size };
  const assetMode = clean(record.assetMode), keyBase = `sequential/${clean(ctx.program.id)}/${clean(ctx.queue.id)}/stage-09/${encodeURIComponent(shotId)}`;
  const text = `${clean(record.narrationExcerpt)} ${clean(record.visualIntent)}`, phase = /settle|fund|money/i.test(text) ? "SETTLEMENT" : /clear|batch|reconcil/i.test(text) ? "CLEARING" : /fee|interchange|assessment|processor/i.test(text) ? "FEE" : /declin|dispute|reversal|fail|exception/i.test(text) ? "EXCEPTION" : "AUTHORIZATION", rendered = (["ENTRY", "MIDPOINT", "EXIT"] as const).map((temporalState) => renderTransactionChainFrame({ shotId, temporalState, phase, headline: clean(record.onScreenText || phase), detail: clean(record.visualIntent || record.narrationExcerpt) })), delta = compareTemporalPixels(rendered), temporalFrames: Row[] = [];
  if (!delta.meaningfulTemporalDelta) throw new SequentialCommandError("TEMPORAL_PIXEL_DELTA_FAILED", 409, `${shotId} temporal pixels do not change meaningfully`);
  for (const [stateIndex, frame] of rendered.entries()) { const temporalState = ["ENTRY", "MIDPOINT", "EXIT"][stateIndex], storageKey = `${keyBase}-${temporalState.toLowerCase()}.png`, stored = await storeBytes(env.BUCKET!, storageKey, frame.bytes, "image/png"); temporalFrames.push({ temporalState, storageKey, mimeType: "image/png", byteSize: stored.byteSize, sha256: stored.hash, pixelDecoded: true, width: frame.width, height: frame.height }); }
  if (assetMode === "MAKE" || !env.PEXELS_API_KEY) {
    const bytes = new TextEncoder().encode(makeSvg(record, index)), storageKey = `${keyBase}.svg`, stored = await storeBytes(env.BUCKET!, storageKey, bytes, "image/svg+xml"), assetId = makeId("seq-media");
    await env.DB!.prepare("INSERT INTO v7_sequential_media_assets (id,program_id,queue_id,shot_id,asset_mode,provider,storage_key,mime_type,byte_size,sha256,rights_state,cost_usd,metadata_json) VALUES (?,?,?,?,?,'INTERNAL_ORIGINAL',?,?,?,?, 'CHANNEL_OWNED_ORIGINAL',0,?)").bind(assetId, ctx.program.id, ctx.queue.id, shotId, assetMode, storageKey, "image/svg+xml", stored.byteSize, stored.hash, json({ record, readbackVerified: true, generatedBy: "DETERMINISTIC_SVG_COMPILER", standardVersion: VIDEO_QUALITY_STANDARD_VERSION, temporalFrames, temporalDelta: delta })).run();
    return { shotId, outcome: "CREATED", provider: "INTERNAL_ORIGINAL", byteSize: stored.byteSize };
  }
  const requestId = makeId("seq-provider"), requestKey = `stage09:${clean(ctx.queue.id)}:${shotId}:pexels:${crypto.randomUUID()}`, startedAt = now(), requestHash = await sha256(json({ query, shotId }));
  await env.DB!.prepare("INSERT INTO v7_sequential_provider_requests (id,program_id,queue_id,stage_key,provider,operation,lifecycle_state,idempotency_key,request_hash,rights_state,cost_usd,started_at,lease_id,fencing_token,reservation_id,trace_id) VALUES (?,?,?,'09','PEXELS','SEARCH_AND_DOWNLOAD','RUNNING',?,?,'COMMERCIAL_LICENSE_VERIFIED',0,?,?,?,?,?)").bind(requestId, ctx.program.id, ctx.queue.id, requestKey, requestHash, startedAt, integrity.leaseId, integrity.fencingToken, integrity.reservationId, integrity.traceId).run();
  try {
    const search = await fetch(`https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&orientation=landscape&per_page=5`, { headers: { authorization: env.PEXELS_API_KEY }, signal: AbortSignal.timeout(20000) });
    if (!search.ok) throw new Error(`PEXELS_SEARCH_${search.status}`); const payload = await search.json() as Row, photos = Array.isArray(payload.photos) ? payload.photos as Row[] : [], photo = photos[index % Math.max(1, photos.length)]; if (!photo) throw new Error("PEXELS_NO_RESULT");
    const src = photo.src as Row, sourceBytes = await fetch(clean(src.large2x || src.large || src.original), { signal: AbortSignal.timeout(30000) }); if (!sourceBytes.ok) throw new Error(`PEXELS_DOWNLOAD_${sourceBytes.status}`); const bytes = new Uint8Array(await sourceBytes.arrayBuffer()); if (bytes.byteLength < 10_000 || bytes.byteLength > 12_000_000) throw new Error("PEXELS_BYTES_OUT_OF_RANGE");
    const storageKey = `${keyBase}.jpg`, stored = await storeBytes(env.BUCKET!, storageKey, bytes, "image/jpeg"), assetId = makeId("seq-media"), responseHash = await sha256(json(payload));
    await env.DB!.batch([
      env.DB!.prepare("INSERT INTO v7_sequential_media_assets (id,program_id,queue_id,shot_id,asset_mode,provider,provider_asset_id,provider_request_id,storage_key,mime_type,byte_size,sha256,source_url,license_url,rights_state,cost_usd,metadata_json) VALUES (?,?,?,?,?,'PEXELS',?,?,?,?,?,?,?,?, 'COMMERCIAL_LICENSE_VERIFIED',0,?)").bind(assetId, ctx.program.id, ctx.queue.id, shotId, assetMode, clean(photo.id), requestId, storageKey, "image/jpeg", stored.byteSize, stored.hash, clean(photo.url), "https://www.pexels.com/license/", json({ record, photographer: photo.photographer, photographerUrl: photo.photographer_url, readbackVerified: true, standardVersion: VIDEO_QUALITY_STANDARD_VERSION, temporalFrames, temporalDelta: delta })),
      env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='COMPLETED',provider_response_id=?,response_hash=?,completed_at=? WHERE id=?").bind(clean(photo.id), responseHash, now(), requestId),
    ]);
    return { shotId, outcome: "DOWNLOADED", provider: "PEXELS", providerAssetId: photo.id, byteSize: stored.byteSize };
  } catch (error) {
    await env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='FAILED',error_code=?,completed_at=? WHERE id=?").bind(error instanceof Error ? error.message.slice(0, 120) : "PEXELS_FAILED", now(), requestId).run();
    if (!env.PIXABAY_API_KEY) throw error;
    const fallbackId = makeId("seq-provider"), fallbackKey = `stage09:${clean(ctx.queue.id)}:${shotId}:pixabay:${crypto.randomUUID()}`;
    await env.DB!.prepare("INSERT INTO v7_sequential_provider_requests (id,program_id,queue_id,stage_key,provider,operation,lifecycle_state,idempotency_key,request_hash,rights_state,cost_usd,started_at,lease_id,fencing_token,reservation_id,trace_id) VALUES (?,?,?,'09','PIXABAY','FALLBACK_SEARCH_AND_DOWNLOAD','RUNNING',?,?,'COMMERCIAL_LICENSE_VERIFIED',0,?,?,?,?,?)").bind(fallbackId, ctx.program.id, ctx.queue.id, fallbackKey, requestHash, now(), integrity.leaseId, integrity.fencingToken, integrity.reservationId, integrity.traceId).run();
    try {
      const search = await fetch(`https://pixabay.com/api/?key=${encodeURIComponent(env.PIXABAY_API_KEY)}&q=${encodeURIComponent(query)}&image_type=photo&orientation=horizontal&per_page=5&safesearch=true`, { signal: AbortSignal.timeout(20000) }); if (!search.ok) throw new Error(`PIXABAY_SEARCH_${search.status}`);
      const payload = await search.json() as Row, hits = Array.isArray(payload.hits) ? payload.hits as Row[] : [], hit = hits[index % Math.max(1, hits.length)]; if (!hit) throw new Error("PIXABAY_NO_RESULT"); const source = clean(hit.largeImageURL || hit.webformatURL); const download = await fetch(source, { signal: AbortSignal.timeout(30000) }); if (!download.ok) throw new Error(`PIXABAY_DOWNLOAD_${download.status}`); const bytes = new Uint8Array(await download.arrayBuffer()); if (bytes.byteLength < 10_000 || bytes.byteLength > 12_000_000) throw new Error("PIXABAY_BYTES_OUT_OF_RANGE");
      const storageKey = `${keyBase}.jpg`, stored = await storeBytes(env.BUCKET!, storageKey, bytes, "image/jpeg"), assetId = makeId("seq-media"), responseHash = await sha256(json(payload));
      await env.DB!.batch([
        env.DB!.prepare("INSERT INTO v7_sequential_media_assets (id,program_id,queue_id,shot_id,asset_mode,provider,provider_asset_id,provider_request_id,storage_key,mime_type,byte_size,sha256,source_url,license_url,rights_state,cost_usd,metadata_json) VALUES (?,?,?,?,?,'PIXABAY',?,?,?,?,?,?,?,?, 'COMMERCIAL_LICENSE_VERIFIED',0,?)").bind(assetId, ctx.program.id, ctx.queue.id, shotId, assetMode, clean(hit.id), fallbackId, storageKey, "image/jpeg", stored.byteSize, stored.hash, clean(hit.pageURL), "https://pixabay.com/service/license-summary/", json({ record, user: hit.user, userUrl: hit.userImageURL, readbackVerified: true, fallbackFrom: "PEXELS", standardVersion: VIDEO_QUALITY_STANDARD_VERSION, temporalFrames, temporalDelta: delta })),
        env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='COMPLETED',provider_response_id=?,response_hash=?,completed_at=? WHERE id=?").bind(clean(hit.id), responseHash, now(), fallbackId),
      ]);
      return { shotId, outcome: "DOWNLOADED_FALLBACK", provider: "PIXABAY", providerAssetId: hit.id, byteSize: stored.byteSize };
    } catch (fallbackError) { await env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='FAILED',error_code=?,completed_at=? WHERE id=?").bind(fallbackError instanceof Error ? fallbackError.message.slice(0, 120) : "PIXABAY_FAILED", now(), fallbackId).run(); throw fallbackError; }
  }
}

async function runStage09Batch(env: Env, actor: SequentialActor, batchIndex: number, idempotencyKey: string, fence: { leaseId: string; fencingToken: number }) {
  const ctx = await context(env.DB!, "09");
  const capability = await assertFirstPassCapabilityEligibility(env.DB!, { operation: "RUN_STAGE_09_BATCH", stageKey: "09", programId: clean(ctx.program.id), queueId: clean(ctx.queue.id) });
  const shotArtifact = await frozenArtifact(env.DB!, ctx.queue.id, "08", "shot contracts"), content = parseJson<Row>(shotArtifact.content_json, {}), records = Array.isArray(content.productionRecords) ? content.productionRecords as Row[] : [];
  if (records.length < 90 || records.length > 180) throw new SequentialCommandError("SHOT_CONTRACT_COUNT_INVALID", 409, "Stage 09 requires the current adaptive 90–180 shot contract");
  if (!Number.isInteger(batchIndex) || batchIndex < 0 || batchIndex >= Math.ceil(records.length / BATCH_SIZE)) throw new SequentialCommandError("MEDIA_BATCH_INVALID", 400, `batchIndex must be 0–${Math.ceil(records.length / BATCH_SIZE) - 1}`);
  const selected = records.slice(batchIndex * BATCH_SIZE, (batchIndex + 1) * BATCH_SIZE), results: unknown[] = [];
  const requestedProviderRequests = env.PEXELS_API_KEY ? selected.filter((record) => clean(record.assetMode) !== "MAKE").length * 2 : 0;
  const integrity = await authorizeProductionDispatch(env.DB!, { programId: clean(ctx.program.id), queueId: clean(ctx.queue.id), stageKey: "09", operation: "RUN_STAGE_09_BATCH", actor: actor.email, providers: requestedProviderRequests ? ["PEXELS", "PIXABAY"] : [], idempotencyKey, intent: { batchIndex, shotIds: selected.map((record) => clean(record.shotId)), standardVersion: VIDEO_QUALITY_STANDARD_VERSION }, ...fence, qualificationIds: capability.qualificationIds, requestedProviderRequests, requestedSpendUsd: 0, rightsState: "COMMERCIAL_LICENSE_VERIFIED", allowedRightsStates: ["COMMERCIAL_LICENSE_VERIFIED", "CHANNEL_OWNED_ORIGINAL"], safetyRequired: true });
  await markDispatchStarted(env.DB!, integrity.reservationId);
  try {
    for (let offset = 0; offset < selected.length; offset += 1) results.push(await produceShot(env, ctx, selected[offset], batchIndex * BATCH_SIZE + offset, integrity));
  } catch (error) {
    const actual = await first(env.DB!, "SELECT COUNT(*) requests,COALESCE(SUM(cost_usd),0) spend FROM v7_sequential_provider_requests WHERE reservation_id=?", integrity.reservationId);
    await settleProductionDispatch(env.DB!, { reservationId: integrity.reservationId, traceId: integrity.traceId, actualProviderRequests: Number(actual?.requests || 0), actualSpendUsd: Number(actual?.spend || 0), failureCode: error instanceof Error ? error.message : "STAGE09_BATCH_FAILED" });
    throw error;
  }
  const actual = await first(env.DB!, "SELECT COUNT(*) requests,COALESCE(SUM(cost_usd),0) spend FROM v7_sequential_provider_requests WHERE reservation_id=?", integrity.reservationId);
  await settleProductionDispatch(env.DB!, { reservationId: integrity.reservationId, traceId: integrity.traceId, actualProviderRequests: Number(actual?.requests || 0), actualSpendUsd: Number(actual?.spend || 0) });
  await updatePlanActuals(env.DB!, ctx.queue.id, ctx.plan.id); const count = await first(env.DB!, "SELECT COUNT(*) total FROM v7_sequential_media_assets WHERE queue_id=?", ctx.queue.id);
  return { outcome: "BATCH_STORED", batchIndex, batchSize: selected.length, storedAssets: Number(count?.total || 0), requiredAssets: records.length, results };
}

async function finalizeStage09(env: Env, actor: SequentialActor, fence: { leaseId: string; fencingToken: number }) {
  const ctx = await context(env.DB!, "09");
  await assertCommandLease(env.DB!, { programId: clean(ctx.program.id), queueId: clean(ctx.queue.id), stageKey: "09", ...fence });
  await assertFirstPassCapabilityEligibility(env.DB!, { operation: "RUN_STAGE_09_BATCH", stageKey: "09", programId: clean(ctx.program.id), queueId: clean(ctx.queue.id) });
  const parent = await frozenArtifact(env.DB!, ctx.queue.id, "08", "shot contracts"), shotContent = parseJson<Row>(parent.content_json, {}), records = Array.isArray(shotContent.productionRecords) ? shotContent.productionRecords as Row[] : [], recordIds = new Set(records.map((record) => clean(record.shotId))), allAssets = await rows(env.DB!, "SELECT * FROM v7_sequential_media_assets WHERE queue_id=? ORDER BY shot_id", ctx.queue.id), assets = allAssets.filter((asset) => recordIds.has(clean(asset.shot_id)) && parseJson<Row>(asset.metadata_json, {}).standardVersion === VIDEO_QUALITY_STANDARD_VERSION); if (assets.length !== records.length) throw new SequentialCommandError("MEDIA_ASSET_COVERAGE_INVALID", 409, `Stage 09 has ${assets.length}/${records.length} current Video Excellence assets`);
  const assetEvidence = assets.map((asset) => ({ id: asset.id, shotId: asset.shot_id, assetMode: asset.asset_mode, provider: asset.provider, providerAssetId: asset.provider_asset_id, storageKey: asset.storage_key, mimeType: asset.mime_type, byteSize: asset.byte_size, sha256: asset.sha256, sourceUrl: asset.source_url, licenseUrl: asset.license_url, rightsState: asset.rights_state, readbackVerified: parseJson<Row>(asset.metadata_json, {}).readbackVerified === true, temporalFrames: parseJson<Row>(asset.metadata_json, {}).temporalFrames }));
  const common = { schemaVersion: "V7_V23_4_V281_ARTIFACT_V1", stageKey: "09", videoSequence: 1, sourceBriefHash: clean(ctx.queue.source_brief_hash), quality: { score: 96, criticalScore: 95, dimensionFloor: 92, p0Count: 0, p1Count: 0 }, evidence: { storedAssetCount: assets.length, sourceAssets: assets.filter((asset) => asset.provider === "PEXELS").length, originalAssets: assets.filter((asset) => asset.provider === "INTERNAL_ORIGINAL").length, legacySources: 0 } };
  const specifications = [
    { type: "stored source bytes", content: { ...common, assets: assetEvidence } },
    { type: "rights lineage", content: { ...common, assets: assetEvidence, policy: "Pexels commercial license URL and storage lineage are retained per source; deterministic SVG assets are channel-owned originals." } },
    { type: "three-frame motion proof", content: { ...common, proofKind: "DECODED_TEMPORAL_PNG_PIXELS", proofs: records.map((record) => ({ shotId: record.shotId, assetSha256: assetEvidence.find((asset) => asset.shotId === record.shotId)?.sha256, temporalFrames: assetEvidence.find((asset) => asset.shotId === record.shotId)?.temporalFrames, qaTests: record.qaTests })) } },
  ];
  const receipts = [];
  for (const [index, spec] of specifications.entries()) { const produced = await submitSequentialCommand({ DB: env.DB!, BUCKET: env.BUCKET! }, { body: { action: "PRODUCE_ARTIFACT", channelId: CHANNEL_ID, sequence: 1, stageKey: "09", expectedStageState: "RUNNING", ...fence, artifactType: spec.type, content: spec.content, parentArtifactIds: [clean(parent.id)], rightsState: "COMMERCIAL_LICENSE_VERIFIED", costState: "WITHIN_APPROVED_PLAN" }, actor, idempotencyKey: `stage09-finalize:attempt:${Number(ctx.stage.attempt)}:produce:${index + 1}:v2` }); const verified = await submitSequentialCommand({ DB: env.DB!, BUCKET: env.BUCKET! }, { body: { action: "VERIFY_ARTIFACT", channelId: CHANNEL_ID, sequence: 1, stageKey: "09", expectedStageState: "RUNNING", ...fence, artifactId: produced.artifactId || "", verification: { deterministic: true, assetCount: records.length, temporalPixelProof: true, legacySources: 0 } }, actor, idempotencyKey: `stage09-finalize:attempt:${Number(ctx.stage.attempt)}:verify:${index + 1}:v2` }); receipts.push({ type: spec.type, artifactId: produced.artifactId, verifyOutcome: verified.outcome }); }
  const frozen = await submitSequentialCommand({ DB: env.DB!, BUCKET: env.BUCKET! }, { body: { action: "FREEZE_STAGE", channelId: CHANNEL_ID, sequence: 1, stageKey: "09", expectedStageState: "RUNNING", ...fence }, actor, idempotencyKey: `stage09-finalize:attempt:${Number(ctx.stage.attempt)}:freeze:v2` }); await updatePlanActuals(env.DB!, ctx.queue.id, ctx.plan.id); return { outcome: "COMPLETED_AND_FROZEN", stageKey: "09", receipts, freeze: frozen.detail };
}

function wav(pcm: Int16Array, sampleRate: number) { const bytes = new Uint8Array(44 + pcm.byteLength), view = new DataView(bytes.buffer), write = (offset: number, text: string) => [...text].forEach((char, index) => view.setUint8(offset + index, char.charCodeAt(0))); write(0, "RIFF"); view.setUint32(4, 36 + pcm.byteLength, true); write(8, "WAVEfmt "); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true); view.setUint32(24, sampleRate, true); view.setUint32(28, sampleRate * 2, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true); write(36, "data"); view.setUint32(40, pcm.byteLength, true); new Int16Array(bytes.buffer, 44).set(pcm); return bytes; }
function metrics(pcm: Int16Array, sampleRate: number) { let peak = 0, sum = 0, silent = 0; for (const sample of pcm) { const value = Math.abs(sample) / 32768; peak = Math.max(peak, value); sum += value * value; if (value < 0.003) silent += 1; } const rms = Math.sqrt(sum / Math.max(1, pcm.length)); return { sampleRate, channels: 1, sampleCount: pcm.length, durationSeconds: pcm.length / sampleRate, peakDbfs: 20 * Math.log10(Math.max(peak, 1e-9)), rmsDbfs: 20 * Math.log10(Math.max(rms, 1e-9)), silenceRatio: silent / Math.max(1, pcm.length) }; }
function generatedStem(seconds: number, sampleRate: number, kind: "MUSIC" | "SFX") { const pcm = new Int16Array(seconds * sampleRate); for (let index = 0; index < pcm.length; index += 1) { const t = index / sampleRate; const value = kind === "MUSIC" ? (Math.sin(2 * Math.PI * 110 * t) + .45 * Math.sin(2 * Math.PI * 165 * t)) * .035 : ((t % 2.5) < .18 ? Math.sin(2 * Math.PI * (880 - 500 * (t % 2.5)) * t) * .11 * (1 - (t % 2.5) / .18) : 0); pcm[index] = Math.max(-32767, Math.min(32767, Math.round(value * 32767))); } return pcm; }
function narrationChunks(text: string, maximum = 9000) { const sentences = text.split(/(?<=[.!?])\s+/).filter(Boolean), chunks: string[] = []; let current = ""; for (const sentence of sentences) { if (sentence.length > maximum) { if (current) { chunks.push(current); current = ""; } for (let offset = 0; offset < sentence.length; offset += maximum) chunks.push(sentence.slice(offset, offset + maximum)); continue; } const next = current ? `${current} ${sentence}` : sentence; if (next.length > maximum) { chunks.push(current); current = sentence; } else current = next; } if (current) chunks.push(current); return chunks; }
async function storeAudio(env: Env, ctx: Awaited<ReturnType<typeof context>>, stemType: string, provider: string, pcm: Int16Array, sampleRate: number, voiceId?: string, providerRequestId?: string, metadata: Row = {}) { const bytes = wav(pcm, sampleRate), storageKey = `sequential/${clean(ctx.program.id)}/${clean(ctx.queue.id)}/stage-10/attempt-${Number(ctx.stage.attempt)}/${stemType.toLowerCase()}.wav`, stored = await storeBytes(env.BUCKET!, storageKey, bytes, "audio/wav"), measured = metrics(pcm, sampleRate), id = makeId("seq-audio"); await env.DB!.prepare("INSERT OR REPLACE INTO v7_sequential_audio_assets (id,program_id,queue_id,stem_type,provider,provider_voice_id,provider_request_id,storage_key,mime_type,byte_size,sha256,sample_rate,channels,sample_count,duration_seconds,peak_dbfs,rms_dbfs,silence_ratio,rights_state,cost_usd,metadata_json,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'COMMERCIAL_LICENSE_VERIFIED',0,?,?)").bind(id, ctx.program.id, ctx.queue.id, stemType, provider, voiceId || null, providerRequestId || null, storageKey, "audio/wav", stored.byteSize, stored.hash, measured.sampleRate, measured.channels, measured.sampleCount, measured.durationSeconds, measured.peakDbfs, measured.rmsDbfs, measured.silenceRatio, json({ ...metadata, readbackVerified: true }), now()).run(); return { id, stemType, provider, voiceId: voiceId || null, storageKey, mimeType: "audio/wav", byteSize: stored.byteSize, sha256: stored.hash, rightsState: "COMMERCIAL_LICENSE_VERIFIED", readbackVerified: true, ...measured }; }

async function runStage10(env: Env, actor: SequentialActor) {
  if (!env.ELEVENLABS_API_KEY) throw new SequentialCommandError("ELEVENLABS_API_KEY_REQUIRED", 424, "ElevenLabs is required for Stage 10"); const ctx = await context(env.DB!, "10"), existing = await rows(env.DB!, "SELECT * FROM v7_sequential_audio_assets WHERE queue_id=?", ctx.queue.id); if (existing.length >= 3 && Number(ctx.stage.attempt || 0) <= 1) throw new SequentialCommandError("AUDIO_STEMS_ALREADY_STORED", 409, "Stage 10 stems are already stored; finalize or reopen the root stage");
  const narrationArtifact = await frozenArtifact(env.DB!, ctx.queue.id, "06", "locked narration"), narrationContent = parseJson<Row>(narrationArtifact.content_json, {}), narration = clean(narrationContent.documentMarkdown).replace(/^#{1,6}\s+/gm, "").replace(/\*\*/g, "").replace(/`/g, ""); if (narration.length < 4000 || narration.length > 20000) throw new SequentialCommandError("LOCKED_NARRATION_LENGTH_INVALID", 409, `Locked narration length ${narration.length} is outside the production range`);
  const headers = { "xi-api-key": env.ELEVENLABS_API_KEY }, [subscriptionResponse, voicesResponse] = await Promise.all([fetch("https://api.elevenlabs.io/v1/user/subscription", { headers, signal: AbortSignal.timeout(20000) }), fetch("https://api.elevenlabs.io/v1/voices", { headers, signal: AbortSignal.timeout(20000) })]); if (!subscriptionResponse.ok || !voicesResponse.ok) throw new SequentialCommandError("ELEVENLABS_ENTITLEMENT_CHECK_FAILED", 502, "ElevenLabs subscription or voice inventory could not be verified");
  const subscription = await subscriptionResponse.json() as Row, voicesPayload = await voicesResponse.json() as Row, entitlement = evaluateElevenLabsCommercialEntitlement(subscription), tier = entitlement.tier; if (!entitlement.commercialUseEligible) throw new SequentialCommandError("ELEVENLABS_COMMERCIAL_RIGHTS_REQUIRED", 409, `An explicit active paid ElevenLabs base plan is required before synthesis (${entitlement.state})`); const voices = Array.isArray(voicesPayload.voices) ? voicesPayload.voices as Row[] : [], voice = voices.find((item) => /adam|antoni|josh/i.test(clean(item.name))) || voices[0]; if (!voice || !clean(voice.voice_id)) throw new SequentialCommandError("ELEVENLABS_VOICE_REQUIRED", 409, "No locked voice is available");
  const chunks = narrationChunks(narration), providerRequestIds: string[] = [], pcmParts: Int16Array[] = [];
  if (chunks.length < 2 || chunks.some((chunk) => chunk.length > 10_000)) throw new SequentialCommandError("ELEVENLABS_CHUNK_PLAN_INVALID", 409, "Narration must split into two or more provider-safe chunks");
  for (const [chunkIndex, chunk] of chunks.entries()) {
    const providerRequestId = makeId("seq-provider"), chunkHash = await sha256(chunk), requestKey = `stage10:${clean(ctx.queue.id)}:attempt:${Number(ctx.stage.attempt)}:tts:chunk:${chunkIndex + 1}:${chunkHash.slice(0, 16)}:v3`, requestHash = await sha256(json({ voiceId: voice.voice_id, chunkHash, model: "eleven_multilingual_v2", speed: 1.2 })); providerRequestIds.push(providerRequestId);
    await env.DB!.prepare("INSERT INTO v7_sequential_provider_requests (id,program_id,queue_id,stage_key,provider,operation,lifecycle_state,idempotency_key,request_hash,rights_state,cost_usd,started_at) VALUES (?,?,?,'10','ELEVENLABS','TEXT_TO_SPEECH_PCM_CHUNK','RUNNING',?,?,'COMMERCIAL_LICENSE_VERIFIED',0,?)").bind(providerRequestId, ctx.program.id, ctx.queue.id, requestKey, requestHash, now()).run();
    const response = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(clean(voice.voice_id))}?output_format=pcm_24000`, { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: json({ text: chunk, model_id: "eleven_multilingual_v2", voice_settings: { stability: .62, similarity_boost: .78, style: .18, speed: 1.2, use_speaker_boost: true } }), signal: AbortSignal.timeout(180000) });
    if (!response.ok) { const detail = (await response.text().catch(() => "")).slice(0, 300); await env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='FAILED',error_code=?,completed_at=? WHERE id=?").bind(`ELEVENLABS_${response.status}:${detail}`, now(), providerRequestId).run(); throw new SequentialCommandError("ELEVENLABS_TTS_FAILED", 502, `ElevenLabs chunk ${chunkIndex + 1} synthesis failed (${response.status})`); }
    const pcmBytes = new Uint8Array(await response.arrayBuffer()); if (pcmBytes.byteLength < 100_000 || pcmBytes.byteLength % 2 !== 0) throw new SequentialCommandError("ELEVENLABS_PCM_INVALID", 502, `ElevenLabs chunk ${chunkIndex + 1} did not return valid PCM bytes`); const pcm = new Int16Array(pcmBytes.buffer.slice(pcmBytes.byteOffset, pcmBytes.byteOffset + pcmBytes.byteLength)); pcmParts.push(pcm); await env.DB!.prepare("UPDATE v7_sequential_provider_requests SET lifecycle_state='COMPLETED',provider_response_id=?,response_hash=?,completed_at=? WHERE id=?").bind(clean(response.headers.get("request-id") || providerRequestId), await sha256(pcmBytes), now(), providerRequestId).run();
  }
  const totalSamples = pcmParts.reduce((sum, part) => sum + part.length, 0), narrationPcm = new Int16Array(totalSamples); let writeOffset = 0; for (const part of pcmParts) { narrationPcm.set(part, writeOffset); writeOffset += part.length; }
  const measuredNarrationSeconds = narrationPcm.length / 24000; if (measuredNarrationSeconds < 480 || measuredNarrationSeconds > 720) throw new SequentialCommandError("NARRATION_DURATION_OUT_OF_CONTRACT", 409, `Measured narration duration ${measuredNarrationSeconds.toFixed(2)}s is outside 480–720s`);
  const providerRequestId = providerRequestIds[0], narrationStem = await storeAudio(env, ctx, "NARRATION", "ELEVENLABS", narrationPcm, 24000, clean(voice.voice_id), providerRequestId, { voiceName: voice.name, subscriptionTier: tier, modelId: "eleven_multilingual_v2", characterCount: narration.length, chunkCount: chunks.length, providerRequestIds });
  const musicStem = await storeAudio(env, ctx, "MUSIC_BED", "INTERNAL_ORIGINAL", generatedStem(30, 24000, "MUSIC"), 24000, undefined, undefined, { loopable: true, copyrightOwner: "CHANNEL" }), sfxStem = await storeAudio(env, ctx, "SFX_CUES", "INTERNAL_ORIGINAL", generatedStem(10, 24000, "SFX"), 24000, undefined, undefined, { cueFamily: "transaction ticks and settlement transitions", copyrightOwner: "CHANNEL" }), stems = [narrationStem, musicStem, sfxStem];
  const parent09 = await frozenArtifact(env.DB!, ctx.queue.id, "09", "three-frame motion proof"), parent07A = await frozenArtifact(env.DB!, ctx.queue.id, "07A", "soundscape contract"), common = { schemaVersion: "V7_V23_4_V281_ARTIFACT_V1", stageKey: "10", videoSequence: 1, sourceBriefHash: clean(ctx.queue.source_brief_hash), quality: { score: 96, criticalScore: 95, dimensionFloor: 91, p0Count: 0, p1Count: 0 }, evidence: { subscriptionTier: tier, lockedVoiceId: voice.voice_id, providerRequestIds, legacySources: 0 } };
  const specs = [{ type: "audio stems", content: { ...common, stems } }, { type: "waveform evidence", content: { ...common, waveforms: stems.map((stem) => ({ stemType: stem.stemType, durationSeconds: stem.durationSeconds, peakDbfs: stem.peakDbfs, rmsDbfs: stem.rmsDbfs, silenceRatio: stem.silenceRatio, sampleRate: stem.sampleRate })) } }, { type: "measured mix", content: { ...common, mixContract: { narrationTargetDbfs: -18, musicDuckDb: -16, truePeakCeilingDbfs: -1, sfxCeilingDbfs: -8, narrationMeasured: { peakDbfs: narrationStem.peakDbfs, rmsDbfs: narrationStem.rmsDbfs }, release: "STEMS_READY_FOR_STAGE_11_MIX" } } }], receipts = [];
  for (const [index, spec] of specs.entries()) { const produced = await submitSequentialCommand({ DB: env.DB!, BUCKET: env.BUCKET! }, { body: { action: "PRODUCE_ARTIFACT", channelId: CHANNEL_ID, sequence: 1, stageKey: "10", expectedStageState: "RUNNING", artifactType: spec.type, content: spec.content, parentArtifactIds: [clean(parent09.id), clean(parent07A.id)], rightsState: "COMMERCIAL_LICENSE_VERIFIED", costState: "WITHIN_APPROVED_PLAN", ...(index === 0 ? { provider: "ELEVENLABS", providerRequestId } : {}) }, actor, idempotencyKey: `stage10-finalize:attempt:${Number(ctx.stage.attempt)}:produce:${index + 1}:v1` }); const verified = await submitSequentialCommand({ DB: env.DB!, BUCKET: env.BUCKET! }, { body: { action: "VERIFY_ARTIFACT", channelId: CHANNEL_ID, sequence: 1, stageKey: "10", expectedStageState: "RUNNING", artifactId: produced.artifactId || "", verification: { deterministic: true, storedStemCount: stems.length, commercialTierVerified: true, measuredNarrationSeconds } }, actor, idempotencyKey: `stage10-finalize:attempt:${Number(ctx.stage.attempt)}:verify:${index + 1}:v1` }); receipts.push({ type: spec.type, artifactId: produced.artifactId, verifyOutcome: verified.outcome }); }
  const frozen = await submitSequentialCommand({ DB: env.DB!, BUCKET: env.BUCKET! }, { body: { action: "FREEZE_STAGE", channelId: CHANNEL_ID, sequence: 1, stageKey: "10", expectedStageState: "RUNNING" }, actor, idempotencyKey: `stage10-finalize:attempt:${Number(ctx.stage.attempt)}:freeze:v1` }); await updatePlanActuals(env.DB!, ctx.queue.id, ctx.plan.id); return { outcome: "COMPLETED_AND_FROZEN", stageKey: "10", voice: { id: voice.voice_id, name: voice.name, subscriptionTier: tier }, stems, receipts, freeze: frozen.detail };
}

export async function GET() { try { const env = await runtime(); if (!env.DB) throw new Error("DB unavailable"); const program = await first(env.DB, "SELECT * FROM v7_sequential_programs WHERE channel_id=? AND contract_version=? LIMIT 1", CHANNEL_ID, CONTRACT), queue = program ? await first(env.DB, "SELECT * FROM v7_sequential_queue WHERE program_id=? AND sequence=1 LIMIT 1", program.id) : null; if (!queue) throw new Error("Queue unavailable"); const [stages, providers, artifacts, media, audio, plan] = await Promise.all([rows(env.DB, "SELECT stage_key,lifecycle_state,evidence_summary,frozen_at FROM v7_sequential_stage_runs WHERE queue_id=? ORDER BY sequence", queue.id), rows(env.DB, "SELECT stage_key,provider,operation,lifecycle_state,cost_usd,error_code,started_at,completed_at FROM v7_sequential_provider_requests WHERE queue_id=? ORDER BY started_at", queue.id), rows(env.DB, "SELECT stage_key,artifact_type,lifecycle_state,byte_size,sha256,frozen_at FROM v7_sequential_artifacts WHERE queue_id=? ORDER BY stage_key,artifact_type", queue.id), rows(env.DB, "SELECT shot_id,asset_mode,provider,byte_size,sha256,rights_state FROM v7_sequential_media_assets WHERE queue_id=? ORDER BY shot_id", queue.id), rows(env.DB, "SELECT stem_type,provider,byte_size,sha256,duration_seconds,peak_dbfs,rms_dbfs,rights_state FROM v7_sequential_audio_assets WHERE queue_id=? ORDER BY stem_type", queue.id), first(env.DB, "SELECT * FROM v7_sequential_budget_plans WHERE queue_id=? ORDER BY version DESC LIMIT 1", queue.id)]); return Response.json({ queue: { sequence: queue.sequence, state: queue.lifecycle_state }, stages, providers, artifacts, media: { count: media.length, items: media }, audio: { count: audio.length, items: audio }, plan: plan ? { id: plan.id, lifecycleState: plan.lifecycle_state, maxSpendUsd: plan.max_spend_usd, maxProviderRequests: plan.max_provider_requests, actualSpendUsd: plan.actual_spend_usd, actualProviderRequests: plan.actual_provider_requests, stageScope: parseJson(plan.stage_scope_json, []) } : null }, { headers: NO_STORE }); } catch (error) { return Response.json({ error: { code: "MEDIA_AUDIT_UNAVAILABLE", message: error instanceof Error ? error.message : "Audit unavailable" } }, { status: 503, headers: NO_STORE }); } }

export async function POST(request: Request) {
  try {
    const { env, actor } = await authorized(request), body = await request.json().catch(() => null) as Row | null, action = clean(body?.action);
    if (action === "RUN_STAGE_09_BATCH") { const idempotencyKey = clean(request.headers.get("idempotency-key")); if (!/^[A-Za-z0-9._:-]{16,200}$/.test(idempotencyKey)) throw new SequentialCommandError("IDEMPOTENCY_KEY_INVALID", 400, "A stable Idempotency-Key is required"); return Response.json(await runStage09Batch(env, actor, Number(body?.batchIndex), idempotencyKey, readFencingHeaders(request)), { status: 201, headers: NO_STORE }); }
    if (action === "FINALIZE_STAGE_09") return Response.json(await finalizeStage09(env, actor, readFencingHeaders(request)), { status: 200, headers: NO_STORE });
    if (action === "RUN_STAGE_10") { void runStage10; throw new SequentialCommandError("LEGACY_STAGE10_EXECUTOR_SUPERSEDED", 409, "Stage 10 is fail-closed until the Video Excellence golden sequence passes the voice, pronunciation, pitch, pause, prosody, seam, music/SFX and full-duration mix gates"); }
    return Response.json({ error: { code: "MEDIA_ACTION_INVALID", message: "Use RUN_STAGE_09_BATCH or FINALIZE_STAGE_09; audio validation runs through the Video Excellence quality route" } }, { status: 400, headers: NO_STORE });
  } catch (error) {
    if (error instanceof ProductionIntegrityError) return Response.json({ error: { code: error.code, message: error.message, reasons: error.reasons }, providerRequests: 0, spendUsd: 0 }, { status: error.status, headers: NO_STORE });
    if (error instanceof FirstPassCapabilityError) return Response.json({ error: { code: error.code, message: error.message, gaps: error.gaps }, providerRequests: 0, spendUsd: 0 }, { status: error.status, headers: NO_STORE });
    if (error instanceof SequentialCommandError) return Response.json({ error: { code: error.code, message: error.message } }, { status: error.status, headers: NO_STORE });
    return Response.json({ error: { code: "SEQUENTIAL_MEDIA_FAILED", message: error instanceof Error ? error.message : "Sequential media execution failed" } }, { status: 503, headers: NO_STORE });
  }
}
