"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

type Gate={id:string;label:string;status:string;evidence:string};
type Run={id:string;status:string;score:number;attempt:number;threshold:number;gates:Gate[];startedAt:string};
type Job={id:string;status:string;providerStatus:string;startedAt:string;error:string|null};
type Artifact={id:string;lifecycleState:string;contentHash:string;content:Record<string,unknown>};
type Data={provider:{connected:boolean;model:string};upstreamReady:boolean;stage:{status:string;threshold:number;attempt:number;evidenceSummary:string};runs:Run[];jobs:Job[];artifacts:Artifact[]};
const list=<T,>(value:unknown)=>Array.isArray(value)?value as T[]:[];const human=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/(^|\s)\S/g,(letter)=>letter.toUpperCase());

export default function StoryArchitecturePage(){
  const[data,setData]=useState<Data|null>(null);const[working,setWorking]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[clock,setClock]=useState(()=>Date.now());
  const load=useCallback(async()=>{const response=await fetch("/api/factory/story-architecture",{cache:"no-store"});const payload=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(payload.error||"Story Architecture could not load");setData(payload);return payload;},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load().catch((reason)=>setError(reason instanceof Error?reason.message:"Unable to load")),0);return()=>window.clearTimeout(timer);},[load]);useEffect(()=>{const timer=window.setInterval(()=>setClock(Date.now()),1000);return()=>window.clearInterval(timer);},[]);
  async function request(action:"RUN"|"POLL"){const response=await fetch("/api/factory/story-architecture",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})});const payload=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(payload.error||"Stage 05 stopped");setData(payload);return payload;}
  async function run(){setWorking(true);setError("");setNotice("Story room accepted · constructing and challenging the full narrative architecture…");try{let payload=data?.jobs.some((job)=>job.status==="ACTIVE")?data!:await request("RUN");const started=Date.now();let transient=0;while(Date.now()-started<12*60*1000){const latest=payload.runs[0];if(latest&&latest.status!=="RUNNING"){setNotice(latest.status==="PASS"?`Story Architecture frozen at ${latest.score}/${latest.threshold}. Stage 06 is authorized.`:"Story Architecture stopped at a hard gate. A bounded repair is available.");return;}await new Promise((resolve)=>window.setTimeout(resolve,3000));try{payload=await request("POLL");transient=0;}catch(reason){transient+=1;if(transient>=5)throw reason;setNotice(`Story room remains safe in the background · reconnecting ${transient}/5…`);await new Promise((resolve)=>window.setTimeout(resolve,5000));}}throw new Error("Stage 05 is still running safely. Use Resume Stage 05 to continue monitoring.");}catch(reason){setError(reason instanceof Error?reason.message:"Stage 05 failed");}finally{setWorking(false);}}
  const runResult=data?.runs[0]||null;const job=data?.jobs.find((item)=>item.status==="ACTIVE");const artifact=data?.artifacts[0]||null;const content=artifact?.content||{};const acts=list<Record<string,unknown>>(content.acts);const beats=list<Record<string,unknown>>(content.beats);const critics=list<Record<string,unknown>>(content.critics);const risks=list<Record<string,unknown>>(content.adversarialRisks);const gatePass=useMemo(()=>runResult?.gates.filter((gate)=>gate.status==="PASS").length||0,[runResult]);const elapsed=job?Math.max(0,Math.floor((clock-new Date(job.startedAt).getTime())/1000)):0;
  if(!data)return <main className="creativeLoading"><span>05</span><h1>Loading Story Architecture Studio…</h1>{error&&<p>{error}</p>}</main>;const frozen=data.stage.status==="FROZEN";
  return <main className="creativeShell">
    <header className="creativeTop"><div><Link href="/control-plane">← V7 Control Plane</Link><p>PRODUCTION V7 · STAGE 05</p><h1>Story Architecture Studio</h1></div><div><span className={frozen?"pass":"pending"}>{human(data.stage.status)}</span><Link href="/creative-contract">Frozen Creative Contract</Link></div></header>
    {error&&<div className="creativeAlert"><strong>Execution stopped</strong><span>{error}</span></div>}
    <section className="creativeHero"><div><p>PRODUCTION-BINDING STORY SYSTEM</p><h2>Every beat must change what the viewer understands.</h2><span>Three acts, a continuous editorial clock, evidence-bound claims, retention promises, meaning-bearing visuals and narrative sound functions are adjudicated together.</span></div><aside><small>HARD FLOOR</small><strong>{runResult?runResult.score:data.stage.threshold}<i>/100</i></strong><span>{runResult?`${gatePass}/${runResult.gates.length} gates passed`:`≥${data.stage.threshold} required`}</span></aside></section>
    <section className="creativeControl"><div><small>UPSTREAM</small><strong>{data.upstreamReady?"Stage 04 frozen":"Creative Contract blocked"}</strong></div><div><small>MODEL</small><strong>{data.provider.connected?`${data.provider.model} · high reasoning`:"OpenAI connection required"}</strong></div><div><small>ATTEMPT POLICY</small><strong>{data.stage.attempt}/3 · bounded repair</strong></div><button disabled={working||frozen||!data.upstreamReady||!data.provider.connected} onClick={()=>void run()}>{working?`Architecting · ${elapsed}s`:frozen?"Story Architecture frozen":job?"Resume Stage 05":data.stage.status==="REPAIR_REQUIRED"?"Run bounded repair":"Run Stage 05 Autopilot"}</button></section>
    {notice&&<div className="creativeNotice"><span>✓</span>{notice}</div>}
    {!artifact&&<section className="creativePreflight"><header><div><small>PRE-FLIGHT</small><h2>One run creates the complete story contract</h2></div><span>{data.upstreamReady?"AUTHORIZED":"BLOCKED"}</span></header><div>{[["01","Three-act escalation","A contradiction develops into mechanism, consequence and payoff."],["02","Continuous beat clock","Every second belongs to one explicit narrative job."],["03","Evidence-bound progression","Every factual beat inherits only controlled claim IDs."],["04","Independent hard gates","Retention, story, evidence, visual and sound critics can block handoff."]].map(([number,title,copy])=><article key={number}><span>{number}</span><div><strong>{title}</strong><p>{copy}</p></div></article>)}</div></section>}
    {artifact&&<><section className="creativeTournament"><header><div><p>THREE-ACT ARCHITECTURE</p><h2>{String(content.title)}</h2></div><span>{artifact.lifecycleState}</span></header><div className="creativeCandidates">{acts.map((act)=><article key={String(act.id)}><header><span>{String(act.id)}</span><b>{Math.round(Number(act.endSeconds)-Number(act.startSeconds))}<i>s</i></b></header><h3>{String(act.title)}</h3><p>{String(act.dramaticJob)}</p><footer>{String(act.actPayoff)}</footer></article>)}</div><div className="creativeDecision"><small>CENTRAL DRAMATIC QUESTION</small><h3>{String(content.centralDramaticQuestion)}</h3><p>{beats.length} production-binding beats · {String(content.runtimeSeconds)} seconds · zero decorative scenes authorized.</p></div></section>
    <section className="creativeContract"><header><div><p>BEAT-BY-BEAT VIEWER PROGRESSION</p><h2>Continuous editorial clock</h2></div><span>{beats.length} beats</span></header><div className="creativeRisks">{beats.map((beat)=><article key={String(beat.id)}><span>{String(beat.id)}</span><div><strong>{String(beat.title)} · {String(beat.startSeconds)}–{String(beat.endSeconds)}s</strong><p>{String(beat.viewerBefore)} → {String(beat.viewerAfter)}</p><small>{String(beat.visualGrammar)} · SOUND: {String(beat.soundFunction)}</small></div><b>{String(beat.cognitiveLoad)}</b></article>)}</div></section>
    <section className="creativeQA"><header><div><p>INDEPENDENT STORY ADJUDICATION</p><h2>Every specialist can block Stage 06.</h2></div><span>{critics.length} critics · {risks.filter((risk)=>risk.status==="RESOLVED").length}/{risks.length} risks resolved</span></header><div className="creativeCritics">{critics.map((critic,index)=><article key={index}><header><strong>{String(critic.role)}</strong><b>{String(critic.score)}</b></header><p>{String(critic.verdict)}</p><small>{String(critic.requiredControl)}</small></article>)}</div></section>
    {runResult&&<section className="creativeGates"><header><div><p>DETERMINISTIC MICRO-QA</p><h2>{runResult.status==="PASS"?"PASS":"REPAIR REQUIRED"} · {runResult.score}/{runResult.threshold}</h2></div><span>No average can compensate for a failed hard gate</span></header><div>{runResult.gates.map((gate)=><article key={gate.id}><span className={gate.status.toLowerCase()}>{gate.status==="PASS"?"✓":"!"}</span><div><strong>{gate.label}</strong><p>{gate.evidence}</p></div></article>)}</div></section>}</>}
    <footer className="creativeFooter"><div><strong>Stage 05 release rule</strong><span>Script Development remains blocked until one stored Story Architecture freezes with zero failed hard gates.</span></div>{frozen?<Link href="/control-plane">Stage 06 is ready · open Control Plane →</Link>:<Link href="/creative-contract">Inspect frozen Creative Contract →</Link>}</footer>
  </main>;
}
