"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

type Gate={id:string;label:string;status:string;evidence:string};
type Run={id:string;status:string;score:number;attempt:number;threshold:number;gates:Gate[];startedAt:string;completedAt:string|null};
type Job={id:string;runId:string;status:string;providerStatus:string;startedAt:string;heartbeatAt:string;error:string|null};
type Artifact={id:string;lifecycleState:string;contentHash:string;createdAt:string;content:Record<string,unknown>};
type Data={provider:{connected:boolean;model:string};upstreamReady:boolean;stage:{stageKey:string;stageName:string;status:string;threshold:number;attempt:number;blocker:string|null;evidenceSummary:string};runs:Run[];jobs:Job[];artifacts:Artifact[]};

const list=<T,>(value:unknown)=>Array.isArray(value)?value as T[]:[];
const object=(value:unknown)=>value&&typeof value==="object"?value as Record<string,unknown>:{};
const human=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/(^|\s)\S/g,(letter)=>letter.toUpperCase());

export default function CreativeContractPage(){
  const[data,setData]=useState<Data|null>(null);const[working,setWorking]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[clock,setClock]=useState(()=>Date.now());
  const load=useCallback(async()=>{const response=await fetch("/api/factory/creative-contract",{cache:"no-store"});const payload=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(payload.error||"Creative Contract could not load");setData(payload);return payload;},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load().catch((reason)=>setError(reason instanceof Error?reason.message:"Unable to load")),0);return()=>window.clearTimeout(timer);},[load]);
  useEffect(()=>{const timer=window.setInterval(()=>setClock(Date.now()),1000);return()=>window.clearInterval(timer);},[]);
  async function request(action:"RUN"|"POLL"|"REPAIR_SCORING"){const response=await fetch("/api/factory/creative-contract",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})});const payload=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(payload.error||"Stage 04 stopped");setData(payload);return payload;}
  async function run(){setWorking(true);setError("");setNotice("Creative board accepted · four routes are being generated and independently challenged…");try{let payload=data?.jobs.some((job)=>job.status==="ACTIVE")?data!:await request("RUN");const started=Date.now();let transient=0;while(Date.now()-started<12*60*1000){const latest=payload.runs[0];if(latest&&latest.status!=="RUNNING"){setNotice(latest.status==="PASS"?`Creative Contract frozen at ${latest.score}/${latest.threshold}. Stage 05 is authorized.`:"Creative Contract stopped at a hard gate. A bounded repair attempt is available.");return;}await new Promise((resolve)=>window.setTimeout(resolve,3000));try{payload=await request("POLL");transient=0;}catch(reason){transient+=1;if(transient>=5)throw reason;setNotice(`Creative board remains safe in the background · reconnecting ${transient}/5…`);await new Promise((resolve)=>window.setTimeout(resolve,5000));continue;}const job=payload.jobs.find((item)=>item.status==="ACTIVE");const elapsed=Math.max(0,Math.floor((Date.now()-new Date(job?.startedAt||Date.now()).getTime())/1000));setNotice(`Stage 04 · ${human(job?.providerStatus||"finalizing")} · ${Math.floor(elapsed/60)}m ${elapsed%60}s · resumable`);}throw new Error("Stage 04 is still running safely. Use Resume Stage 04 to continue monitoring.");}catch(reason){setError(reason instanceof Error?reason.message:"Stage 04 failed");}finally{setWorking(false);}}
  const runResult=data?.runs[0]||null;const job=data?.jobs.find((item)=>item.status==="ACTIVE");const artifact=data?.artifacts[0]||null;const content=artifact?.content||{};const candidates=list<Record<string,unknown>>(content.candidates);const contract=object(content.contract);const critics=list<Record<string,unknown>>(content.critics);const risks=list<Record<string,unknown>>(content.adversarialRisks);const champion=candidates.find((candidate)=>candidate.id===content.championId);const elapsed=job?Math.max(0,Math.floor((clock-new Date(job.startedAt).getTime())/1000)):0;
  const gatePass=useMemo(()=>runResult?.gates.filter((gate)=>gate.status==="PASS").length||0,[runResult]);
  if(!data)return <main className="creativeLoading"><span>04</span><h1>Loading Creative Contract Foundry…</h1>{error&&<p>{error}</p>}</main>;
  const frozen=data.stage.status==="FROZEN";const scoreValues=candidates.flatMap((candidate)=>Object.values(object(candidate.scores)).map(Number));const scoringRepairAvailable=data.stage.status==="REPAIR_REQUIRED"&&scoreValues.length>0&&scoreValues.every((value)=>Number.isFinite(value)&&value>=0&&value<=10)&&runResult?.gates.some((gate)=>gate.id==="CHAMPION"&&gate.status==="FAIL");
  async function repairScoring(){setWorking(true);setError("");setNotice("Normalizing the candidate score contract to 0–100 and re-adjudicating without a new AI run…");try{const payload=await request("REPAIR_SCORING");setNotice(`Creative Contract frozen at ${payload.runs[0]?.score||100}/100. Stage 05 is authorized.`);}catch(reason){setError(reason instanceof Error?reason.message:"Scoring repair failed");}finally{setWorking(false);}}
  return <main className="creativeShell">
    <header className="creativeTop"><div><Link href="/intelligence">← Wave 2 Intelligence</Link><p>PRODUCTION V7 · STAGE 04</p><h1>Creative Contract Foundry</h1></div><div><span className={frozen?"pass":"pending"}>{human(data.stage.status)}</span><Link href="/control-plane">V7 Control Plane</Link></div></header>
    {error&&<div className="creativeAlert"><strong>Execution stopped</strong><span>{error}</span></div>}
    <section className="creativeHero"><div><p>BINDING CREATIVE DECISION</p><h2>Turn evidence into one ownable viewer experience.</h2><span>Four genuinely different routes compete. Seven specialist critics challenge the winner. Story cannot begin until audience, narrative, visual, sound, originality and evidence promises all freeze together.</span></div><aside><small>HARD FLOOR</small><strong>{runResult?runResult.score:data.stage.threshold}<i>/100</i></strong><span>{runResult?`${gatePass}/${runResult.gates.length} gates passed`:`≥${data.stage.threshold} required`}</span></aside></section>
    <section className="creativeControl"><div><small>UPSTREAM</small><strong>{data.upstreamReady?"Stages 01–03 frozen":"Evidence blocked"}</strong></div><div><small>MODEL</small><strong>{data.provider.connected?`${data.provider.model} · high reasoning`:"OpenAI connection required"}</strong></div><div><small>ATTEMPT POLICY</small><strong>{data.stage.attempt}/3 · bounded repair</strong></div><button disabled={working||frozen||!data.upstreamReady||(!scoringRepairAvailable&&!data.provider.connected)} onClick={()=>void(scoringRepairAvailable?repairScoring():run())}>{working?scoringRepairAvailable?"Repairing score contract…":`Adjudicating · ${elapsed}s`:frozen?"Creative Contract frozen":scoringRepairAvailable?"Repair scoring contract · no AI rerun":job?"Resume Stage 04":data.stage.status==="REPAIR_REQUIRED"?"Run bounded repair":"Run Stage 04 Autopilot"}</button></section>
    {notice&&<div className="creativeNotice"><span>✓</span>{notice}</div>}
    {!artifact&&<section className="creativePreflight"><header><div><small>PRE-FLIGHT</small><h2>One run creates a production-binding artifact</h2></div><span>{data.upstreamReady?"AUTHORIZED":"BLOCKED"}</span></header><div>{[["01","Audience promise","One primary viewer and a measurable before/after transformation."],["02","Creative tournament","Four differentiated story engines with evidence-bound scores."],["03","Independent panel","Executive, audience, story, visual, sound, factual and originality critics."],["04","Hard freeze","R2 and Google Drive archive plus zero open adversarial risk."]].map(([number,title,copy])=><article key={number}><span>{number}</span><div><strong>{title}</strong><p>{copy}</p></div></article>)}</div></section>}
    {artifact&&<>
      <section className="creativeTournament"><header><div><p>CANDIDATE TOURNAMENT</p><h2>Four routes entered. One contract survived.</h2></div><span>{artifact.lifecycleState}</span></header><div className="creativeCandidates">{candidates.map((candidate)=>{const scores=object(candidate.scores);const winner=candidate.id===content.championId;return <article key={String(candidate.id)} className={winner?"winner":""}><header><span>{winner?"CHAMPION":"CHALLENGER"}</span><b>{String(candidate.totalScore)}<i>/100</i></b></header><h3>{String(candidate.name)}</h3><p>{String(candidate.oneSentencePromise)}</p><div>{Object.entries(scores).map(([key,value])=><span key={key}><small>{human(key)}</small><strong>{String(value)}</strong></span>)}</div><footer>{String(candidate.differentiation)}</footer></article>})}</div>{champion&&<div className="creativeDecision"><small>ADJUDICATED DECISION</small><h3>{String(champion.name)}</h3><p>{String(content.championRationale)}</p></div>}</section>
      <section className="creativeContract"><header><div><p>REAL DELIVERABLE · FROZEN CONTRACT</p><h2>{String(content.publicWorkingTitle)}</h2></div><span>{artifact.lifecycleState} · SHA {artifact.contentHash.slice(0,12)}…</span></header><div className="creativeContractGrid">{[["Primary viewer",content.primaryViewer],["Transformation",content.transformation],["Central question",content.centralQuestion],["Audience promise",contract.audiencePromise],["Thesis",contract.thesis],["Story engine",contract.storyEngine],["Emotional arc",contract.emotionalArc],["Stakes",contract.stakes],["Payoff",contract.payoff],["Runtime",`${contract.runtimeTargetSeconds}s · ${contract.spokenWordRange}`],["Hook contract",contract.hookContract],["Midpoint contract",contract.midpointContract],["Ending contract",contract.endingContract],["Visual engine",contract.visualEngine],["Sound engine",contract.soundEngine]].map(([label,value])=><article key={String(label)}><small>{String(label)}</small><p>{String(value||"")}</p></article>)}</div>
        <div className="creativeSystems">{[["Visual families",contract.visualFamilies],["Visual prohibitions",contract.visualProhibitions],["Sound motifs",contract.soundMotifs],["Sound prohibitions",contract.soundProhibitions],["Originality controls",contract.originalityControls],["Acceptance tests",contract.acceptanceTests]].map(([label,items])=><article key={String(label)}><h3>{String(label)}</h3><ol>{list<string>(items).map((item,index)=><li key={index}>{item}</li>)}</ol></article>)}</div>
      </section>
      <section className="creativeQA"><header><div><p>INDEPENDENT ADJUDICATION</p><h2>Every specialist can block handoff.</h2></div><span>{critics.length} critics · {risks.filter((risk)=>risk.status==="RESOLVED").length}/{risks.length} risks resolved</span></header><div className="creativeCritics">{critics.map((critic,index)=><article key={index}><header><strong>{String(critic.role)}</strong><b>{String(critic.score)}</b></header><p>{String(critic.verdict)}</p><small>{String(critic.requiredControl)}</small></article>)}</div><div className="creativeRisks">{risks.map((risk,index)=><article key={index}><span>{String(risk.severity)}</span><div><strong>{String(risk.risk)}</strong><p>{String(risk.resolution)}</p><small>Acceptance · {String(risk.acceptanceTest)}</small></div><b>{String(risk.status)}</b></article>)}</div></section>
      {runResult&&<section className="creativeGates"><header><div><p>DETERMINISTIC MICRO-QA</p><h2>{runResult.status==="PASS"?"PASS":"REPAIR REQUIRED"} · {runResult.score}/{runResult.threshold}</h2></div><span>No critic score can compensate for a failed hard gate</span></header><div>{runResult.gates.map((gate)=><article key={gate.id}><span className={gate.status.toLowerCase()}>{gate.status==="PASS"?"✓":"!"}</span><div><strong>{gate.label}</strong><p>{gate.evidence}</p></div></article>)}</div></section>}
    </>}
    <footer className="creativeFooter"><div><strong>Stage 04 release rule</strong><span>Story Architecture remains blocked until one stored Creative Contract freezes with zero failed hard gates.</span></div>{frozen?<Link href="/control-plane">Stage 05 is ready · open Control Plane →</Link>:<Link href="/intelligence">Inspect frozen evidence →</Link>}</footer>
  </main>;
}
