"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense, useEffect, useState } from "react";
import type { FormEvent } from "react";
import type { ChannelStudioProjection, ContentBand } from "../channel-studio-contract";
import type { ContentPlanningProjection } from "../content-planning-contract";
import { FactoryShell, ProjectionState, StatusPill } from "../factory-shell";

const bands: ContentBand[] = ["OPPORTUNITY", "BACKLOG", "PLANNED", "PRODUCTION", "TERMINAL", "UNKNOWN"];
const escalationDefaults = ["Material strategy change", "Evidence contradiction or readiness below policy", "Legal, safety or unsupported-claim risk", "Cost above the per-video ceiling", "Repair limit exhausted", "Publishing outside approved boundaries"];

function Axes({ item }: { item: ContentPlanningProjection["opportunities"][number] }) { return <div className="cpAxes"><span><small>Strategy fit</small><strong>{item.axes.strategyFit}</strong></span><span><small>Demand</small><strong>{item.axes.audienceDemand}</strong></span><span><small>Differentiate</small><strong>{item.axes.differentiation}</strong></span><span><small>Evidence</small><strong>{item.axes.evidenceReadiness}</strong></span></div>; }

function AutopilotWorkspace({ data, refresh }: { data: ChannelStudioProjection; refresh: () => void }) {
  const planning = data.contentPlanning;
  const [status, setStatus] = useState("IDLE"), [message, setMessage] = useState<string | null>(null);
  if (!planning || !data.selectedChannel) return <section className="cpUnavailable"><h2>Content System & Planning unavailable</h2><p>The projection failed closed; no local or demonstration plan was substituted.</p></section>;
  async function command(action: "CONFIGURE_AUTOMATION_POLICY" | "RUN_CONTENT_AUTOPILOT" | "PAUSE_AUTOPILOT" | "RESUME_AUTOPILOT" | "EMERGENCY_STOP", policy?: Record<string, unknown>) {
    setStatus("SUBMITTING"); setMessage(null);
    try {
      const response = await fetch("/api/factory/content-autopilot", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": `content:${planning.channelId}:${action.toLowerCase()}:${Date.now()}` }, body: JSON.stringify({ action, channelId: planning.channelId, expectedPolicyVersion: planning.policy.version, expectedRunVersion: planning.run.version, ...(policy ? { policy } : {}) }) });
      const payload = await response.json() as { outcome?: string; error?: { message?: string } };
      if (!response.ok) throw new Error(payload.error?.message || "Content Autopilot command failed");
      setStatus("RECORDED"); setMessage(`${action.replaceAll("_", " ")} · ${payload.outcome}`); refresh();
    } catch (error) { setStatus("ERROR"); setMessage(error instanceof Error ? error.message : "Content Autopilot command failed"); }
  }
  function configure(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); command("CONFIGURE_AUTOMATION_POLICY", { mode: String(form.get("mode")), dailyBudgetUsd: Number(form.get("dailyBudgetUsd")), monthlyBudgetUsd: Number(form.get("monthlyBudgetUsd")), perVideoCostCeilingUsd: Number(form.get("perVideoCostCeilingUsd")), cadencePerMonth: Number(form.get("cadencePerMonth")), repairLimit: Number(form.get("repairLimit")), riskTolerance: String(form.get("riskTolerance")), autoProduction: form.get("autoProduction") === "on", autoPublish: form.get("autoPublish") === "on", escalationRules: String(form.get("escalationRules")).split("\n").map((item) => item.trim()).filter(Boolean) }); }
  const runReady = planning.strategy.state === "ACTIVE" && planning.policy.state === "ACTIVE";
  return <>
    <section className="cpHero">
      <div><small>CONTENT SYSTEM & PLANNING V1 · AUTOPILOT-FIRST</small><h2>{planning.handoff.state === "READY_FOR_PRODUCTION" ? `${planning.summary.briefsReady} briefs ready for production` : "Turn one active strategy into a repeatable publishing system."}</h2><p>{planning.strategy.viewerPromise || "An active strategy viewer promise is required."}</p><div className="cpHeroBadges"><StatusPill tone={planning.policy.state === "ACTIVE" ? "good" : "warn"}>{planning.policy.mode || "POLICY REQUIRED"}</StatusPill><span>Policy v{planning.policy.version}</span><span>Strategy v{planning.strategy.version}</span><span>Run v{planning.run.version}</span></div></div>
      <aside><div><small>PILLARS</small><strong>{planning.summary.pillars}</strong></div><div><small>SERIES</small><strong>{planning.summary.series}</strong></div><div><small>OPPORTUNITIES</small><strong>{planning.summary.opportunities}</strong></div><div><small>BRIEFS READY</small><strong>{planning.summary.briefsReady}</strong></div><div><small>OPEN EXCEPTIONS</small><strong>{planning.summary.openExceptions}</strong></div><div><small>PLANNING SPEND</small><strong>${planning.summary.spendUsd.toFixed(2)}</strong></div></aside>
    </section>
    <section className="cpPath" aria-label="Content System and Planning slices">{["Authority", "Content system", "Backlog", "Editorial plan", "Brief compiler", "Orchestrator", "Production FE", "Production QA"].map((label, index) => <article className={(index === 0 ? planning.policy.version : index < 6 ? planning.run.version : planning.run.state === "COMPLETE" ? 1 : 0) ? "done" : ""} key={label}><span>0{index + 1}</span><strong>{label}</strong><small>{index === 0 ? planning.policy.state : index < 6 ? planning.run.state : planning.run.state === "COMPLETE" ? "ACCEPTANCE CANDIDATE" : "PENDING"}</small></article>)}</section>
    <div className="cpControlGrid">
      <section className="cpPolicy"><header><div><small>SLICE 1 · AUTOMATION POLICY & AUTHORITY</small><h2>Owner sets the envelope once.</h2><p>Autopilot acts only inside this versioned policy. Strategic, risk and cost exceptions return to the owner.</p></div><StatusPill tone={planning.policy.state === "ACTIVE" ? "good" : planning.policy.state === "EMERGENCY_STOPPED" ? "bad" : "warn"}>{planning.policy.state}</StatusPill></header>
        <form onSubmit={configure}><label><span>Operating mode</span><select name="mode" defaultValue={planning.policy.mode || "FULL_AUTOPILOT"}><option value="FULL_AUTOPILOT">Full Autopilot</option><option value="EXCEPTIONS_ONLY">Exceptions only</option><option value="EXPERT_REVIEW">Expert review</option></select></label><label><span>Risk tolerance</span><select name="riskTolerance" defaultValue={planning.policy.riskTolerance || "LOW"}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label><span>Daily budget · USD</span><input name="dailyBudgetUsd" type="number" min="0" step="0.01" defaultValue={planning.policy.dailyBudgetUsd || 25} /></label><label><span>Monthly budget · USD</span><input name="monthlyBudgetUsd" type="number" min="0" step="0.01" defaultValue={planning.policy.monthlyBudgetUsd || 500} /></label><label><span>Per-video ceiling · USD</span><input name="perVideoCostCeilingUsd" type="number" min="0" step="0.01" defaultValue={planning.policy.perVideoCostCeilingUsd || 40} /></label><label><span>Videos per month</span><input name="cadencePerMonth" type="number" min="1" max="60" defaultValue={planning.policy.cadencePerMonth || 8} /></label><label><span>Automatic repair limit</span><input name="repairLimit" type="number" min="0" max="4" defaultValue={planning.policy.repairLimit || 1} /></label><div className="cpSwitches"><label><input name="autoProduction" type="checkbox" defaultChecked={planning.policy.autoProduction} /><span>Authorize automatic production handoff</span></label><label><input name="autoPublish" type="checkbox" defaultChecked={planning.policy.autoPublish} /><span>Authorize automatic publishing after downstream QA</span></label></div><label className="wide"><span>Mandatory escalation rules · one per line</span><textarea name="escalationRules" defaultValue={(planning.policy.escalationRules.length ? planning.policy.escalationRules : escalationDefaults).join("\n")} /></label><footer className="wide"><p>Changing policy creates v{planning.policy.version + 1}; it never rewrites prior system decisions.</p><button disabled={status === "SUBMITTING"}>Record policy v{planning.policy.version + 1}</button></footer></form>
      </section>
      <aside className="cpRunPanel"><header><small>AUTOPILOT ORCHESTRATOR</small><h2>Run only inside policy.</h2></header><dl><div><dt>System actor</dt><dd>SYSTEM_AUTOPILOT</dd></div><div><dt>Provider requests</dt><dd>{planning.run.providerRequests}</dd></div><div><dt>Planning spend</dt><dd>${planning.run.spendUsd.toFixed(2)}</dd></div><div><dt>Production dispatch</dt><dd>{planning.handoff.productionDispatchAuthorized ? "POLICY AUTHORIZED" : "NOT AUTHORIZED"}</dd></div></dl><button disabled={!runReady || status === "SUBMITTING"} onClick={() => command("RUN_CONTENT_AUTOPILOT")}>{planning.run.version ? `Compile plan v${planning.run.version + 1}` : "Run Content Autopilot"}</button><div className="cpRunActions"><button disabled={planning.policy.state !== "ACTIVE" || status === "SUBMITTING"} onClick={() => command("PAUSE_AUTOPILOT")}>Pause</button><button disabled={!(["PAUSED", "EMERGENCY_STOPPED"].includes(planning.policy.state)) || status === "SUBMITTING"} onClick={() => command("RESUME_AUTOPILOT")}>Resume</button><button className="danger" disabled={!planning.policy.version || planning.policy.state === "EMERGENCY_STOPPED" || status === "SUBMITTING"} onClick={() => command("EMERGENCY_STOP")}>Emergency stop</button></div>{message && <p className={`cpMessage ${status.toLowerCase()}`} role="status">{message}</p>}<footer><strong>{planning.handoff.state.replaceAll("_", " ")}</strong>{planning.handoff.blockers.map((item) => <span key={item}>{item}</span>)}</footer></aside>
    </div>
    {planning.run.state === "COMPLETE" && <>
      <section className="cpSection"><header><div><small>SLICE 2 · CONTENT SYSTEM COMPILER</small><h2>Repeatable pillars and series</h2></div><span>{planning.pillars.length} pillars · {planning.series.length} series</span></header><div className="cpPillars">{planning.pillars.map((pillar) => <article key={pillar.id}><header><span>0{pillar.position}</span><StatusPill tone="good">{pillar.state}</StatusPill></header><h3>{pillar.title}</h3><p>{pillar.purpose}</p><dl><div><dt>Audience need</dt><dd>{pillar.audienceNeed}</dd></div><div><dt>Differentiation</dt><dd>{pillar.differentiation}</dd></div><div><dt>Evidence</dt><dd>{pillar.evidenceRequirement}</dd></div></dl><div className="cpSeries">{planning.series.filter((item) => item.pillarId === pillar.id).map((item) => <div key={item.id}><small>{item.format}</small><strong>{item.title}</strong><p>{item.repeatablePromise}</p></div>)}</div></article>)}</div></section>
      <section className="cpSection"><header><div><small>SLICE 3 · CONTENT OPPORTUNITY BACKLOG</small><h2>Priority without a total score</h2></div><span>{planning.opportunities.length} system-ranked</span></header><div className="cpOpportunities">{planning.opportunities.map((item) => <article key={item.id}><header><span>#{item.systemRank}</span><StatusPill>{item.productionComplexity}</StatusPill></header><h3>{item.title}</h3><p>{item.coreQuestion}</p><Axes item={item} /><footer><span>{item.evidenceRefs.join(" · ")}</span><strong>Ceiling ${item.estimatedCostUsd.toFixed(2)}</strong></footer></article>)}</div></section>
      <section className="cpPlanGrid"><div className="cpSection"><header><div><small>SLICE 4 · EDITORIAL PLANNING</small><h2>{planning.editorialPlan.horizonDays}-day publishing sequence</h2></div><StatusPill tone="good">{planning.editorialPlan.state}</StatusPill></header><p className="cpRationale">{planning.editorialPlan.rationale}</p><ol className="cpCalendar">{planning.editorialPlan.items.map((item) => <li key={item.id}><time>Day {item.publishOffsetDays + 1}</time><span><strong>{item.title}</strong><small>Sequence {item.sequence} · {item.state}</small></span></li>)}</ol></div><aside className="cpSection"><header><div><small>EXCEPTIONS INBOX</small><h2>Owner attention only when needed</h2></div><StatusPill tone={planning.summary.openExceptions ? "warn" : "good"}>{planning.summary.openExceptions ? `${planning.summary.openExceptions} OPEN` : "CLEAR"}</StatusPill></header>{planning.exceptions.length ? <div className="cpExceptions">{planning.exceptions.map((item) => <article key={item.id}><small>{item.severity} · {item.type}</small><strong>{item.title}</strong><p>{item.detail}</p><span>{item.owningAuthority}</span></article>)}</div> : <div className="cpEmpty"><strong>No owner intervention required.</strong><p>All current planning decisions remain inside policy and evidence boundaries.</p></div>}<details className="cpAudit"><summary>Autopilot activity timeline <b>+</b></summary>{planning.audit.map((item) => <article key={item.id}><span>{item.eventType.replaceAll("_", " ")}</span><small>{item.actorType} · policy v{item.policyVersion} · strategy v{item.strategyVersion}</small></article>)}</details></aside></section>
      <section className="cpSection"><header><div><small>SLICE 5 · PRODUCTION BRIEF COMPILER</small><h2>Evidence-bound briefs</h2></div><span>{planning.summary.briefsReady} ready</span></header><div className="cpBriefs">{planning.briefs.map((brief) => <details key={brief.id}><summary><span><small>{brief.state} · v{brief.version}</small><strong>{brief.title}</strong></span><b>+</b></summary><div><p><strong>Viewer payoff:</strong> {brief.viewerPayoff}</p><p><strong>Hook:</strong> {brief.hook}</p><div><section><small>NARRATIVE</small><ol>{brief.narrativeStructure.map((item) => <li key={item}>{item}</li>)}</ol></section><section><small>EVIDENCE</small><ul>{brief.evidenceRequirements.map((item) => <li key={item}>{item}</li>)}</ul></section><section><small>VISUALS</small><ul>{brief.visualOpportunities.map((item) => <li key={item}>{item}</li>)}</ul></section><section><small>RISK CONTROLS</small><ul>{brief.riskControls.slice(0, 6).map((item) => <li key={item}>{item}</li>)}</ul></section></div><footer>{Math.round(brief.targetDurationSeconds / 60)} minutes · cost ceiling ${brief.costCeilingUsd.toFixed(2)} · provider requests 0</footer></div></details>)}</div></section>
    </>}
  </>;
}

function Studio() {
  const params = useSearchParams(), [scope, setScope] = useState(params.get("channel") || ""), [data, setData] = useState<ChannelStudioProjection | null>(null), [error, setError] = useState<string | null>(null), [refresh, setRefresh] = useState(0);
  useEffect(() => { let active = true; fetch(`/api/factory/channel-studio${scope ? `?channel=${encodeURIComponent(scope)}` : ""}`, { cache: "no-store" }).then(async (response) => { const payload = await response.json() as ChannelStudioProjection & { error?: string }; if (!response.ok) throw new Error(payload.error || "Channel Studio projection is unavailable"); if (active) setData(payload); }).catch((reason) => active && setError(reason instanceof Error ? reason.message : "Channel Studio projection is unavailable")); return () => { active = false; }; }, [scope, refresh]);
  function changeScope(value: string) { setData(null); setError(null); setScope(value); }
  function reload() { setData(null); setError(null); setRefresh((value) => value + 1); }
  return <FactoryShell active="studio"><ProjectionState loading={!data && !error} error={error} data={data} label="Channel Studio" />{data && <><header className="pfTop"><div><p>CHANNEL STUDIO · AUTOPILOT CONTROL</p><h1>Build once. Operate by exception.</h1><span>Translate the active strategy into pillars, series, opportunities, an editorial plan and production briefs—with owner attention reserved for material exceptions.</span></div><label className="pfSelect"><span>CHANNEL SCOPE</span><select value={scope} onChange={(event) => changeScope(event.target.value)}><option value="">Default portfolio channel</option>{data.channels.map((channel) => <option value={channel.id} key={channel.id}>{channel.name}</option>)}</select></label></header>{data.selectedChannel ? <><section className="pfStudioIdentity"><span className="pfAvatar">{data.selectedChannel.name.slice(0, 2).toUpperCase()}</span><div><small>{data.selectedChannel.id}</small><h2>{data.selectedChannel.name}</h2><p>{data.selectedChannel.market} · {data.selectedChannel.language} · {data.nicheDecision.currentNiche}</p></div><StatusPill tone={data.integrity.state === "READY" ? "good" : "warn"}>{data.integrity.state}</StatusPill></section><AutopilotWorkspace data={data} refresh={reload} /><details className="cpLegacy"><summary><span><small>COMPATIBILITY & PROTECTED PRODUCTION STATE</small><strong>Legacy topics and existing Video Engine portfolio</strong></span><b>+</b></summary><div><div className="pfBandSummary">{bands.map((band) => <div key={band}><small>{band}</small><strong>{data.summary[band]}</strong></div>)}</div>{data.portfolio.length ? <div className="pfTable">{data.portfolio.map((item) => <Link href={`/projects/${encodeURIComponent(item.id)}`} key={item.id}><span><small>{item.id} · {item.pillar || "Unassigned"}</small><strong>{item.title}</strong><em>{item.nextAction}</em></span><span><StatusPill>{item.rawStatus}</StatusPill><b>{item.score}/100</b></span></Link>)}</div> : <div className="pfEmpty"><h3>No content bridge records</h3></div>}<header><div><p>LEGACY V1 · VIDEO TOPICS</p><h2>Preserved, never promoted into a niche</h2></div><span>{data.legacyTopicCandidates.length}</span></header><div className="pfCompactList">{data.legacyTopicCandidates.map((item) => <article key={item.id}><small>{item.entityType} · {item.score}/100</small><strong>{item.title}</strong><p>{item.centralQuestion || item.viewerPromise}</p></article>)}</div></div></details></> : <div className="pfEmpty"><h3>No canonical channels</h3></div>}</>}</FactoryShell>;
}

export default function ChannelStudioPage() { return <Suspense fallback={<FactoryShell active="studio"><ProjectionState loading error={null} data={null} label="Channel Studio" /></FactoryShell>}><Studio /></Suspense>; }
