"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense, useEffect, useState } from "react";
import type { FormEvent } from "react";
import type { ChannelStudioProjection, ContentBand } from "../channel-studio-contract";
import type { ContentAutopilotImpactPreview, ContentPlanningProjection } from "../content-planning-contract";
import { FactoryShell, ProjectionState, StatusPill } from "../factory-shell";

const bands: ContentBand[] = ["OPPORTUNITY", "BACKLOG", "PLANNED", "PRODUCTION", "TERMINAL", "UNKNOWN"];
const escalationDefaults = ["Material strategy change", "Evidence contradiction or readiness below policy", "Legal, safety or unsupported-claim risk", "Cost above the per-video ceiling", "Repair limit exhausted", "Publishing outside approved boundaries"];

function Axes({ item }: { item: ContentPlanningProjection["opportunities"][number] }) { return <div className="cpAxes"><span><small>Strategy fit</small><strong>{item.axes.strategyFit}</strong></span><span><small>Demand</small><strong>{item.axes.audienceDemand}</strong></span><span><small>Differentiate</small><strong>{item.axes.differentiation}</strong></span><span><small>Evidence</small><strong>{item.axes.evidenceReadiness}</strong></span></div>; }

function AutopilotWorkspace({ data, refresh }: { data: ChannelStudioProjection; refresh: () => void }) {
  const planning = data.contentPlanning;
  const [status, setStatus] = useState("IDLE"), [message, setMessage] = useState<string | null>(null);
  if (!planning || !data.selectedChannel) return <section className="cpUnavailable"><h2>Content System & Planning unavailable</h2><p>The projection failed closed; no local or demonstration plan was substituted.</p></section>;
  async function command(action: "CONFIGURE_AUTOMATION_POLICY" | "RUN_CONTENT_AUTOPILOT" | "PAUSE_AUTOPILOT" | "RESUME_AUTOPILOT" | "EMERGENCY_STOP", policy?: Record<string, unknown>) {
    setStatus("SUBMITTING"); setMessage(null);
    try {
      const response = await fetch("/api/factory/content-autopilot", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": `content:${planning.channelId}:${action.toLowerCase()}:${Date.now()}` }, body: JSON.stringify({ action, channelId: planning.channelId, expectedPolicyVersion: planning.policy.version, expectedRunVersion: planning.run.version, ...(policy ? { policy } : {}) }) });
      const payload = await response.json() as { outcome?: string; error?: { message?: string } };
      if (!response.ok) throw new Error(payload.error?.message || "Content Autopilot command failed");
      setStatus("RECORDED"); setMessage(`${action.replaceAll("_", " ")} · ${payload.outcome}`); refresh();
    } catch (error) { setStatus("ERROR"); setMessage(error instanceof Error ? error.message : "Content Autopilot command failed"); }
  }
  function configure(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); command("CONFIGURE_AUTOMATION_POLICY", { mode: String(form.get("mode")), dailyBudgetUsd: Number(form.get("dailyBudgetUsd")), monthlyBudgetUsd: Number(form.get("monthlyBudgetUsd")), perVideoCostCeilingUsd: Number(form.get("perVideoCostCeilingUsd")), cadencePerMonth: Number(form.get("cadencePerMonth")), repairLimit: Number(form.get("repairLimit")), riskTolerance: String(form.get("riskTolerance")), autoProduction: form.get("autoProduction") === "on", autoPublish: form.get("autoPublish") === "on", escalationRules: String(form.get("escalationRules")).split("\n").map((item) => item.trim()).filter(Boolean) }); }
  const runReady = planning.strategy.state === "ACTIVE" && planning.policy.state === "ACTIVE";
  const productionFeComplete = planning.run.state === "COMPLETE"
    && planning.handoff.state === "READY_FOR_PRODUCTION"
    && planning.summary.planned === planning.policy.cadencePerMonth
    && planning.summary.briefsReady === planning.policy.cadencePerMonth
    && planning.handoff.eligibleBriefs === planning.policy.cadencePerMonth
    && planning.briefs.every((brief) => brief.state === "READY_FOR_PRODUCTION");
  const productionQaComplete = productionFeComplete
    && planning.integrity.state === "READY"
    && planning.summary.openExceptions === 0
    && planning.summary.providerRequests === 0
    && planning.summary.spendUsd === 0
    && planning.handoff.blockers.length === 0
    && !planning.handoff.publishingAuthorized;
  const sliceStates = [
    planning.policy.state,
    planning.run.state,
    planning.run.state,
    planning.run.state,
    planning.run.state,
    planning.run.state,
    productionFeComplete ? "COMPLETE" : "PENDING",
    productionQaComplete ? "COMPLETE" : "PENDING",
  ];
  return <>
    <section className="cpHero">
      <div><small>CONTENT SYSTEM & PLANNING V1 · AUTOPILOT-FIRST</small><h2>{planning.handoff.state === "READY_FOR_PRODUCTION" ? `${planning.summary.briefsReady} briefs ready for production` : `${planning.summary.briefsReady} of ${planning.policy.cadencePerMonth || 0} briefs ready — ${Math.max(0, planning.policy.cadencePerMonth - planning.summary.briefsReady)} missing`}</h2><p>{planning.strategy.viewerPromise || "An active strategy viewer promise is required."}</p><div className="cpHeroBadges"><StatusPill tone={planning.policy.state === "ACTIVE" ? "good" : "warn"}>{planning.policy.mode || "POLICY REQUIRED"}</StatusPill><span>Policy v{planning.policy.version}</span><span>Strategy v{planning.strategy.version}</span><span>Run v{planning.run.version}</span></div></div>
      <aside><div><small>PILLARS</small><strong>{planning.summary.pillars}</strong></div><div><small>SERIES</small><strong>{planning.summary.series}</strong></div><div><small>OPPORTUNITIES</small><strong>{planning.summary.opportunities}</strong></div><div><small>BRIEFS READY</small><strong>{planning.summary.briefsReady}</strong></div><div><small>OPEN EXCEPTIONS</small><strong>{planning.summary.openExceptions}</strong></div><div><small>PLANNING SPEND</small><strong>${planning.summary.spendUsd.toFixed(2)}</strong></div></aside>
    </section>
    <section className="cpPath" aria-label="Content System and Planning slices">{["Authority", "Content system", "Backlog", "Editorial plan", "Brief compiler", "Orchestrator", "Production FE", "Production QA"].map((label, index) => <article className={["ACTIVE", "COMPLETE"].includes(sliceStates[index]) ? "done" : ""} key={label}><span>0{index + 1}</span><strong>{label}</strong><small>{sliceStates[index]}</small></article>)}</section>
    <div className="cpControlGrid">
      <section className="cpPolicy"><header><div><small>SLICE 1 · AUTOMATION POLICY & AUTHORITY</small><h2>Owner sets the envelope once.</h2><p>Autopilot acts only inside this versioned policy. Strategic, risk and cost exceptions return to the owner.</p></div><StatusPill tone={planning.policy.state === "ACTIVE" ? "good" : planning.policy.state === "EMERGENCY_STOPPED" ? "bad" : "warn"}>{planning.policy.state}</StatusPill></header>
        <form onSubmit={configure}><label><span>Operating mode</span><select name="mode" defaultValue={planning.policy.mode || "FULL_AUTOPILOT"}><option value="FULL_AUTOPILOT">Full Autopilot</option><option value="EXCEPTIONS_ONLY">Exceptions only</option><option value="EXPERT_REVIEW">Expert review</option></select></label><label><span>Risk tolerance</span><select name="riskTolerance" defaultValue={planning.policy.riskTolerance || "LOW"}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label><span>Daily budget · USD</span><input name="dailyBudgetUsd" type="number" min="0" step="0.01" defaultValue={planning.policy.dailyBudgetUsd || 25} /></label><label><span>Monthly budget · USD</span><input name="monthlyBudgetUsd" type="number" min="0" step="0.01" defaultValue={planning.policy.monthlyBudgetUsd || 500} /></label><label><span>Per-video ceiling · USD</span><input name="perVideoCostCeilingUsd" type="number" min="0" step="0.01" defaultValue={planning.policy.perVideoCostCeilingUsd || 40} /></label><label><span>Videos per month</span><input name="cadencePerMonth" type="number" min="1" max="60" defaultValue={planning.policy.cadencePerMonth || 8} /></label><label><span>Automatic repair limit</span><input name="repairLimit" type="number" min="0" max="4" defaultValue={planning.policy.repairLimit || 1} /></label><div className="cpSwitches"><label><input name="autoProduction" type="checkbox" defaultChecked={planning.policy.autoProduction} /><span>Authorize automatic production handoff</span></label><label><input name="autoPublish" type="checkbox" defaultChecked={planning.policy.autoPublish} /><span>Authorize automatic publishing after downstream QA</span></label></div><label className="wide"><span>Mandatory escalation rules · one per line</span><textarea name="escalationRules" defaultValue={(planning.policy.escalationRules.length ? planning.policy.escalationRules : escalationDefaults).join("\n")} /></label><footer className="wide"><p>Changing policy creates v{planning.policy.version + 1}; it never rewrites prior system decisions.</p><button disabled={status === "SUBMITTING"}>Record policy v{planning.policy.version + 1}</button></footer></form>
      </section>
      <aside className="cpRunPanel"><header><small>AUTOPILOT ORCHESTRATOR</small><h2>Run only inside policy.</h2></header><dl><div><dt>System actor</dt><dd>SYSTEM_AUTOPILOT</dd></div><div><dt>Provider requests</dt><dd>{planning.run.providerRequests}</dd></div><div><dt>Planning spend</dt><dd>${planning.run.spendUsd.toFixed(2)}</dd></div><div><dt>Production dispatch</dt><dd>{planning.handoff.productionDispatchAuthorized ? "POLICY AUTHORIZED" : "NOT AUTHORIZED"}</dd></div></dl><button disabled={!runReady || status === "SUBMITTING"} onClick={() => command("RUN_CONTENT_AUTOPILOT")}>{planning.run.version ? `Compile plan v${planning.run.version + 1}` : "Run Content Autopilot"}</button><div className="cpRunActions"><button disabled={planning.policy.state !== "ACTIVE" || status === "SUBMITTING"} onClick={() => command("PAUSE_AUTOPILOT")}>Pause</button><button disabled={!(["PAUSED", "EMERGENCY_STOPPED"].includes(planning.policy.state)) || status === "SUBMITTING"} onClick={() => command("RESUME_AUTOPILOT")}>Resume</button><button className="danger" disabled={!planning.policy.version || planning.policy.state === "EMERGENCY_STOPPED" || status === "SUBMITTING"} onClick={() => command("EMERGENCY_STOP")}>Emergency stop</button></div>{message && <p className={`cpMessage ${status.toLowerCase()}`} role="status">{message}</p>}<footer><strong>{planning.handoff.state.replaceAll("_", " ")}</strong>{planning.handoff.blockers.map((item) => <span key={item}>{item}</span>)}</footer></aside>
    </div>
    {planning.run.state === "COMPLETE" && <>
      <section className="cpSection"><header><div><small>SLICE 2 · CONTENT SYSTEM COMPILER</small><h2>Repeatable pillars and series</h2></div><span>{planning.pillars.length} pillars · {planning.series.length} series</span></header><div className="cpPillars">{planning.pillars.map((pillar) => <article key={pillar.id}><header><span>0{pillar.position}</span><StatusPill tone="good">{pillar.state}</StatusPill></header><h3>{pillar.title}</h3><p>{pillar.purpose}</p><dl><div><dt>Audience need</dt><dd>{pillar.audienceNeed}</dd></div><div><dt>Differentiation</dt><dd>{pillar.differentiation}</dd></div><div><dt>Evidence</dt><dd>{pillar.evidenceRequirement}</dd></div></dl><div className="cpSeries">{planning.series.filter((item) => item.pillarId === pillar.id).map((item) => <div key={item.id}><small>{item.format}</small><strong>{item.title}</strong><p>{item.repeatablePromise}</p></div>)}</div></article>)}</div></section>
      <section className="cpSection"><header><div><small>SLICE 3 · CONTENT OPPORTUNITY BACKLOG</small><h2>Priority without a total score</h2></div><span>{planning.opportunities.length} system-ranked</span></header><div className="cpOpportunities">{planning.opportunities.map((item) => <article key={item.id}><header><span>#{item.systemRank}</span><StatusPill>{item.productionComplexity}</StatusPill></header><h3>{item.title}</h3><p>{item.coreQuestion}</p><Axes item={item} /><footer><span>{item.evidenceRefs.join(" · ")}</span><strong>Ceiling ${item.estimatedCostUsd.toFixed(2)}</strong></footer></article>)}</div></section>
      <section className="cpPlanGrid"><div className="cpSection"><header><div><small>SLICE 4 · EDITORIAL PLANNING</small><h2>{planning.editorialPlan.horizonDays}-day publishing sequence</h2></div><StatusPill tone="good">{planning.editorialPlan.state}</StatusPill></header><p className="cpRationale">{planning.editorialPlan.rationale}</p><ol className="cpCalendar">{planning.editorialPlan.items.map((item) => <li key={item.id}><time>Day {item.publishOffsetDays + 1}</time><span><strong>{item.title}</strong><small>Sequence {item.sequence} · {item.state}</small></span></li>)}</ol></div><aside className="cpSection"><header><div><small>EXCEPTIONS INBOX</small><h2>Owner attention only when needed</h2></div><StatusPill tone={planning.summary.openExceptions ? "warn" : "good"}>{planning.summary.openExceptions ? `${planning.summary.openExceptions} OPEN` : "CLEAR"}</StatusPill></header>{planning.exceptions.length ? <div className="cpExceptions">{planning.exceptions.map((item) => <article key={item.id}><small>{item.severity} · {item.type}</small><strong>{item.title}</strong><p>{item.detail}</p><span>{item.owningAuthority}</span></article>)}</div> : <div className="cpEmpty"><strong>No owner intervention required.</strong><p>All current planning decisions remain inside policy and evidence boundaries.</p></div>}<details className="cpAudit"><summary>Autopilot activity timeline <b>+</b></summary>{planning.audit.map((item) => <article key={item.id}><span>{item.eventType.replaceAll("_", " ")}</span><small>{item.actorType} · policy v{item.policyVersion} · strategy v{item.strategyVersion}</small></article>)}</details></aside></section>
      <section className="cpSection"><header><div><small>SLICE 5 · PRODUCTION BRIEF COMPILER</small><h2>Evidence-bound briefs</h2></div><span>{planning.summary.briefsReady} ready</span></header><div className="cpBriefs">{planning.briefs.map((brief) => <details key={brief.id}><summary><span><small>{brief.state} · v{brief.version}</small><strong>{brief.title}</strong></span><b>+</b></summary><div><p><strong>Viewer payoff:</strong> {brief.viewerPayoff}</p><p><strong>Hook:</strong> {brief.hook}</p><div><section><small>NARRATIVE</small><ol>{brief.narrativeStructure.map((item) => <li key={item}>{item}</li>)}</ol></section><section><small>EVIDENCE</small><ul>{brief.evidenceRequirements.map((item) => <li key={item}>{item}</li>)}</ul></section><section><small>VISUALS</small><ul>{brief.visualOpportunities.map((item) => <li key={item}>{item}</li>)}</ul></section><section><small>RISK CONTROLS</small><ul>{brief.riskControls.slice(0, 6).map((item) => <li key={item}>{item}</li>)}</ul></section></div><footer>{Math.round(brief.targetDurationSeconds / 60)} minutes · cost ceiling ${brief.costCeilingUsd.toFixed(2)} · provider requests 0</footer></div></details>)}</div></section>
    </>}
  </>;
}

type OwnerTab = "overview" | "settings" | "plan" | "briefs" | "system";
type OwnerPolicyDraft = {
  mode: string; dailyBudgetUsd: number; monthlyBudgetUsd: number; perVideoCostCeilingUsd: number; cadencePerMonth: number; repairLimit: number; riskTolerance: string; autoProduction: boolean; autoPublish: boolean; escalationRules: string[];
};

function OwnerAutomationWorkspace({ data, refresh }: { data: ChannelStudioProjection; refresh: () => void }) {
  const planning = data.contentPlanning, [tab, setTab] = useState<OwnerTab>("overview"), [status, setStatus] = useState("IDLE"), [message, setMessage] = useState<string | null>(null), [impact, setImpact] = useState<ContentAutopilotImpactPreview | null>(null), [pendingPolicy, setPendingPolicy] = useState<OwnerPolicyDraft | null>(null);
  if (!planning || !data.selectedChannel) return <section className="cpUnavailable"><h2>Monthly planning is unavailable</h2><p>The canonical projection failed closed. No sample plan was substituted.</p></section>;
  const busy = status === "SUBMITTING", exact = planning.coverage.complete && planning.integrity.state === "READY", gap = planning.coverage.missing;
  const stages = [
    { label: "Strategy", state: planning.strategy.state === "ACTIVE" ? "Complete" : "Needs attention" },
    { label: "Automation settings", state: planning.policy.state === "ACTIVE" ? "Active" : "Needs attention" },
    { label: "Monthly plan", state: planning.coverage.planned === planning.coverage.target ? "Complete" : planning.coverage.planned + " of " + planning.coverage.target },
    { label: "Production briefs", state: planning.coverage.briefsReady === planning.coverage.target ? "Ready" : planning.coverage.briefsReady + " of " + planning.coverage.target },
  ];
  const labels: Array<{ id: OwnerTab; label: string }> = [{ id: "overview", label: "Overview" }, { id: "settings", label: "Automation settings" }, { id: "plan", label: "Monthly plan" }, { id: "briefs", label: "Production briefs" }, { id: "system", label: "Activity & system details" }];

  async function command(action: "APPLY_POLICY_AND_REBUILD_PLAN" | "PAUSE_AUTOPILOT" | "RESUME_AUTOPILOT" | "EMERGENCY_STOP", policy?: OwnerPolicyDraft) {
    setStatus("SUBMITTING"); setMessage(null);
    try {
      const response = await fetch("/api/factory/content-autopilot", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": "content:" + planning.channelId + ":" + action.toLowerCase() + ":" + Date.now() }, body: JSON.stringify({ action, channelId: planning.channelId, expectedPolicyVersion: planning.policy.version, expectedRunVersion: planning.run.version, ...(policy ? { policy } : {}) }) });
      const payload = await response.json() as { outcome?: string; error?: { message?: string } };
      if (!response.ok) throw new Error(payload.error?.message || "The automation change could not be recorded");
      setStatus("RECORDED"); setMessage(action === "APPLY_POLICY_AND_REBUILD_PLAN" ? "Changes applied. The monthly plan and production briefs were rebuilt together." : "Automation status updated.");
      setImpact(null); setPendingPolicy(null); refresh();
    } catch (error) { setStatus("ERROR"); setMessage(error instanceof Error ? error.message : "The automation change failed"); }
  }
  async function reviewChanges(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus("SUBMITTING"); setMessage(null); setImpact(null);
    const form = new FormData(event.currentTarget), policy: OwnerPolicyDraft = { mode: String(form.get("mode")), dailyBudgetUsd: Number(form.get("dailyBudgetUsd")), monthlyBudgetUsd: Number(form.get("monthlyBudgetUsd")), perVideoCostCeilingUsd: Number(form.get("perVideoCostCeilingUsd")), cadencePerMonth: Number(form.get("cadencePerMonth")), repairLimit: Number(form.get("repairLimit")), riskTolerance: String(form.get("riskTolerance")), autoProduction: form.get("autoProduction") === "on", autoPublish: form.get("autoPublish") === "on", escalationRules: String(form.get("escalationRules")).split("\n").map((item) => item.trim()).filter(Boolean) };
    try {
      const response = await fetch("/api/factory/content-autopilot/preview", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "APPLY_POLICY_AND_REBUILD_PLAN", channelId: planning.channelId, expectedPolicyVersion: planning.policy.version, expectedRunVersion: planning.run.version, policy }) });
      const payload = await response.json() as ContentAutopilotImpactPreview & { error?: { message?: string } };
      if (!response.ok) throw new Error(payload.error?.message || "Impact preview is unavailable");
      setPendingPolicy(policy); setImpact(payload); setStatus("REVIEW"); setMessage("Review the exact impact below before applying.");
    } catch (error) { setStatus("ERROR"); setMessage(error instanceof Error ? error.message : "Impact preview failed"); }
  }

  return <section className="ownerWorkspace">
    <nav className="ownerTabs" aria-label="Channel Studio sections">{labels.map((item) => <button type="button" className={tab === item.id ? "active" : ""} aria-current={tab === item.id ? "page" : undefined} onClick={() => setTab(item.id)} key={item.id}>{item.label}</button>)}</nav>
    {tab === "overview" && <>
      <section className="ownerHero"><div><small>CHANNEL AUTOMATION</small><h2>{exact ? "This month is fully planned." : gap + " production brief" + (gap === 1 ? "" : "s") + " still needed."}</h2><p>{exact ? "The publishing target, monthly plan and production briefs match exactly. Automatic handoff is governed by your settings." : "Production handoff is blocked until the target, plan and briefs match exactly."}</p><button type="button" onClick={() => setTab(exact ? "plan" : "settings")}>{exact ? "View monthly plan" : "Fix monthly plan"}</button></div><aside><div><small>Monthly target</small><strong>{planning.coverage.target}</strong></div><div><small>Episodes planned</small><strong>{planning.coverage.planned}</strong></div><div><small>Briefs ready</small><strong>{planning.coverage.briefsReady}</strong></div><div><small>Projected cost</small><strong>${planning.budget.projectedCostUsd.toFixed(2)}</strong></div></aside></section>
      <section className="ownerStages">{stages.map((stage, index) => <article className={stage.state === "Complete" || stage.state === "Active" || stage.state === "Ready" ? "done" : ""} key={stage.label}><span>{index + 1}</span><div><strong>{stage.label}</strong><small>{stage.state}</small></div></article>)}</section>
      <section className="ownerOverviewGrid"><article><small>NEXT ACTION</small><h3>{exact ? "No owner action required" : "Rebuild the plan to match the monthly target"}</h3><p>{exact ? "Automation will return only material evidence, risk or budget exceptions." : planning.handoff.blockers[0] || "Review automation settings and rebuild the plan."}</p></article><article><small>PRODUCTION HANDOFF</small><h3>{planning.handoff.productionDispatchAuthorized ? "Automatic handoff enabled" : "Handoff blocked"}</h3><p>Publishing remains {planning.handoff.publishingAuthorized ? "authorized after downstream QA" : "manual and outside this planning authority"}.</p></article><article><small>OWNER ATTENTION</small><h3>{planning.summary.openExceptions ? planning.summary.openExceptions + " open exception(s)" : "No intervention required"}</h3><p>Planning provider requests: {planning.summary.providerRequests}. Planning spend: ${planning.summary.spendUsd.toFixed(2)}.</p></article></section>
    </>}
    {tab === "settings" && <div className="ownerSettingsGrid"><section className="ownerSettings"><header><small>AUTOMATION SETTINGS</small><h2>Set the operating envelope once.</h2><p>Review the impact, then apply settings and rebuild the monthly plan in one atomic action.</p></header><form onSubmit={reviewChanges}>
      <label><span>Level of automation</span><select name="mode" defaultValue={planning.policy.mode || "FULL_AUTOPILOT"}><option value="FULL_AUTOPILOT">Full automation</option><option value="EXCEPTIONS_ONLY">Automation with exceptions</option><option value="EXPERT_REVIEW">Expert review required</option></select><small>Full automation asks you only about material exceptions.</small></label>
      <label><span>When owner approval is required</span><select name="riskTolerance" defaultValue={planning.policy.riskTolerance || "LOW"}><option value="LOW">Only high-impact risk</option><option value="MEDIUM">Moderate or high-impact risk</option><option value="HIGH">Any material uncertainty</option></select></label>
      <label><span>Monthly publishing target</span><input name="cadencePerMonth" type="number" min="1" max="60" defaultValue={planning.policy.cadencePerMonth || 8} /><small>The rebuilt plan and ready briefs must equal this number.</small></label>
      <label><span>Monthly planning budget · USD</span><input name="monthlyBudgetUsd" type="number" min="0" step="0.01" defaultValue={planning.policy.monthlyBudgetUsd || 500} /></label>
      <label><span>Daily production budget · USD</span><input name="dailyBudgetUsd" type="number" min="0" step="0.01" defaultValue={planning.policy.dailyBudgetUsd || 25} /></label>
      <label><span>Maximum cost per episode · USD</span><input name="perVideoCostCeilingUsd" type="number" min="0" step="0.01" defaultValue={planning.policy.perVideoCostCeilingUsd || 40} /></label>
      <label><span>Automatic repair attempts</span><input name="repairLimit" type="number" min="0" max="4" defaultValue={planning.policy.repairLimit || 1} /></label>
      <div className="ownerSwitches"><label><input name="autoProduction" type="checkbox" defaultChecked={planning.policy.autoProduction} /><span><strong>Automatic production handoff</strong><small>Allowed only after exact coverage, integrity, budget and exception checks pass.</small></span></label><label><input name="autoPublish" type="checkbox" defaultChecked={planning.policy.autoPublish} /><span><strong>Automatic publishing after downstream QA</strong><small>Keep off for manual release control.</small></span></label></div>
      <label className="wide"><span>Ask the owner when… · one rule per line</span><textarea name="escalationRules" defaultValue={(planning.policy.escalationRules.length ? planning.policy.escalationRules : escalationDefaults).join("\n")} /></label>
      <footer className="wide"><span>Previewing makes no changes and sends no provider requests.</span><button disabled={busy}>Review changes</button></footer>
    </form></section><aside className="ownerImpact"><small>IMPACT PREVIEW</small>{impact ? <><h2>{impact.proposed.target} episodes and {impact.proposed.briefsReady} ready briefs</h2><dl><div><dt>Current coverage</dt><dd>{impact.current.planned}/{impact.current.target}</dd></div><div><dt>After rebuild</dt><dd>{impact.proposed.planned}/{impact.proposed.target}</dd></div><div><dt>Projected cost</dt><dd>${impact.proposed.projectedCostUsd.toFixed(2)} / ${impact.proposed.monthlyBudgetUsd.toFixed(2)}</dd></div><div><dt>Provider requests</dt><dd>0</dd></div></dl>{impact.warnings.map((item) => <p className="warning" key={item}>{item}</p>)}{impact.blockers.map((item) => <p className="blocker" key={item}>{item}</p>)}<button disabled={!impact.canApply || busy || !pendingPolicy} onClick={() => pendingPolicy && command("APPLY_POLICY_AND_REBUILD_PLAN", pendingPolicy)}>Apply changes &amp; rebuild plan</button></> : <><h2>No pending changes</h2><p>Choose settings and select <strong>Review changes</strong>. You will see the exact episode count, ready briefs, cost and blockers before anything changes.</p></>}{message && <p className={"ownerMessage " + status.toLowerCase()} role="status">{message}</p>}</aside></div>}
    {tab === "plan" && <section className="ownerPanel"><header><div><small>30-DAY PLAN</small><h2>{planning.coverage.planned} of {planning.coverage.target} episodes planned</h2><p>Every row is a distinct Episode Concept linked to its source opportunity and evidence.</p></div><StatusPill tone={planning.coverage.complete ? "good" : "warn"}>{planning.coverage.complete ? "COMPLETE" : gap + " MISSING"}</StatusPill></header><ol className="ownerPlanList">{planning.editorialPlan.items.map((item) => <li key={item.id}><time>Day {item.publishOffsetDays + 1}</time><span><strong>{item.title}</strong><small>Episode {item.sequence} · {item.state}</small></span></li>)}</ol></section>}
    {tab === "briefs" && <section className="ownerPanel"><header><div><small>PRODUCTION BRIEFS</small><h2>{planning.coverage.briefsReady} of {planning.coverage.target} ready</h2><p>Production handoff stays blocked unless every monthly slot has one evidence-bound brief.</p></div><StatusPill tone={planning.coverage.complete ? "good" : "warn"}>{planning.handoff.productionDispatchAuthorized ? "HANDOFF ENABLED" : "HANDOFF BLOCKED"}</StatusPill></header><div className="ownerBriefs">{planning.briefs.map((brief, index) => <details key={brief.id}><summary><span><small>Episode {index + 1} · {brief.state.replaceAll("_", " ")}</small><strong>{brief.title}</strong></span><b>+</b></summary><div><p><strong>Viewer payoff:</strong> {brief.viewerPayoff}</p><p><strong>Opening hook:</strong> {brief.hook}</p><p><strong>Evidence:</strong> {brief.evidenceRequirements.join(" · ")}</p><footer>{Math.round(brief.targetDurationSeconds / 60)} min · projected ceiling ${brief.costCeilingUsd.toFixed(2)}</footer></div></details>)}</div></section>}
    {tab === "system" && <><section className="ownerPanel"><header><div><small>ACTIVITY &amp; SYSTEM DETAILS</small><h2>Append-only planning lineage</h2><p>Technical versions and emergency controls live here, away from the daily owner workflow.</p></div><StatusPill tone={planning.integrity.state === "READY" ? "good" : "warn"}>{planning.integrity.state}</StatusPill></header><div className="ownerSystemFacts"><div><small>Strategy</small><strong>v{planning.strategy.version}</strong></div><div><small>Settings</small><strong>v{planning.policy.version}</strong></div><div><small>Plan run</small><strong>v{planning.run.version}</strong></div><div><small>Planning model</small><strong>{planning.coverage.modelVersion === "V2_EPISODE_CONCEPTS" ? "Episode Concepts V2" : "Compatibility V1"}</strong></div><div><small>Provider requests</small><strong>{planning.summary.providerRequests}</strong></div><div><small>Planning spend</small><strong>${planning.summary.spendUsd.toFixed(2)}</strong></div></div><div className="ownerSystemActions"><button disabled={planning.policy.state !== "ACTIVE" || busy} onClick={() => command("PAUSE_AUTOPILOT")}>Pause automation</button><button disabled={!["PAUSED", "EMERGENCY_STOPPED"].includes(planning.policy.state) || busy} onClick={() => command("RESUME_AUTOPILOT")}>Resume automation</button><button className="danger" disabled={!planning.policy.version || planning.policy.state === "EMERGENCY_STOPPED" || busy} onClick={() => command("EMERGENCY_STOP")}>Emergency stop</button></div>{message && <p className={"ownerMessage " + status.toLowerCase()} role="status">{message}</p>}<details className="ownerAudit"><summary>View technical activity ({planning.audit.length}) <b>+</b></summary>{planning.audit.map((item) => <article key={item.id}><strong>{item.eventType.replaceAll("_", " ")}</strong><small>{item.actorType} · settings v{item.policyVersion} · strategy v{item.strategyVersion}</small></article>)}</details></section><details className="ownerTechnical"><summary>Content system, opportunities and scoring details <b>+</b></summary><div className="cpPillars">{planning.pillars.map((pillar) => <article key={pillar.id}><h3>{pillar.title}</h3><p>{pillar.purpose}</p></article>)}</div><div className="cpOpportunities">{planning.opportunities.map((item) => <article key={item.id}><header><span>#{item.systemRank}</span><StatusPill>{item.productionComplexity}</StatusPill></header><h3>{item.title}</h3><p>{item.coreQuestion}</p><Axes item={item} /></article>)}</div></details></>}
  </section>;
}

function Studio() {
  const params = useSearchParams(), [scope, setScope] = useState(params.get("channel") || ""), [data, setData] = useState<ChannelStudioProjection | null>(null), [error, setError] = useState<string | null>(null), [refresh, setRefresh] = useState(0);
  useEffect(() => { let active = true; fetch(`/api/factory/channel-studio${scope ? `?channel=${encodeURIComponent(scope)}` : ""}`, { cache: "no-store" }).then(async (response) => { const payload = await response.json() as ChannelStudioProjection & { error?: string }; if (!response.ok) throw new Error(payload.error || "Channel Studio projection is unavailable"); if (active) setData(payload); }).catch((reason) => active && setError(reason instanceof Error ? reason.message : "Channel Studio projection is unavailable")); return () => { active = false; }; }, [scope, refresh]);
  function changeScope(value: string) { setData(null); setError(null); setScope(value); }
  function reload() { setData(null); setError(null); setRefresh((value) => value + 1); }
  return <FactoryShell active="studio"><ProjectionState loading={!data && !error} error={error} data={data} label="Channel Studio" />{data && <><header className="pfTop"><div><p>CHANNEL STUDIO</p><h1>Plan the month. Automate the routine.</h1><span>Set one publishing target, review the impact, then let automation build the plan and production briefs. You step in only for material exceptions.</span></div><label className="pfSelect"><span>CHANNEL</span><select value={scope} onChange={(event) => changeScope(event.target.value)}><option value="">Default portfolio channel</option>{data.channels.map((channel) => <option value={channel.id} key={channel.id}>{channel.name}</option>)}</select></label></header>{data.selectedChannel ? <><section className="pfStudioIdentity"><span className="pfAvatar">{data.selectedChannel.name.slice(0, 2).toUpperCase()}</span><div><small>{data.selectedChannel.id}</small><h2>{data.selectedChannel.name}</h2><p>{data.selectedChannel.market} · {data.selectedChannel.language} · {data.nicheDecision.currentNiche}</p></div><StatusPill tone={data.integrity.state === "READY" ? "good" : "warn"}>{data.integrity.state === "READY" ? "READY" : "NEEDS ATTENTION"}</StatusPill></section><OwnerAutomationWorkspace data={data} refresh={reload} /><details className="cpLegacy"><summary><span><small>PROTECTED HISTORY</small><strong>Legacy topics and existing Video Engine portfolio</strong></span><b>+</b></summary><div><div className="pfBandSummary">{bands.map((band) => <div key={band}><small>{band}</small><strong>{data.summary[band]}</strong></div>)}</div>{data.portfolio.length ? <div className="pfTable">{data.portfolio.map((item) => <Link href={`/projects/${encodeURIComponent(item.id)}`} key={item.id}><span><small>{item.id} · {item.pillar || "Unassigned"}</small><strong>{item.title}</strong><em>{item.nextAction}</em></span><span><StatusPill>{item.rawStatus}</StatusPill><b>{item.score}/100</b></span></Link>)}</div> : <div className="pfEmpty"><h3>No content bridge records</h3></div>}<header><div><p>LEGACY V1 · VIDEO TOPICS</p><h2>Preserved, never promoted into a niche</h2></div><span>{data.legacyTopicCandidates.length}</span></header><div className="pfCompactList">{data.legacyTopicCandidates.map((item) => <article key={item.id}><small>{item.entityType} · {item.score}/100</small><strong>{item.title}</strong><p>{item.centralQuestion || item.viewerPromise}</p></article>)}</div></div></details></> : <div className="pfEmpty"><h3>No canonical channels</h3></div>}</>}</FactoryShell>;
}

export default function ChannelStudioPage() { return <Suspense fallback={<FactoryShell active="studio"><ProjectionState loading error={null} data={null} label="Channel Studio" /></FactoryShell>}><Studio /></Suspense>; }
